### ISSUE TITLE
received event for an invoice which is already completed

### ISSUE THREAD

**Issue by balboah** [btcpayserver/btcpayserver#2537] opened 2021-05-21 08:06 UTC
**Describe the bug**

An old invoice triggered a new webhook event (invoice_receivedPayment) months after it was already invoice_completed and "invoice is not monitored anymore".
The same e-mail was recently used for paying a different invoice id a couple of days earlier, however this invoice was also already "completed". 

It seems there is a persistent pending transaction with some kind of advertising memo that might just try addresses it finds in the blockchain, this is the one that triggered an old receiving address for the already months old completed invoice.

**To Reproduce the bug**
Steps to (hypothetically) reproduce the reported bug:
1. have a completed invoice
2. send a new pending payment to the old receiving address
3. event is triggered

**Expected behavior**

After I see "invoice is not monitored anymore" and completion, I would expect no more webhook events.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.1.1.0 (altcoins)
- Deployment Method:      docker

**Logs (if applicable)**

```

2021-02-15 | Invoice status is complete (paidOver)
2021-02-15 | Invoice foobar new event: invoice_completed (1006)
2021-02-15 | Invoice foobar is not monitored anymore.
2021-02-15 | IPN (1006 invoice_completed) sent for invoice foobar
2021-02-15 | IPN (1006 invoice_completed) sent for invoice foobar
2021-05-20 | Invoice foobar new event: invoice_receivedPayment (1002)
2021-05-20 | IPN (1002 invoice_receivedPayment) sent for invoice foobar
```

**Comment by pavlenex** [comment] 2021-06-26 11:32
@NicolasDorier What do you think?

**Comment by pavlenex** [comment] 2022-01-09 17:02
Possibly a duplicate of #968

**Comment by NicolasDorier** [comment] 2022-01-11 15:06
I think I should properly explain the monitoring concept.
`MonitoringExpiration` is the time after which a Processing invoice turn Invalid after failing to confirm for the expiration.
It doesn't mean that we stop looking at payments.

I understand why you would expect no more event to be sent for an invoice invalid/settled though.
I don't feel like removing those either though. People used it for long time, I fear some depend on it.
Maybe need more discussion with @Kukks

**Closed** 2022-09-28 09:31 UTC
Labels: Discussion
