### ISSUE TITLE
Feature request: Possibility to upload custom CSS/logo

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#161] opened 2018-05-08 16:11 UTC
Now we have to paste a link. It would be great to have a possibility to upload the files directly.

**Comment by rockstardev** [comment] 2018-05-08 20:39
I was actually thinking about supporting this for both logo and favicon. But since it would require tinkering with write permissions on hosting platform I think it's best not to do it for now.

**Comment by Kukks** [comment] 2018-05-24 08:07
Wouldn't we need to support specific storage  providers based on hosting platform such as Azure blob storage for example? Since persistent storage on vms on public clouds aren't guaranteed to keep local data saved?

**Comment by Kukks** [comment] 2018-05-28 15:16
How about if we just allow a textarea for the css and we save the image in the db as a base64? Avoids hosting platform issues

**Comment by hubiktomas** [comment] 2018-05-28 15:18
That would be a solution as both files will be probably relatively small.

**Comment by NicolasDorier** [comment] 2018-05-29 03:36
You can already customize the css. But I don't think you can set the favicon with it

**Comment by Kukks** [comment] 2018-05-29 07:30
@NicolasDorier This is so that the css and image are hosted within the site though. I've found ti troublesome for testing locally and for online instances with ssl( you need to match the protocol otherwise the stylesheet is not loaded due to mismatching protocols) which is really annoying for such a small aesthetic thing.

**Comment by pavlenex** [comment] 2019-02-19 21:06
Related #239

**Comment by pavlenex** [comment] 2019-05-23 06:25
Option to upload files added in #708 
[Custom Theming i](https://docs.btcpayserver.org/development/theme)s possible for a long time now.
So @hubiktomas I assume what you want is a direct `upload` button that will connect #708 with the UI?

We also need to do that for adding images in apps etc, so probably a larger issue than just a logo.

**Comment by pavlenex** [comment] 2020-03-22 08:02
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2020-03-22 15:49 UTC
Labels: Back-end, Brainstorming, Closing
