### ISSUE TITLE
[Bug]: Webhook is not working

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4643] opened 2023-02-14 22:15 UTC
### What is your BTCPay version?

BTCPay Server v1.7.11

### How did you deploy BTCPay Server?

Docker

### What happened?

Good day; the webhook is not working.
Last time we add our webhook without http:// 
Now I CAN'T setup webhook using our onion address without http:// 
`The field PayloadUrl is invalid.` - if I am using an onion address without http://
All webhook tests - fail!
`InvoiceCreated event could not be delivered. Error message received: The request was aborted.`

If I use HTTP://ipaddres/endpoint - all tests are green! 

### How did you encounter this bug?

Test webhook using button - Test in webhook

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by tefikoff** [comment] 2023-02-14 23:37
please help my webhook (callback) not work
please write me in telegram https://t.me/tervin

**Comment by NicolasDorier** [comment] 2023-02-15 07:02
Why is it a problem? It says URL so `http://` should be included. If it was working before, it shouldn't have.

**Comment by valsha** [comment] 2023-02-15 08:44
have no idea, but right now, when we post the .onion address in webhook, it is not working.
maybe the problem is not in HTTP://

**Comment by NicolasDorier** [comment] 2023-02-15 08:48
You need to detail more,

![image](https://user-images.githubusercontent.com/3020646/218978539-9328f921-3e43-4ce7-ad63-b9ed1b858018.png)

It works for me

**Comment by tefikoff** [comment] 2023-02-15 10:46
> You need to detail more how to repro
> 
> ![image](https://user-images.githubusercontent.com/3020646/218978539-9328f921-3e43-4ce7-ad63-b9ed1b858018.png)
> 
> It works for me

please write me in telegram https://t.me/tervin

**Comment by NicolasDorier** [comment] 2023-02-15 12:53
sorry I don't use telegram.

**Comment by dennisreimann** [comment] 2023-02-15 15:55
Closing this as a duplicate of  #4648 — the follow-up contains more details.

**Closed by dennisreimann** 2023-02-15 15:55 UTC
Labels: API, need-info
