### ISSUE TITLE
[Bug]: Db Migration, creates table in postgres, but no data is migrated

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#4623] opened 2023-02-10 23:09 UTC
### What is your BTCPay version?

BtcPay v1.7.9

### How did you deploy BTCPay Server?

Run from source using 
dotnet run --no-launch-profile -c Release --project ".\BTCPayServer\BTCPayServer.csproj" --debuglog "C:\debug.log"

### What happened?

So I created a postgres blank database "btcpayserver" and user for it
Added this to the configuration

postgres=User ID=btcpay;Password=???;Application Name=btcpayserver;Host=127.0.0.1;Port=5432;Database=btcpayserver;

and commented out the "sqlitefile" config

### How did you encounter this bug?

Ran btcpay with new postgres config for migration.
The tables were created in the postgres database, 
**however no data was migrated.**
When I access the btc pay server it was like accessing fresh instance, nothing migrated.

### Relevant log output

```shell
nothing found in log file that suggested migration was running
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment] 2023-02-11 10:56
https://github.com/btcpayserver/btcpayserver/blob/master/docs/db-migration.md

You are not supposed to comment out the sqlite config, else it does not
detect you want to do a migration

**Comment by NicolasDorier** [comment] 2023-02-11 14:05
I updated to doc to be more clear about this.
Also update, I fixed another bug on migration.

**Comment by mjlamb** [comment] 2023-02-11 19:00
Ok that seems obvious now in hindsight, however I had both db config lines uncommented and run btcpay server, it exited after some moments, No table data migrated. Nothing in debug logs.

**Comment by mjlamb** [comment] 2023-02-11 19:10
Ok I've managed to get the migration kick off now.... it gets to Files table and crashes.


info: BTCPayServer.Hosting.ToPostgresMigrationStartupTask: Migrating table: Files
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> System.InvalidCastException: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)

**Comment by mjlamb** [comment] 2023-02-11 19:16
Having a look at the sqllite "Files" table it is a "Timestamp" TEXT NOT NULL column, I'm assuming a conversion issue here.

**Comment by BlackstonerJr** [comment] 2023-02-13 18:02
Why I need pay 💰 instead claiming.!<

**Comment by mjlamb** [comment] 2023-02-14 19:44
@NicolasDorier  I've tried various date formats in the TEXT columns but the migration seems to choke on the ones I've tried.

**Comment by NicolasDorier** [comment] 2023-02-15 06:34
@mjlamb thank you for the feedback, checking

**Comment by NicolasDorier** [comment] 2023-02-15 06:47
Could reproduce, will fix and make new release today or tomorrow.

**Comment by kovivac** [comment] 2023-02-15 06:49
A megküldött bónuszok nem jelennek meg a számlán..!?

**Comment by mjlamb** [comment] 2023-02-15 06:49
Awesome your a champion!

**Comment by mjlamb** [comment] 2023-02-15 08:19
I've pulled the latest with your commit, unfortunately I still have the same error..

**Comment by mjlamb** [comment] 2023-02-15 08:20
@NicolasDorier Seems more of a conversion issue with datetime format.

**Comment by NicolasDorier** [comment] 2023-02-16 08:53
@mjlamb can you try again now?

**Comment by NicolasDorier** [comment] 2023-02-16 08:53
after `btcpay-update.sh`

**Comment by NicolasDorier** [comment] 2023-02-21 06:07
@mjlamb do you have any feedback?

**Comment by mjlamb** [comment] 2023-02-21 09:47
Ok will try again soon, sorry missed your update.

**Comment by NicolasDorier** [comment] 2023-02-22 06:06
@mjlamb let me know we will release a new version tomorrow, so if there is a bug, I'd like to fix it.

**Comment by mjlamb** [comment] 2023-02-22 06:34
@NicolasDorier  I have checked this and I still have the same error. 

info: BTCPayServer.Hosting.ToPostgresMigrationStartupTask: Migrating table: Files
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
---> System.InvalidCastException: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)

**Comment by mjlamb** [comment] 2023-02-22 06:35
I do not have btcpay-update.sh

I Run from source using
dotnet run --no-launch-profile -c Release --project ".\BTCPayServer\BTCPayServer.csproj" --debuglog "C:\debug.log"

**Comment by NicolasDorier** [comment] 2023-02-22 07:21
did you `git pull` before that?

**Comment by mjlamb** [comment] 2023-02-22 07:22
![image](https://user-images.githubusercontent.com/2274034/220550815-2784b2fb-a28a-47fe-8948-5b378ccf1f7c.png)

Yep latest

**Comment by NicolasDorier** [comment] 2023-02-22 07:37
@mjlamb I can't reproduce this, can you try to build again with `dotnet build -c Release`?

**Comment by NicolasDorier** [comment] 2023-02-22 07:46
There should be only two tables PairingCodes and Files with the problematic types.

**Comment by mjlamb** [comment] 2023-02-22 07:47
@NicolasDorier I did that just now
dotnet build -c Release
dotnet run --no-launch-profile -c Release --project ".\BTCPayServer\BTCPayServer.csproj" --debuglog "C:\debug.log"

with both the sqllite and postgres connection string.
Same error.

I have below the sample of the files table.

![image](https://user-images.githubusercontent.com/2274034/220555795-9b31ebd1-d6af-4498-8c04-7a8a47512df6.png)

**Comment by NicolasDorier** [comment] 2023-02-22 07:48
@mjlamb can you export the schema of the table so I check if I have the same in my tests?

**Comment by mjlamb** [comment] 2023-02-22 07:49
CREATE TABLE "Files" (
    "Id" TEXT NOT NULL CONSTRAINT "PK_Files" PRIMARY KEY,
    "FileName" TEXT NULL,
    "StorageFileName" TEXT NULL,
    "Timestamp" TEXT NOT NULL,
    "ApplicationUserId" TEXT NULL,
    CONSTRAINT "FK_Files_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Files_ApplicationUserId" ON "Files" ("ApplicationUserId");

**Comment by mjlamb** [comment] 2023-02-22 07:49
@NicolasDorier 

CREATE TABLE "PairingCodes" (
    "Id" TEXT NOT NULL CONSTRAINT "PK_PairingCodes" PRIMARY KEY,
    "DateCreated" TEXT NOT NULL,
    "Expiration" TEXT NOT NULL,
    "Facade" TEXT NULL,
    "Label" TEXT NULL,
    "Name" TEXT NULL,
    "SIN" TEXT NULL,
    "StoreDataId" TEXT NULL,
    "TokenValue" TEXT NULL
);

**Comment by NicolasDorier** [comment] 2023-02-22 07:50
Interesting stuff: in the table, your date has different format than mine.
Mine is `2023-02-15 06:47:06.6841308`. Will try to paste your format and see how it goes.

**Comment by NicolasDorier** [comment] 2023-02-22 07:51
Replicated the issue! Cool looking it now.

**Comment by mjlamb** [comment] 2023-02-22 07:52
@NicolasDorier 
Great news, I can change the dates if needed

**Comment by NicolasDorier** [comment] 2023-02-22 07:55
@mjlamb no, git pull I just pushed a commit

**Comment by NicolasDorier** [comment] 2023-02-22 07:55
Try now. This should work!
Close the issue if this work.

**Comment by mjlamb** [comment] 2023-02-22 07:58
@NicolasDorier  Apps table now, same error

**Comment by mjlamb** [comment] 2023-02-22 08:00
Different date format ? 
![image](https://user-images.githubusercontent.com/2274034/220558420-994c4889-6d96-427d-b829-70738824550f.png)

**Comment by NicolasDorier** [comment] 2023-02-22 08:01
dammit! what error is it this time? you sure it's same error?

**Comment by mjlamb** [comment] 2023-02-22 08:01
> Try now. This should work! Close the issue if this work.

This wroked for files and pairingcodes for sure.

**Comment by mjlamb** [comment] 2023-02-22 08:03
gresMigrationStartupTask: Migrating table: Stores
info: BTCPayServer.Hosting.ToPostgresMigrationStartupTask: Migrating table: ApiKeys
info: BTCPayServer.Hosting.ToPostgresMigrationStartupTask: Migrating table: Apps
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> System.InvalidCastException: Cannot write DateTimeOffset with Offset=12:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTimeOffset value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()

**Comment by NicolasDorier** [comment] 2023-02-22 08:03
OK give me two minutes!

**Comment by NicolasDorier** [comment] 2023-02-22 08:07
OK

**Comment by NicolasDorier** [comment] 2023-02-22 08:07
Hopefully this is fine now!

**Comment by mjlamb** [comment] 2023-02-22 08:10
You will be pleased to see this -> 
info: BTCPayServer.Hosting.ToPostgresMigrationStartupTask: Migration to postgres from SQLite successful

Thank you very much for your  time !

**Comment by NicolasDorier** [comment] 2023-02-22 08:17
finally! awesome.

**Comment by NicolasDorier** [comment] 2023-02-22 08:18
@mjlamb Also set your `BTCPAY_EXPLORERPOSTGRES` to the connection string of the nbxplorer of your manual install.

**Closed by NicolasDorier** 2023-02-22 08:17 UTC
Labels: Database-Migration

**Comment by NicolasDorier** [comment] 2023-02-22 08:19
if your nbxplorer is still on the old backend, you can easily with

The following settings in your NBXPLorer:

```
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
```

This migration should work fine.

**Comment by NicolasDorier** [comment] 2023-02-22 08:20
Then

```
BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer
```

In BTCPay

**Comment by mjlamb** [comment] 2023-02-22 08:21
@NicolasDorier 

 Yes I have migrated the NBX already, I'll add the BTCPAY_EXPLORERPOSTGRES however.... Whats extra do I get?

**Comment by mjlamb** [comment] 2023-02-22 08:26
@NicolasDorier  I think I have the graphs and stuff already as I have the config in the environment var

**Comment by NicolasDorier** [comment] 2023-02-22 08:26
@mjlamb you will see dashboard on the main page. The perf for lot's of things will become much better as well.

**Comment by NicolasDorier** [comment] 2023-02-22 08:27
If you have the graph, like the wallet progression then you already set it I guess.

**Comment by mjlamb** [comment] 2023-02-22 08:28
Yep have, it all very good stuff !

**Comment by mjlamb** [comment] 2023-02-22 08:29
The migration made my "pull payment" page work, I guess I didn't have the correct schema for that before migration

**Comment by NicolasDorier** [comment] 2023-02-22 09:11
@mjlamb I know it was broken with SQLite, it's because some request were filtering on date which sqlite doesn't support. When I saw that I thought it would be easier to make people migrate than making the page work on sqlite via entity framework :D

**Comment by mjlamb** [comment] 2023-02-22 09:13
Got you. Thanks for every your a rockstar! in the space!
