### ISSUE TITLE
[Bug]: Wrong status in IPN

### ISSUE THREAD

**Issue by jaredhared** [btcpayserver/btcpayserver#4220] opened 2022-10-18 16:13 UTC
### What is your BTCPay version?

1.6.12.0

### How did you deploy BTCPay Server?

Docker

### What happened?

Hello, I'm trying to integrate BTCPay Server v1.6.12.0 with external software. After settling test payments, BTCPay behaves weird. 

Sometimes it sends normal IPN with status 'complete', but sometimes, IPN status is 'new'. This is even more weird due to identical payment processing by settling them manually. Could you please look into it?

In attached logs, I'm trying to return a 500 error for 'new' status in order to force BTCPay to send updated status later, but it doesn't changed as you can see.

P.S. Also is it possible to add some link/button to re-send IPN for a particular invoice? That would greatly help in debugging.

### How did you encounter this bug?

1. I generate payment in my script and user is redirected to BTCPay
2. In BTCPay admin panel, I manually mark invoice as settled
3. After that, sometimes BTCPay sends IPN with 'completed' status and sometimes - with 'new'

### Relevant log output

```shell
18.10.2022, 15:54	Creation of invoice starting
18.10.2022, 15:54	BTC_USD: The rating rule is coinbasepro(BTC_USD)
18.10.2022, 15:54	BTC_USD: The evaluated rating rule is (19357.8, 19358.61)
18.10.2022, 15:54	LTC_USD: The evaluated rating rule is (51.3, 51.31)
18.10.2022, 15:54	LTC_USD: The rating rule is coinbasepro(LTC_USD)
18.10.2022, 15:54	BTC (On-Chain): Payjoin is enabled for this invoice.
18.10.2022, 15:54	BTC (On-Chain): Payment method details creation took 36 milliseconds
18.10.2022, 15:54	LTC (On-Chain): Payment method details creation took 42 milliseconds
18.10.2022, 15:54	Saving invoice took 17 milliseconds
18.10.2022, 15:54	Invoice QArn2ywQeHQPZSXYknYo4E new event: invoice_created (1001)
18.10.2022, 15:54	Invoice QArn2ywQeHQPZSXYknYo4E new event: invoice_markedComplete (2008)
18.10.2022, 15:54	Error while sending IPN (2008 invoice_markedComplete): Unexpected return code: 500
18.10.2022, 16:04	Error while sending IPN (2008 invoice_markedComplete): Unexpected return code: 500
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment] 2022-10-19 08:05
Hi,

it seems you use the old Bitpay compatible API which is not actively developed further anymore. You should use the more modern and feature complete [Greenfield API](https://docs.btcpayserver.org/API/Greenfield/v1/#section/Authentication) instead.

No matter if old or Greenfield API, when you return http status 500 (Internal Server Error) BTCPay will assume that the delivery of the IPN failed. This means it will try to re-send the IPN over and over again with different pauses in between. No new callbacks will arrive in the meantime. So you should return http status 200 instead and just ignore it.

With Greenfield API you have a more granular way to only subscribe to certain events. This way you can ignore the [InvoiceCreated](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Webhook_InvoiceCreated) event but subscribe to others. 

Also with Greenfield API you can click to Redeliver already sent events:
![image](https://user-images.githubusercontent.com/1136761/196633001-9ddb2737-34dc-478c-9b2f-3e0e7e3b49cb.png)

**Comment by jaredhared** [comment] 2022-10-19 08:13
Hello,

Since that code wasn't written by me, I just making minor modifications. I have found a workaround for now - instead of relying on callbacks, I'm getting invoice info from BTCPay via API on receiving callback, and if there is 'complete' state, marking it as paid.

**Comment by ndeet** [comment] 2022-10-19 12:09
Yes, if you use the legacy API you should do it that way anyway as the payload is not signed. This means if you rely on the IPN payload anybody can send manipulated payload to your site. You should still return status 200 instead of 500 on receiving an IPN so that BTCPay keeps sending them. If it gets 500 then it will retry for some time but eventually bail at some point.

As this is not a bug on BTCPay and now solved please close this issue. Thank you.

**Closed** 2022-10-20 00:18 UTC
