### ISSUE TITLE
[Bug]: cannot create invoice for new: user,store. BTC

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#4397] opened 2022-12-03 07:15 UTC
### What is your BTCPay version?

BTCPay Server v1.6.12.0

### How did you deploy BTCPay Server?

install.btcpayserver.org

### What happened?

UI log when I create invoice BTC

Warning: You have payment methods configured but none of them match any of the requested payment methods or the rate is not available. See logs below:
12/03/2022 06:53:06:Info Creation of invoice starting
12/03/2022 06:53:06:Info BTC_USD: The rating rule is coingecko(BTC_USD)
12/03/2022 06:53:06:Info BTC_USD: The evaluated rating rule is 16972.835
12/03/2022 06:53:06:Info BTC (On-Chain): Payment method details creation took 20 milliseconds
12/03/2022 06:53:06:Error BTC: Unexpected exception (System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NBXplorer.ExplorerClient.ParseResponse[T](HttpResponseMessage response)
   at NBXplorer.ExplorerClient.SendAsync[T](HttpMethod method, Object body, String relativePath, Object[] parameters, CancellationToken cancellation)
   at NBXplorer.ExplorerClient.GetUnusedAsync(DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve, CancellationToken cancellation)
   at BTCPayServer.Services.Wallets.BTCPayWallet.ReserveAddressAsync(DerivationStrategyBase derivationStrategy) in /source/BTCPayServer/Services/Wallets/BTCPayWallet.cs:line 86
   at BTCPayServer.Payments.Bitcoin.BitcoinLikePaymentHandler.CreatePaymentMethodDetails(InvoiceLogs logs, DerivationSchemeSettings supportedPaymentMethod, PaymentMethod paymentMethod, StoreData store, BTCPayNetwork network, Object preparePaymentObject, IEnumerable`1 invoicePaymentMethods) in /source/BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs:line 223
   at BTCPayServer.Controllers.UIInvoiceController.CreatePaymentMethodAsync(Dictionary`2 fetchingByCurrencyPair, IPaymentMethodHandler handler, ISupportedPaymentMethod supportedPaymentMethod, BTCPayNetworkBase network, InvoiceEntity entity, StoreData store, InvoiceLogs logs, HashSet`1 invoicePaymentMethods) in /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 461)

![1](https://user-images.githubusercontent.com/17591751/205429322-29ce05ae-ba3b-4d18-aab4-cb77eb51fc53.png)
![2](https://user-images.githubusercontent.com/17591751/205429324-edde0909-fa3f-4402-a63e-c1aa38bdf394.png)
![3](https://user-images.githubusercontent.com/17591751/205429325-12cf8a45-1ee1-4ddf-967e-ea1a29bd48e9.png)

### How did you encounter this bug?

1. register new user 
2. create new store
3. create new hot wallet btc
4. create invoice

### Relevant log output

```shell
docker logs  nicolasdorier/nbxplorer:2.3.44


fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMMK79CNEFP6", Request id "0HMMK79CNEFP6:00000002": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: This type of wallet does not support this command
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 924
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 919
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 845
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 846
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Chrome, FF

### Additional information

Add some info:
I have 2 nodes of BTCPay Server v1.6.12.0, (second is for testing) (one coin BTC)
On first server, I have exist user and created store and all works fine, but when I create new user>new store>wallet (with default settings) and after I cannot create invoice (on the same server). 
`Warning: You have payment methods configured but none of them match any of the requested payment methods....`

ps: 
after update second server from BTCPay Server v1.6.12.0 to BTCPay Server v1.7.1.0+e11a775be the issue reproduce.
Also for testing install fresh third server BTCPay Server v1.7.1.0+e11a775be - for new users and stores all works fine invoices creating, no issues. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment] 2022-12-13 01:14
Duplicate of https://github.com/btcpayserver/btcpayserver/issues/4403 @hell0-w can you report there about the fixes I give?

**Closed by NicolasDorier** 2022-12-13 01:14 UTC
Labels: Bug

**Comment by hell0-w** [comment] 2022-12-24 14:33
> Duplicate of #4403 @hell0-w can you report there about the fixes I give?

after an update, all works fine, Thanks!
