### ISSUE TITLE
Exception thrown: function array_position(text[], unknown) does not exist

### ISSUE THREAD

**Issue by martinbehrens** [btcpayserver/btcpayserver#1318] opened 2020-02-04 12:49 UTC
**Describe the problem/bug**
We are replacing our old, self hosted BTCPay sqlite deployment with a new BTCPay with PSQL DB (v9.2.24). The deployment itself was working fine but the checkout with a third party doesn't work. Once the invoice has been paid (off-chain, lightning transaction), BTCpayServer returns for every transaction:

`Unexpected return code: 500`

The events section of https://fqdn/invoices/invoice_id is full of that:

Date | Message
------------ | -------------
2/4/2020 11:06:36 AM | Creation of invoice starting
2/4/2020 11:06:37 AM | BTC_EUR: The rating rule is kraken(BTC_EUR)
2/4/2020 11:06:37 AM | BTC_EUR: The evaluated rating rule is (8290, 8291)
2/4/2020 11:06:39 AM | BTC (Off-Chain): Payment method details creation took 1 seconds
2/4/2020 11:06:40 AM | BTC (On-Chain): Payment method details creation took 2 seconds
2/4/2020 11:06:40 AM | BTC (On-Chain): The amount of the invoice is too low to be paid on chain
2/4/2020 11:06:40 AM | Saving invoice took 298 milliseconds
2/4/2020 11:06:40 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ new event: invoice_created (1001)
2/4/2020 11:06:42 AM | Error while sending IPN (1001 invoice_created): Unexpected return code: 500
2/4/2020 11:06:54 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ new event: invoice_receivedPayment (1002)
2/4/2020 11:06:54 AM | Invoice status is complete
2/4/2020 11:06:54 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ new event: invoice_paidInFull (1003)
2/4/2020 11:06:54 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ new event: invoice_confirmed (1005)
2/4/2020 11:06:54 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ new event: invoice_completed (1006)
2/4/2020 11:06:54 AM | Invoice 5hJeGFCsxtJAHeVXN2QTtQ is not monitored anymore.
2/4/2020 11:06:55 AM | Error while sending IPN (1002 invoice_receivedPayment): Unexpected return code: 500
2/4/2020 11:06:57 AM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500
2/4/2020 11:06:57 AM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500
2/4/2020 11:06:58 AM | Error while sending IPN (1005 invoice_confirmed): Unexpected return code: 500
2/4/2020 11:07:00 AM | Error while sending IPN (1005 invoice_confirmed): Unexpected return code: 500
2/4/2020 11:07:00 AM | Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
2/4/2020 11:07:02 AM | Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
2/4/2020 11:16:43 AM | Error while sending IPN (1001 invoice_created): Unexpected return code: 500
2/4/2020 11:16:56 AM | Error while sending IPN (1002 invoice_receivedPayment): Unexpected return code: 500
2/4/2020 11:16:58 AM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500
2/4/2020 11:16:58 AM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500
2/4/2020 11:17:00 AM | Error while sending IPN (1005 invoice_confirmed): Unexpected return code: 500
2/4/2020 11:17:01 AM | Error while sending IPN (1005 invoice_confirmed): Unexpected return code: 500
2/4/2020 11:17:02 AM | Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
2/4/2020 11:17:03 AM | Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
2/4/2020 11:26:44 AM | Error while sending IPN (1001 invoice_created): Unexpected return code: 500
2/4/2020 11:26:57 AM | Error while sending IPN (1002 invoice_receivedPayment): Unexpected return code: 500
2/4/2020 11:27:02 AM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500

I scanned the BTCPayServer logs and stumbled upon Exceptions mentioned in the title. Please find them below in full.

**Your environment**
* CentOS Linux release 7.7.1908 (Core)
* .NET Core SDK (3.1.101)
* BTCPay Server: v1.0.3.156 (master branch)
* PostgreSQL v9.2.24
* Deployment method: manual

**Logs (if applicable)**

BTCPayServer startup is all good and looks fine, but when it comes to the respective transactions the journal (journalctl -xe --unit btcpay) is full of: 

`Feb 04 11:27:04 fqdn run.sh[26076]: at lambda_method(Closure , Object )
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:04 fqdn run.sh[26076]: at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 78
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 04 11:27:04 fqdn run.sh[26076]: at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 32
Feb 04 11:27:04 fqdn run.sh[26076]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 04 11:27:04 fqdn run.sh[26076]: Exception data:
Feb 04 11:27:04 fqdn run.sh[26076]: Severity: ERROR
Feb 04 11:27:04 fqdn run.sh[26076]: SqlState: 42883
Feb 04 11:27:04 fqdn run.sh[26076]: MessageText: function array_position(text[], unknown) does not exist
Feb 04 11:27:04 fqdn run.sh[26076]: Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Feb 04 11:27:04 fqdn run.sh[26076]: Position: 488
Feb 04 11:27:04 fqdn run.sh[26076]: File: parse_func.c
Feb 04 11:27:04 fqdn run.sh[26076]: Line: 304
Feb 04 11:27:04 fqdn run.sh[26076]: Routine: ParseFuncOrColumn
Feb 04 11:27:05 fqdn run.sh[26076]: info: Events:         Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
Feb 04 11:27:05 fqdn run.sh[26076]: crit: PayServer:      Unhandled exception in BTCPayMiddleware
Feb 04 11:27:05 fqdn run.sh[26076]: Npgsql.PostgresException (0x80004005): 42883: function array_position(text[], unknown) does not exist
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Feb 04 11:27:05 fqdn run.sh[26076]: --- End of stack trace from previous location where exception was thrown ---
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Feb 04 11:27:05 fqdn run.sh[26076]: --- End of stack trace from previous location where exception was thrown ---
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Services.Invoices.InvoiceRepository.GetInvoices(InvoiceQuery queryObject) in /home/user/btcpayserver/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 612
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Controllers.InvoiceControllerAPI.GetInvoice(String id) in /home/user/btcpayserver/BTCPayServer/Controllers/InvoiceController.API.cs:line 50
Feb 04 11:27:05 fqdn run.sh[26076]: at lambda_method(Closure , Object )
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 78
Feb 04 11:27:05 fqdn run.sh[26076]: Exception data:
Feb 04 11:27:05 fqdn run.sh[26076]: Severity: ERROR
Feb 04 11:27:05 fqdn run.sh[26076]: SqlState: 42883
Feb 04 11:27:05 fqdn run.sh[26076]: MessageText: function array_position(text[], unknown) does not exist
Feb 04 11:27:05 fqdn run.sh[26076]: Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Feb 04 11:27:05 fqdn run.sh[26076]: Position: 488
Feb 04 11:27:05 fqdn run.sh[26076]: File: parse_func.c
Feb 04 11:27:05 fqdn run.sh[26076]: Line: 304
Feb 04 11:27:05 fqdn run.sh[26076]: Routine: ParseFuncOrColumn
Feb 04 11:27:05 fqdn run.sh[26076]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLT8P4U1V8LM", Request id "0HLT8P4U1V8LM:00000001": An unhandled exception was thrown by the application.
Feb 04 11:27:05 fqdn run.sh[26076]: Npgsql.PostgresException (0x80004005): 42883: function array_position(text[], unknown) does not exist
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Feb 04 11:27:05 fqdn run.sh[26076]: --- End of stack trace from previous location where exception was thrown ---
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Feb 04 11:27:05 fqdn run.sh[26076]: --- End of stack trace from previous location where exception was thrown ---
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Services.Invoices.InvoiceRepository.GetInvoices(InvoiceQuery queryObject) in /home/user/btcpayserver/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 612
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Controllers.InvoiceControllerAPI.GetInvoice(String id) in /home/user/btcpayserver/BTCPayServer/Controllers/InvoiceController.API.cs:line 50
Feb 04 11:27:05 fqdn run.sh[26076]: at lambda_method(Closure , Object )
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 78
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 04 11:27:05 fqdn run.sh[26076]: at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 32
Feb 04 11:27:05 fqdn run.sh[26076]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 04 11:27:05 fqdn run.sh[26076]: Exception data:
Feb 04 11:27:05 fqdn run.sh[26076]: Severity: ERROR
Feb 04 11:27:05 fqdn run.sh[26076]: SqlState: 42883
Feb 04 11:27:05 fqdn run.sh[26076]: MessageText: function array_position(text[], unknown) does not exist
Feb 04 11:27:05 fqdn run.sh[26076]: Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Feb 04 11:27:05 fqdn run.sh[26076]: Position: 488
Feb 04 11:27:05 fqdn run.sh[26076]: File: parse_func.c
Feb 04 11:27:05 fqdn run.sh[26076]: Line: 304
Feb 04 11:27:05 fqdn run.sh[26076]: Routine: ParseFuncOrColumn
Feb 04 11:27:05 fqdn run.sh[26076]: info: Events:         Error while sending IPN (1006 invoice_completed): Unexpected return code: 500
Feb 04 11:31:29 fqdn run.sh[26076]: info: Events:         BTC: New block`

**To Reproduce**

Difficult to replicate, we have a specific third party integration (that definitely supports btcpay).

**Expected behavior**
No exception being thrown.

**Actual behavior**
Exception being thrown when an invoice got paid.

**Comment by martinbehrens** [comment] 2020-02-12 15:42
Commented out the PSQL connection string (aka switched back to Sqlite) and everything worked like charm. So this issue might need some attention, testing and/or clarification on the specific PSQL version to be deployed.

**Comment by NicolasDorier** [comment] 2020-02-24 12:03
Sorry for having take time to get back at you.
That is indeed strange...

Can you tell me which platform you use? OS/Arch

**Comment by martinbehrens** [comment] 2020-02-24 12:10
Sure: CentOS Linux release 7.7.1908 (Core)/x86_64

**Comment by NicolasDorier** [comment] 2020-02-24 12:39
our version of postgres is 9.6.5

maybe that's the problem?

**Comment by martinbehrens** [comment] 2020-02-25 00:43
Idk, possible. What's the recommended/compatible PSQL version(s)?

**Comment by NicolasDorier** [comment] 2020-02-25 08:28
try the 9.6.5

**Comment by pavlenex** [comment] 2020-03-22 07:59
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2020-03-22 15:49 UTC
Labels: Closing
