### ISSUE TITLE
Invoices view: `Paid invoices` filter gives empty list

### ISSUE THREAD

**Issue by silent-link** [btcpayserver/btcpayserver#3418] opened 2022-02-04 21:37 UTC
Invoices view: `Paid invoices` filter gives empty list
All other filters work properly.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'Invoices'
2. Click on 'filter `Paid invoices`'
3. Observe empty list of invoices

**Expected behavior**

see paid invoices list.

Deployment: Docker, amd64
Browser: Chromium on Ubuntu 20.04

**Comment by NicolasDorier** [comment] 2022-02-10 03:59
duplicate of https://github.com/btcpayserver/btcpayserver/issues/3434 will release a new version this week, meanwhile see the workaround there.

**Closed by NicolasDorier** 2022-02-10 03:59 UTC
