### ISSUE TITLE
[Bug]: Woocommerce doesn't save to create webhooks on WP 6.0+ 

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#3899] opened 2022-06-25 22:39 UTC
### What is your BTCPay version?

1.5.4.0 (altcoins) 

### How did you deploy BTCPay Server?

BTCPay Server hosted.

### What happened?

Yoo, 

We got pushed to WP 6 by Woocommerce. 
Now it seems BTCPay is sending data to the WP, but when in WP you hit save, it doesn't do the call back properly (properly doesnt save properly in admin.php) and breaks after a while into a 504 time out. It's trying to resolve :  (https://WEBSITE.X/wp-admin/admin.php?page=wc-settings&tab=btcpay_settings) which should create the Webhook, but it cant. 

### How did you encounter this bug?

Have WP 6.0 
and the latest woocommerce (6.6) 

Plugin Version 1.0.2 and PHP Version 7.4.

### Relevant log output

```shell
{"result":"failure","messages":"<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>\n\t\t\tWe were unable to process your order, please try again.\t\t<\/li>\n\t<\/ul>\n","refresh":true,"reload":false} 

DEBUG Error fetching data for this API key from server. Please check if the key is valid. Error: Failed to connect to 
[website.me](http://website.me/)
 port 443: Connection timed out.
```

### What browser do you use?

Safari latest version

### Additional information

![afbeelding](https://user-images.githubusercontent.com/102448109/175792380-e18cb1f0-92d9-4b03-948c-4621c6f302f0.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Eskyee** [comment] 2022-06-26 05:55
@ndeet 🍻 cheers bro @Bangalisch

**Comment by ndeet** [comment] 2022-06-26 13:57
Hey @Bangalisch thanks a lot for the bug report!

Are you sure you input the correct BTCPay Server URL and it works. The error you posted:
> Error: Failed to connect to [website.me](http://website.me/) port 443: Connection timed out.

means that the Host is not reachable. So if you go to http://website.me/ you should see the BTCPay Server login page. Also what is strange but maybe a typo that you have `http` instead of `https` in front of the url. Should be `https://website.me`

Can you please double check that?

**Comment by Eskyee** [comment] 2022-06-26 15:27
Hey gang.. i managed to get BTCPAY V2 working with Wordpress 6 with no problems know, this was because I created a new server with just Wordpress 6 and Woocommerce latest version with BTCPAY v2 plug-in.. the site health was ok ✅ and it could save ok 👍🏽 No conflicts..

So bas we need to test the internal Woocommerce fragment... and see if we can reproduce this error... ie site not healthy...

Old logs
From BTCPAY Woocommerce fragment... 
Your site has critical issues that should be addressed as soon as possible to improve its performance and security.

2 critical issues


The REST API encountered an error
Performance
The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

The REST API request failed due to an error.
Error: cURL error 28: Connection timed out after 10001 milliseconds (http_request_failed)

Your site could not complete a loopback request
Performance
Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: cURL error 28: Connection timed out after 10000 milliseconds (http_request_failed)


So bas this was causing it not to save... problem.. no webhooks etc etc.. api key 🔑 was ok..


But as I said.. with a fresh Wordpress into on a external server... I had no problems...

With lightning ⚡️ or bitcoin payments....

Now I'm happy 😃 gang 💯


I leave this here ... 

Until the internally BTCPAY Woocommerce fragment is tested...

And bug reproduce...
Peace ✌️

**Comment by Eskyee** [comment] 2022-06-26 15:45
My Wordpress 6 ✨ This plugin version is 1.0.2 and your PHP version is 8.0. As default

**Comment by ndeet** [comment] 2022-06-26 15:59
> The REST API request failed due to an error.
Error: cURL error 28: Connection timed out after 10001 milliseconds (http_request_failed)

> The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: cURL error 28: Connection timed out after 10000 milliseconds (http_request_failed)

> So bas this was causing it not to save... problem.. no webhooks etc etc.. api key 🔑 was ok..

@Eskyee this was when running the health check on the fragment right? I wonder if this affects the settings form though? It should be on a different path and not interfere with the settings form at all (but I could be wrong here). Can you clarify if there is any problem causing the plugin settings to fail to save or is this some other error unrelated to the plugin itself but causes generally the WC api callbacks to fail?

Thanks a lot for debugging 💚

**Comment by Eskyee** [comment] 2022-06-26 17:57
@ndeet yes if yellow... the site health has a conflict...

Green is all go.. ✅😂


Ps plug-in is working sweet...

Thanks 🙏 bro 🙌❤️✨💯

**Comment by Eskyee** [comment] 2022-06-26 18:03
It Might be that Woocommerce in BTCPAY fragment needs replacement & updating to be safe... as it's older version now.. & problem was site health yellow after a default install fragment... 



and new the php 8 & Wordpress 6 is validated.. Working fine now.. tested all day.. 
🍻✨

**Comment by pavlenex** [comment] 2022-07-12 08:46
@ndeet Were you able to repro this? I assume this issue should be transferred to Woo repo if so?

**Comment by ndeet** [comment] 2022-07-12 20:48
> So can we close this issue as a result?

Now that I linked the PR it should get closed as soon as the PR is merged, but if you do not want to wait you can close it now too.

**Closed** 2022-07-20 01:25 UTC
Labels: Bug
