### ISSUE TITLE
[Bug]: Error LNURL payment link on creating invoices over API

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5898] opened 2024-04-03 20:19 UTC
### What is your BTCPay version?

v1.12.5

### How did you deploy BTCPay Server?

Umbrel

### What happened?

A user reported that he gets this error when invoices are created through API via WooCommerce:

```
"Error generating LNURL payment link: serviceUrl must be an onion service OR https based OR on the local network (Parameter 'serviceUrl')
```

Seems this is related to Umbrel setup and not a general problem as I was not able to reproduce it. 

This can be fixed by disabling LNURL in the LN wallet settings.

### How did you encounter this bug?

Running on BTCPay on Umbrel and creating an invoice over the API (in this case WooCommerce plugin)

### Relevant log output

```shell
Error generating LNURL payment link: serviceUrl must be an onion service OR https based OR on the local network (Parameter 'serviceUrl')
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment] 2024-04-08 10:21
I don't quite understand, is this a problem with Umbrel only, do we know how to resolve this?

**Comment by ndeet** [comment] 2024-04-10 08:57
To me it looks like the error happens because on Umbrel the setup is missing LNURL support or some endpoint not reachable - nothing we can do there. But we may can do some check if LNURL is available and avoid the error and just silently ignore it to solve he issue.

**Comment by Asone** [comment] 2024-07-12 06:02
Hi, 

i found this issue after digging on the web whilst experiencing the same problem. 

> To me it looks like the error happens because on Umbrel the setup is missing LNURL support or some endpoint not reachable

The bug seems a bit odd. I've been looking a bit deeper. This is what i could get : 

- When using the Woocommerce plugin for payment the website calls the following URL structure : `<domain>/invoice?id=<invoiceId>&view=modal` which returns an HTTP/500 response. 
- Through the btcpayserver backoffice, the invoice exists though and seems to have been generated. When trying to access the invoice through the `checkout` CTA, the page it loads also fails and the server responds with an HTTP/500 response. 

In both cases the server returns the following stacktrace in the STDERR : 

```
Error generating LNURL payment link: serviceUrl must be an onion service OR https based OR on the local network (Parameter 'serviceUrl')
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN50TRJSDL3F", Request id "0HN50TRJSDL3F:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
   at BTCPayServer.Payments.LNURLPayPaymentType.PopulateCryptoInfo(InvoiceEntity invoice, PaymentMethod details, InvoiceCryptoInfo invoiceCryptoInfo, String serverUrl) in /source/BTCPayServer/Payments/LNURLPay/PaymentTypes.LNURL.cs:line 74
   at BTCPayServer.Services.Invoices.InvoiceEntity.EntityToDTO() in /source/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 630
   at BTCPayServer.Controllers.UIInvoiceController.GetInvoiceModel(String invoiceId, PaymentMethodId paymentMethodId, String lang) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 805
   at BTCPayServer.Controllers.UIInvoiceController.Checkout(String invoiceId, String id, String paymentMethodId, String view, String lang) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 671
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: PayServer:      BTC (Lightning): No more invoice to listen on https://10.21.21.9:8080/, releasing the connection
```

I've been trying to create an invoice manually to compare the events of the invoice for both cases in the backoffice. In both cases we have the same events that are registered as successful and both using LNURL-Pay service for invoice generation. 

My guess would be that it might not be related to LNURL itself, but rather on the BTCPayServer <-> GreenField API communication where something is defaulty. But i'm no expert of BTCPayServer nor C#. 

For context of the use case generation on my side : 
- BTCPayServer version : v1.13.1+ca55e1f3
- Hosted on Umbrel 1.2.1
- Woocommerce plugin version : 2.6.2 ( probably not relevant )
- Additional information : the btcpayserver is reached through a [reverse proxy to tor](https://docs.btcpayserver.org/Deployment/ReverseProxyToTor/) ( probably not relevant )

**Comment by Asone** [comment] 2024-07-12 06:29
Update : The problem is the same one as defined #4959 

Fixed by making the same actions. However in order to display the QR Code, in case of using a reverse proxy over tor i had to remove the following line of my nginx config : 

`add_header Content-Security-Policy "frame-ancestors 'self';";`

**Comment by NicolasDorier** [comment] 2024-11-21 00:12
@Asone about why LNURL doesn't work on Umbrel, it is because you are accessing btcpay on http localhost.

About why it crashes, I confirm that this has been fixed in 2.x, so I close this issue.

**Closed by NicolasDorier** 2024-11-21 00:12 UTC
Labels: Bug, Lightning, API
