### ISSUE TITLE
Bitcoin ATM / (BTCPay day)

### ISSUE THREAD

**Issue by 4rkad** [btcpayserver/btcpayserver#1038] opened 2019-09-16 14:31 UTC
Allowing credit card payment and receive it directly into Bitcoin.
Idea from BTCPay day

**Comment by pavlenex** [comment] 2019-09-23 18:47
Hey hey! 
So glad we started chatting about this during the BTCPay Day.
The basic idea is to have some sort of integration that will allow merchants to accept fiat but convert and stack sats on their end.
Currently it's possible with Changelly, but the fees are high and the UX is quite confusing.
Also seems a bit related or a duplicate of #923

**Comment by pavlenex** [comment] 2019-09-29 11:54
@4rkad I'll close this issue since there's an ongoing discussion going on in #923 so let's continue to brainstorm on this one there to avoid duplication.

**Closed by pavlenex** 2019-09-29 11:54 UTC
Labels: Brainstorming, Feature Request

**Comment by 4rkad** [comment] 2019-09-30 10:43
Thanks buddy
