### ISSUE TITLE
Send a `verification email` when a user changes their email to avoid lock-out.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#3645] opened 2022-04-16 08:19 UTC
a already User is Locked out of their BTCPay Account. 
They Have Changed their email address, and said they never received email confirmation, 
systems locked me out with: "Invalid login attempt." and "You must have a confirmed email to log in.". 

A verify email was sent from our server, which has now timed out.

So now the Admin has to verify them again, but in the users section, web view  their is only edit or remove.
their is nothing to say, send verify email again, to user, or no toggle button to verify them again.

So it looks like its via the command terminal is the only way to verify a user again, as their is only,   is admin - function.
Would be nice to have this in the front browser,  with a verify a user toggle or send verify email again.
also not had this problem in years, so I have forgotten the commands to do this.

Make the email address associated for user verified. terminal commands ??
I have search the BTCPay docs, but also couldn't find no information here. About verify user. for admins.

Any ideas how to do this manually, via terminal.

cheers

**Comment by pavlenex** [comment] 2022-04-16 08:26
From what I understood, previously registered user, changed their email address, but never got email confirmation when changing it, hence they cannot sign in. This would mean that anyone changing an email on their instance would be locked out. Could anyone try to replicate the issue? @bolatovumar ?

**Comment by ishristov** [comment] 2022-04-21 09:40
@pavlenex, I tried to replicate:
- I changed my email and clicked "save" (didn't click the "send verification email"). I didn't receive any email, but email was changed and I could login with the new email;
- I repeated the same and changed to my old email, it worked again.

If I login with the server admin, I can see that even though the email is changed, the user is still marked as "verified". So the email change doesn't make them "unverified".

**Comment by pavlenex** [comment] 2022-04-21 09:49
Thanks for veryfing @ishristov then this is something we should address.

**Comment by Eskyee** [comment] 2022-04-22 12:08
@pavlenex  any idea of the commands to do this via ssh " to manually change their email and resend password "

cheers!

**Comment by pavlenex** [comment] 2022-04-23 14:26
I am not aware of command to change users email and it seems it's not possible to change their email or re-send the verification email. Perhaps this is a functionality we should add. Maybe @bolatovumar has an idea on the approach and perhaps @Kukks know a command that can be executed to change user's email in the database?

**Comment by bolatovumar** [comment] 2022-05-07 05:05
@pavlenex is the thought here to allow server admins to update existing user's email address to something else or allow them to resend the verification email? (or both?) I can look into this (although I can't promise anything as I don't really know anything about the email verification functionality).

**Comment by pavlenex** [comment] 2022-05-07 09:46
@bolatovumar I'd say both would be fine, how do you feel about it?

**Comment by bolatovumar** [comment] 2022-05-08 04:21
@pavlenex yeah, I think having both is useful unless there is a good reason why this shouldn't be done.

**Comment by pavlenex** [comment] 2022-05-28 18:07
@bolatovumar Should we close this one, or would you like to add another PR to address something more?

**Comment by bolatovumar** [comment] 2022-06-01 04:21
@pavlenex I think we can close this ticket. If the issue is not fixed for @Eskyee then we can reopen it.

**Closed** 2022-06-06 08:11 UTC
Labels: Bug, good first issue, Stores
