### ISSUE TITLE
[Bug]: The invoice hyperlink is enabled during "Pay Button" plugin configuration

### ISSUE THREAD

**Issue by raduButucelea23** [btcpayserver/btcpayserver#4325] opened 2022-11-21 17:03 UTC
### What is your BTCPay version?

 BTCPay Server v1.6.12.0

### How did you deploy BTCPay Server?

docker deploy

### What happened?

504 Gateway Time-out

### How did you encounter this bug?

Under "Plugins", select "Pay Button" to access the configuration window. 
Click "this link" button on the right-hand side of the window, just below the "Preview" of the pay button. 

Expected behaviour: The hyperlink should be disabled during the configuration of the "Pay Button". 

![image](https://user-images.githubusercontent.com/44141337/203115376-7c1aac82-3b38-4cc4-a69e-cc88b45e2d5c.png)

### What browser do you use?

Brave 1.45.118

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment] 2022-11-21 19:48
For me it works and I think the behaviour is correct. Can you check whether or not this was just a temporary timeout failure?

**Comment by raduButucelea23** [comment] 2022-11-21 20:29
@dennisreimann which version did you try on? 

In my case, the error is consistently reproducible on BTCPay Server v1.6.12.0, but I have tested it on my local environment with the current tip of master and, indeed, the checkout screen appears **although** the amount displayed seems to be wrong.

Steps: 
1. Select custom amount / slider 
2. Select an amount different than default (e.g 7 USD)
3. Tap on the "this link" hyperlink
4. The invoice is generated for the default "1 USD" amount

![image](https://user-images.githubusercontent.com/44141337/203152373-e90e56ca-359b-423c-ae7b-1d2e9940a409.png)

**Comment by dennisreimann** [comment] 2022-11-28 15:28
Are there any Content Security Ploicy warnings in the browser console?

**Comment by dennisreimann** [comment] 2022-11-28 17:08
The link is a static version and adjusts to the minimum selected value. I just verified it works as intended, so I think we can close this one.

**Closed by dennisreimann** 2022-11-28 17:08 UTC
