### ISSUE TITLE
Shopify multi currency issue

### ISSUE THREAD

**Issue by rolandschellhorn** [btcpayserver/btcpayserver#4264] opened 2022-11-02 14:32 UTC
### What is your BTCPay version?

BTCPay 1.6.12.0

### How did you deploy BTCPay Server?

Raspberry Pi 4

### What happened?

I´m having troubles - showing the BTC pay option if a customer switches to another currency then our main shop currency.
E.g. 
Shop main currency is EUR > Pay with Bitcoin shows up in payment options. 
Currency is set to CHF, USD, GBP..  >  Pay with Bitcoin option is not available.

### How did you encounter this bug?

complains about missing checkout option

### What browser do you use?

Testet on Chrome 106.0.5249.119 and Safari 16

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment] 2022-11-03 10:44
@Kukks Can you look into this one?

**Comment by rolandschellhorn** [comment] 2022-11-05 12:16
I do not see any suspicious logs except that one:

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

And hinds what this could be - is this a problem on my side only - so this should work and works on other stores?

**Comment by pavlenex** [comment] 2022-11-14 09:30
@rolandschellhorn Is this still the issue for you or you resolved it?

**Comment by pavlenex** [comment] 2022-12-19 11:08
@ndeet would you be able to look into this one?

**Comment by ndeet** [comment] 2022-12-21 09:52
@pavlenex Shopify has been done in the BTCPay codebase. I'm yet to start with C# and have not looked into the codebase yet. I could give it a shot but I doubt I will see the problem as quickly as somebody that is familar with both 😅

**Comment by raduButucelea23** [comment] 2022-12-21 15:59
> > @rolandschellhorn Is this still the issue for you or you resolved it?
> 
> No unfortunately it's still an issue. Thats why I asked - if there are other shops out there where this works - so that I know it musst be somehow a problem on my side / configuration or whatsoever.

@rolandschellhorn  Hi Roland! Could you please confirm the behavior for the 2 use cases below:
Assuming you're in the error state, what happens if the "Shop" currency is changed back to match the "default" BTCPay currency? Is the issue still reproducible? 
Assuming you are in the error state, what happens if you change the BTCPay "default" currency to match the "Shop" currency selected? Is the problem still reproducible?

Also could you please attach the full log snippet?

@dennisreimann @Kukks

**Comment by bolatovumar** [comment] 2022-12-24 04:10
@rolandschellhorn what do you mean by

> if a customer switches to another currency then our main shop currency.

Is there an option in Shopify to allow a customer to pic a currency when they are checking out for a product? I created a Shopify store and connected it to my BTCPay instance to try to repro this bug but can't since I can't find the option to allow multiple currencies. Could you share more details here pls so I can try to repro the issue.

**Comment by rolandschellhorn** [comment] 2022-12-24 08:08
> @rolandschellhorn what do you mean by
> 
> > if a customer switches to another currency then our main shop currency.
> 
> Is there an option in Shopify to allow a customer to pic a currency when they are checking out for a product? I created a Shopify store and connected it to my BTCPay instance to try to repro this bug but can't since I can't find the option to allow multiple currencies. Could you share more details here pls so I can try to repro the issue.

Hi, you need to add Shopify Geolocation App (https://apps.shopify.com/geolocation).
Then in Settings > Markets > Add a country with a different currency.
You should be able to select it add the bottom (if enabled via geolocation app) + if you set the country on checkout it should switch the currency.

**Comment by rolandschellhorn** [comment] 2022-12-24 08:22
> > > @rolandschellhorn Is this still the issue for you or you resolved it?
> > 
> > 
> > No unfortunately it's still an issue. Thats why I asked - if there are other shops out there where this works - so that I know it musst be somehow a problem on my side / configuration or whatsoever.
> 
> @rolandschellhorn Hi Roland! Could you please confirm the behavior for the 2 use cases below:
> 
> 1. Assuming you're in the error state, what happens if the "Shop" currency is changed back to match the "default" BTCPay currency? Is the issue still reproducible?
> 2. Assuming you are in the error state, what happens if you change the BTCPay "default" currency to match the "Shop" currency selected? Is the problem still reproducible?
> 
> Also could you please attach the full log snippet?
> 
> @dennisreimann @Kukks

Hi, I checked a few things now:

Shopify Settings:
Base Shop Currency is in EUR and is not changeable without shopify support.
BTCPayServer Default Currency is also EUR.

Shopify Webshop: 
Checkout > Swiss address > no Bitcoin payment option > switch back to address with EUR > Bitcoin payment option is available
Changed BTCPayServer Default Currency to CHF > Test Checkout in CHF > no BTC payment option.
Changed BTCPayServer Default Currency to CHF > Test Checkout in EUR > BTC payment option is available.

**Comment by bolatovumar** [comment] 2022-12-25 06:37
@rolandschellhorn I added the Geolocation App to my test store and then tried checking out with Swiss Franc and with Czech Koruna and it worked as expected (my default currency is Canadian Dollar). I suspect something might be off with your setup.

Are you able to share a link to your store so we can try to repro the bug there? Does the bug happen on the page in the screenshot below and the "Bitcoin with BTCPay Server" option is not available at all or does it happen after this page where the BTCPay pay button is on? 

![Capture](https://user-images.githubusercontent.com/1934678/209458944-22524769-336c-4dfd-827d-44941dad613d.PNG)

**Comment by rolandschellhorn** [comment] 2022-12-25 06:43
> @rolandschellhorn I added the Geolocation App to my test store and then tried checking out with Swiss Franc and with Czech Koruna and it worked as expected (my default currency is Canadian Dollar). I suspect something might be off with your setup.
> 
> Are you able to share a link to your store so we can try to repro the bug there? Does the bug happen on the page in the screenshot below and the "Bitcoin with BTCPay Server" option is not available at all or does it happen after this page where the BTCPay pay button is on?
> 
> ![Capture](https://user-images.githubusercontent.com/1934678/209458944-22524769-336c-4dfd-827d-44941dad613d.PNG)

Hi, I will check that soon. Just one question to your setup - is your Base Shopify Currency EUR or USD?

**Comment by bolatovumar** [comment] 2022-12-25 18:57
@rolandschellhorn base currency is CAD.

**Comment by bolatovumar** [comment] 2023-01-05 04:50
@rolandschellhorn followed up with Shopify and as it turns out manual payment methods are only allowed for the base currency of the store. Interestingly enough, when I initially tried it on my test store I was able to check out with BTCPay using non-base currencies, however, a couple of days later it stopped working without me actually making any changes. I guess Shopify doesn't disable this functionality right away.

@pavlenex we can probably close this issue as there is nothing we can do here it seems.

**Closed** 2023-01-05 08:45 UTC

**Comment by kayth21** [comment] 2023-02-12 17:44
I had a chat with Shopify about this and they said, that the custom app is not able to deal with the Geolocation app. So if you disable or delete the Geolocation app, your customers will probably only see prices in your main currency, but at least the "Bitcoin with BTCPay" option shows up again.

**Comment by ndeet** [comment] 2023-02-14 08:42
@kayth21 thanks for reaching out to them. Did they mention that it can be fixed on our end or is it just impossible with their geolocation app?

**Comment by kayth21** [comment] 2023-02-15 12:35
@ndeet unfortunately they could not tell me this, see the following transcript snippet:

> 13:58 kayth21: Do you have any hints I can forward to the developers of the custom app how to deal with geolocation?
> 
> 14:00 Nicka (Support Advisor): Apologies kayth21, since app coding and custom app compatibility are out of my scope of support, I am unable to provide that kind of details,, though you can let them know that they are not compatible with geolocation app, which is a shopify app. So that they can make some adjustment with their coding.

Here is the complete transcript (without pictures):

> 13:34 kayth21: Dear Shopify
> 
> In my shop I use a manual payment method (Bitcoin with BTCPay Server). This works fine for US customers, but for customers in Switzerland or Germany the option doesn't show up at the checkout screen. Can you support me with this?
> 
> 13:34 System: An agent has joined the chat
> 
> 13:34 Nicka (Support Advisor): Hi! This is Nicka, your Shopify Support Advisor and I'll be happy to help you today.
> 
> 13:34 kayth21: Hi Nicka
> 
> 13:34 Nicka (Support Advisor): Nice to meet you kayth21! Let me just review the message above real quick :)
> 
> 13:35 kayth21: sure :)
> 
> 13:35 Nicka (Support Advisor): Thank you for waiting! Just to confirm, your manual payment BTC pay are unable to show up if the customer are outside US? No worries, let's check this out!
> 
> 13:36 kayth21: yes. So I didn't check all countries, but it doesn't show up on Switzerland and Germany. But it does, as soon as I reload the page and choose "change country" and select USA.
> 
> 13:37 Nicka (Support Advisor): Got it! That's a bit odd. Let me go ahead and take a look at this for you.
> 
> 13:37 kayth21: great, thank you.
> 
> 13:38 Nicka (Support Advisor): Sure! While I am taking a look at this one for you, may I know when did you notice this started to happen?
> 
> 13:39 kayth21: hmm... some days ago. But it's possible that it doesn't work anymore since many weeks.
> 
> 13:41 Nicka (Support Advisor): Gotcha! Thanks for the information you provided, upon checking here, i made a test order using a canadian address though the location is Philippines, and the this is what I got:  if I may ask, what apps are we using by the way?
> 
> 13:44 Nicka (Support Advisor): When I made a test order on the theme itself, the BTC gateway is showing.  which i can confirm, that it's not a theme issue, let me dig into this.
> 
> 13:45 kayth21: Exactly, thank you. I use a custom app for this integration.
> 
> 13:46 Nicka (Support Advisor): I see, I have a feeling that this your custom apps seems to be not compatible with Geolocation. Let me check further.
> 
> 13:49 Nicka (Support Advisor): Alright! I am right kayth21!  so I disabled the geolocation codes via backend here so it won't make too much effect in the store. And the BTC server is showing. So the custom apps and geolocation seems to be not compatible.
> 
> 13:51 kayth21: ok, I see. So when I open the shop now, it doesn't ask me if I am fine with Switzerland or if I want to choose another country. Prices are not in CHF or EUR but always in USD now. Correct? Is that something I can enable/disable by myself somewhere in the backend?
> 
> 13:52 Nicka (Support Advisor): Yes! I enabled back the geolocation in my backend admin here, let me walk you through how you can disable it on your admin. And yes, the prices will always be in USD now if we disable it.
> 
> 13:53 kayth21: ok, yes please
> 
> 13:55 Nicka (Support Advisor): Sure! So you can go either uninstall the geolocation app, or disable this option instead. 
> 
> 13:56 kayth21: Ah I see, it's that easy. Great, thank you. Is the geolocation a new feature that somewhen came without me noticing it?
> 
> 13:58 Nicka (Support Advisor): It's an app where in it helps you with selling into another countries, more like helping your market settings. It's feature is changing the currencies based on your customer's location. Though since the custom app are unable to match or compatible with this app, it is best if we disable it instead or uninstall.
>
> 13:58 kayth21: Do you have any hints I can forward to the developers of the custom app how to deal with geolocation?
> 
> 14:00 Nicka (Support Advisor): Apologies kayth21, since app coding and custom app compatibility are out of my scope of support, I am unable to provide that kind of details,, though you can let them know that they are not compatible with geolocation app, which is a shopify app. So that they can make some adjustment with their coding.
