### ISSUE TITLE
Guiding lightning on-board with liquidity services

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#750] opened 2019-04-10 08:44 UTC
When a merchant open uses BTCPay for the first time, he does not have any incoming liquidity to receive any payments.

We should guide the merchant to use services providing this if we detect that he has no incoming liquidity.

Known provider:

1. lnbig
2. bitrefill

Ping @pavlenex you know more?

**Comment by pavlenex** [comment] 2019-04-10 09:52
@NicolasDorier 
I used these:
- https://lightningto.me/
- https://lightningpowerusers.com/home/

Also know these

- https://lightningconductor.net/channels
- https://popmin.net/

This document provides [more info on such services.](https://wiki.ion.radar.tech/tutorials/troubleshooting/bootstrapping-channels)

We should somehow differ premium from free services, and also tell users that sometimes if a service is free they may expect higher routing fees from that node, but some do it really for free, anyhow, it's up to the user to do research and determine which service fits their business needs.

There are some guys making BTCPay Merchant Association, it's still WIP from what I saw, but the main goal seems to have bi-directional channels where merchants help each other, it's not automated though they do it from telegram, so should not be listed there yet, but worth keeping an eye on in the future.

**Comment by NicolasDorier** [comment] 2019-04-10 09:53
Isn't there is zigzap or something like this ?

**Comment by pavlenex** [comment] 2019-04-10 09:57
[ZigZag ](http://zigzag.io/)is an exchange. So to get liquidity, the user needs to send BTC on-chain to them and get LN, but I think you need a channel with them in any case, I don't think they provide liquidity service tbh, it's more a workaround people use to re-balance or simply get from LN to on-chain without closing channels

**Comment by pavlenex** [comment] 2019-04-10 10:00
related #733

**Comment by pavlenex** [comment] 2019-04-17 05:36
Yesterday, I used Bitrefill, was surprised to see that they have BTCPay specific code similar to LNBIG which people can copy - paste and it just works.

**Comment by pavlenex** [comment] 2019-09-29 11:57
@NicolasDorier can we close this, to me it seems like a duplicate of discussion in #733?

**Comment by pavlenex** [comment] 2019-11-15 10:07
Closing as a duplicate of #733

**Closed by pavlenex** 2019-11-15 10:07 UTC
Labels: Feature Request, Lightning
