### ISSUE TITLE
Error when generating Dockerfile

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#1355] opened 2020-02-27 17:14 UTC
**Describe the problem/bug**
When executing the `build.sh` file an error emerges that does not let me create the `Dockerimage`.

**Additional information**
I have tried to run it with the following **.NET** versions:
- 2.1
- 2.2
- 3.1

**Logs (if applicable)**
```
/usr/local/share/dotnet/sdk/2.1.804/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: El SDK de .NET actual no admite el destino .NET Core 3.1. Use el destino .NET Core 2.1 u otro inferior, o bien una versión del SDK de .NET que admita .NET Core 3.1. [/Users/sokardys/workspace/rookielabs/btcpayserver/BTCPayServer.Data/BTCPayServer.Data.csproj]
```

**To Reproduce**
1. Clone the repo
2. Run the`build.sh` file

**Expected behavior**
`Dockerimage`is generated without errors.

**Actual behavior**
It pops up an error. No `Dockerimage` is generated

**Comment by pavlenex** [comment] 2020-02-29 10:01
@NicolasDorier @Kukks Any clue?

**Comment by bolatovumar** [comment] 2020-03-01 03:29
@whiteyhat have you added a `global.json` file in your root folder?
This is what my file looks like:
`{
  "sdk": {
    "version": "3.1.100"
  }
}`

Make sure to specify the exact version of .NET Core you are using (3.1.x).

**Comment by NicolasDorier** [comment] 2020-03-02 09:29
you need to download the dotnet **SDK** not runtime.

Check `dotnet info` output to see if it is installed.

**Comment by whiteyhat** [comment] 2020-03-02 10:51
@NicolasDorier Maybe I am not expressing well the issue.  My end-goal is being able to generate a `Dockerfile` in the same conditions as https://hub.docker.com/r/btcpayserver/btcpayserver.

What are the steps to successfully execute `docker build`.

### Side note
How can I reach to the point where I can compile these 3 architectural builds?
1. https://github.com/btcpayserver/btcpayserver/blob/master/arm64v8.Dockerfile
2. https://github.com/btcpayserver/btcpayserver/blob/master/arm32v7.Dockerfile
3. https://github.com/btcpayserver/btcpayserver/blob/master/amd64.Dockerfile

**Comment by Kukks** [comment] 2020-03-02 11:14
> 
> 
> @NicolasDorier Maybe I am not expressing well the issue. My end-goal is being able to generate a `Dockerfile` in the same conditions as https://hub.docker.com/r/btcpayserver/btcpayserver.
> 
> What are the steps to successfully execute `docker build`.
> ### Side note
> 
> How can I reach to the point where I can compile these 3 architectural builds?
> 
>     1. https://github.com/btcpayserver/btcpayserver/blob/master/arm64v8.Dockerfile
> 
>     2. https://github.com/btcpayserver/btcpayserver/blob/master/arm32v7.Dockerfile
> 
>     3. https://github.com/btcpayserver/btcpayserver/blob/master/amd64.Dockerfile

Build.sh does not create a docker image. 

`docker build -f amd64.Dockerfile .` is all it takes No dependency on dotnet either when doing this.

**Comment by NicolasDorier** [comment] 2020-03-11 06:14
hey @whiteyhat you can build all images from this script that we update when we generate new image:

https://github.com/btcpayserver/btcpayserver-docker/blob/master/contrib/build-all-images.sh

**Comment by NicolasDorier** [comment] 2020-03-11 06:15
For example:

```bash
# Build btcpayserver
# https://raw.githubusercontent.com/btcpayserver/btcpayserver/v1.0.3.164/amd64.Dockerfile
DOCKERFILE="amd64.Dockerfile"
# https://raw.githubusercontent.com/btcpayserver/btcpayserver/v1.0.3.164/arm32v7.Dockerfile
[[ "$(uname -m)" == "armv7l" ]] && DOCKERFILE="arm32v7.Dockerfile"
# https://raw.githubusercontent.com/btcpayserver/btcpayserver/v1.0.3.164/arm64v8.Dockerfile
[[ "$(uname -m)" == "aarch64" ]] && DOCKERFILE="arm64v8.Dockerfile"
echo "Building btcpayserver/btcpayserver:1.0.3.164"
git clone https://github.com/btcpayserver/btcpayserver btcpayserver
cd btcpayserver
git checkout v1.0.3.164
cd "$(dirname $DOCKERFILE)"
docker build -f "$DOCKERFILE" -t "btcpayserver/btcpayserver:1.0.3.164" .
cd - && cd ..
```

**Comment by pavlenex** [comment] 2020-03-22 07:59
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2020-03-22 10:16 UTC
Labels: Closing
