### ISSUE TITLE
[Bug]: Can't spend Taproot inputs using PSBTs

### ISSUE THREAD

**Issue by sethforprivacy** [btcpayserver/btcpayserver#5715] opened 2024-01-31 19:26 UTC
### What is your BTCPay version?

v1.12.4+2111b67e2 (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

Attempting to test spending Taproot inputs on Passport, but am unable to actually send any transactions using PSBTs.

### How did you encounter this bug?

1. Go to Bitcoin wallet
2. Hit Send
3. Populate transaction details (spending entire UTXO)
4. Set fee manually
5. Hit Sign Transaction
6. Hit PSBTs
7. See transaction details with "Impossible to finalize the input" warning tooltip next to input index
8. Export PSBT (QR or microSD)
9. Provide updated PSBT (QR or microSD)
10. Nothing happens
11. Hit Sign Transaction and get booted back to the beginning of the entire flow

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by sethforprivacy** [comment] 2024-02-07 16:36
Ping @Kukks, AFAICT this is not Passport-specific and may apply to any testnet spending via PSBTs.

**Comment by NicolasDorier** [comment] 2024-05-09 01:21
I don't have a passport with me.
@sethforprivacy I can look but I need you to help.
Is it possible that you make a testnet or regtest wallet then:

1. Give me the seed.
2. Give me the unsigned PSBT
3. Give me the PSBT after being signed by Passport

**Comment by pavlenex** [comment] 2024-05-15 08:47
@sethforprivacy we'll need your help here so we can proceed with debuging, please see ^

**Comment by sethforprivacy** [comment] 2024-05-15 11:02
Hey guys, sorry for the delay here. will get you what you need today.

**Comment by sethforprivacy** [comment] 2024-05-15 13:09
I don't have a testnet instance of BTCPay to test with, but here is an example seed, unsigned PSBT, signed PSBT, and wallet export file from Passport. The PSBTs were generated using Sparrow Wallet.

```
panda myself doctor maid sketch jump riot movie infant giraffe dawn ill giraffe year fresh crumble wet utility island feed mouse pistol wise skull
```
Files:

https://drive.proton.me/urls/5BGYW1BM6M#iwWlCAdob6e6

**Comment by NicolasDorier** [comment] 2024-05-20 04:50
@sethforprivacy so it comes from the `sigHash` which has value `0` which, I think, means "default". And it seems NBitcoin doesn't support this. Will fix that.

**Comment by sethforprivacy** [comment] 2024-07-18 12:06
Hi @NicolasDorier, it seems this bug is still present, and we've narrowed it down to an incorrect implementations of the PSBT spec for Taproot. From our lead Passport dev:

> I found the problem, at least in psbt-export.psbt. (BIP174 for reference) They're giving us a PSBT_IN_BIP32_DERIVATION, when for taproot, we need a PSBT_IN_TAP_BIP32_DERIVATION. We also need them to include a PSBT_IN_SIGHASH_TYPE of 0 for "default", rather than the assumed value of 1 which is used for all other signature types. The screenshot below shows debug from a psbt sparrow created for the same wallet, with the proper fields in the first 3 lines of debug after the startup headers. The "tap_subpath" is the PSBT_IN_TAP_BIP32_DERIVATION. The last line indicates the only field included in the btcpay psbt, a non-taproot bip32 derivation.

![image](https://github.com/user-attachments/assets/0f8197fc-62d4-4773-a74f-dec1ed6956dc)

I can share the seed phrase and PSBTs used to find this issue privately, just let me know where to send them so you can test/verify.

CC @pavlenex, AFAICT this would still prevent any PSBT-based transactions from working when using Taproot.

**Comment by Jacksper13** [comment] 2024-08-29 15:59
Pinging this @pavlenex, any chance we could reopen the issue?

**Comment by NicolasDorier** [comment] 2024-08-30 00:37
@sethforprivacy @Jacksper13 this may be caused by the fact we still used an old version of NBX (before bug was fixed) looking into it.

**Comment by NicolasDorier** [comment] 2024-08-30 00:59
I bumped NBX so at least there is no more crash, but need to make sure I am creating the PSBT correctly for you now.

**Comment by NicolasDorier** [comment] 2024-08-30 07:34
Ok, so I bumped NBX to 2.5.6 on the btcpay-docker. After updating btcpay, you have the new version.

This should fix the issue. But I wait you to test before closing the issue. @sethforprivacy @Jacksper13

**Comment by Jacksper13** [comment] 2024-09-06 16:25
Hey @NicolasDorier, so we tested this and were getting an icorrect xfp error while trying to sign. From our guy:

> the first two lines here are from the btcpay psbt, and the remaining lines are from sparrow:
> ![image](https://github.com/user-attachments/assets/a347cfe7-f2a6-43bf-8c7f-3d00314c0d94)
> it looks like btcpay needs to label taproot input paths with PSBT_IN_TAP_BIP32_DERIVATION = const(22), set their sighash to 0 for taproot inputs, and set the tap_internal_key field of the psbt

> The different xfp is resulting from the parsing of taproot subpaths being different, so they likely have the right values, but when they're labeled as bip32 subpaths they get parsed weird

**Comment by Jacksper13** [comment] 2024-10-30 15:00
Following up on this @NicolasDorier @pavlenex, I see v2.0.0 was rleased (congrats!) - is the plan to reschedule issues like this one that were planned for 1.13.6?

**Comment by NicolasDorier** [comment] 2024-12-05 05:34
@Jacksper13 please can you try this on 2.0 ? I have checked right now and we are doing all of this.

* With set the `sighash to 0`
* There is `PSBT_IN_TAP_BIP32_DERIVATION `
* The xfp is correct.

> The different xfp is resulting from the parsing of taproot subpaths being different, so they likely have the right values, but when they're labeled as bip32 subpaths they get parsed weird

I have no idea what that mean... 4CC7FF65 is the same xfp as provided in @sethforprivacy example.

**Comment by NicolasDorier** [comment] 2024-12-05 05:43
Mmmh actually I see a difference: The output, the example you gave me set `bip32_taproot_derivs`, while we set `bip32_derivs`

**Comment by NicolasDorier** [comment] 2024-12-05 06:27
Confirming NBXplorer 2.5.16 will now generate exactly the same PSBT as @sethforprivacy shared.

We will release 2.5.16 at the same time as BTCPay 2.0.4.
Please reopen after if there is still any issue.

**Closed by NicolasDorier** 2024-12-05 06:27 UTC
Labels: Bug, need-info

**Comment by NicolasDorier** [comment] 2024-12-11 12:32
BTCPay Server 2.0.4 and NBXplorer 2.5.16 are out!

**Comment by sethforprivacy** [comment] 2024-12-11 12:47
> BTCPay Server 2.0.4 and NBXplorer 2.5.16 are out!

CC @Jacksper13!
