### ISSUE TITLE
Event types don't match in Greenfield API docs, "settled" is not defined

### ISSUE THREAD

**Issue by d2ro** [btcpayserver/btcpayserver#2294] opened 2021-02-17 12:26 UTC
Hi, the webhook event types in the Greenfield API documentation don't match the webhooks and our observations. The [Greenfield API docs](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/Invoice%20created/post) state:

> The type of this event, current available are InvoiceCreated, InvoiceReceivedPayment, InvoicePaidInFull, InvoiceExpired, InvoiceConfirmed, and InvoiceInvalid.

Here is an overview:

| Webhook (docs sidebar and store settings) | Event type in API docs | Observed type in BTCPayServer v1.0.6.8 |
| ----------------------------------------- | ---------------------- | ---------------------------------------|
| Invoice created                           | InvoiceCreated         | InvoiceCreated                         |
| Invoice expired                           | InvoiceExpired         | InvoiceExpired                         |
| Payment received                          | InvoiceReceivedPayment | InvoiceReceivedPayment                 |
| Invoice processing                        |                        | InvoiceProcessing                      |
| Invoice invalid                           | InvoiceInvalid         | (not tested)                           |
| Invoice settled                           |                        | InvoiceSettled                         |
|                                           | InvoicePaidInFull      |                                        |
|                                           | InvoiceConfirmed       |                                        |

Probably the event type strings in the Greenfield API documentation need to be updated.

It is still unclear what "settled" means. The [payment request docs](https://docs.btcpayserver.org/PaymentRequests/#paid-request-for-payment) state that "the status will appear as Settled if payment has been received in full". However we observed that an "InvoiceSettled" event has been triggered at the same time as "new event: invoice_confirmed" was logged. Can anyone give me a hint?

**Comment by Kukks** [comment] 2021-02-17 13:53
Transferring to main btcpay repo as this is where we have our swagger docs written

**Comment by Kukks** [comment] 2021-02-17 13:58
>It is still unclear what "settled" means. The payment request docs state that "the status will appear as Settled if payment has been received in full". However we observed that an "InvoiceSettled" event has been triggered at the same time as "new event: invoice_confirmed" was logged. Can anyone give me a hint?


Settled means "Complete and final" in that you can consider the invoice as good to go. If an invoice is paid via lightning, you will most likely receive `InvoiceReceivedPayment`, `InvoiceProcessing` and `InvoiceSettled` in one go as it is considered final as soon as it arrives.

In the old BItpay API, there was a concept of a payment on-chain being confirmed but not complete, typically needing to always reach 10 confirmations for it to transition to 10. The GreenField API has removed that unnecessary complexity and once a payment is confirmed, it is considered "settled" (or complete in terms of bitpay event equivalent)

**Comment by d2ro** [comment] 2021-02-20 10:12
Thank you. I hope it's correct to assume that an invoice is "settled" if and only if:

* payment has been _received_ in time (i.e. seen in the mempool before the invoice time expired)
* and the transaction is _confirmed_ (got n confirmations on the blockchain)
* and the _full amount_ has been paid.

This definition is important to us because we'd like to keep the btctransmuter and our shop system in sync and handle edge cases correctly (payment received late, underpaid, multiple payments to the same address, etc.).

**Comment by pavlenex** [comment] 2021-02-27 07:58
Related or in a way duplicate of #1789, however won't close it as it's important topic to tackle. I agreed that current state of statuses in the Greenfield is confusing, especially the `settled` state.

**Closed** 2021-02-27 08:05 UTC
