### ISSUE TITLE
[Bug]: Tag not applied in the Wallet Send

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#5591] opened 2023-12-22 02:06 UTC
### What is your BTCPay version?

1.12.2

### How did you deploy BTCPay Server?

docker

### What happened?

Add a tag in Wallet Send, broadcast the transaction, see the transaction in the list not having the tag.

### How did you encounter this bug?

Add a tag in Wallet Send, broadcast the transaction, see the transaction in the list not having the tag.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment] 2023-12-22 11:38
I cannot reproduce this and the tags for sending and receiving get applied properly. 

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/faced994-4cc1-4925-bc27-a599b370ea3c)

They are also shown in the process on the confirmation page:

![1](https://github.com/btcpayserver/btcpayserver/assets/886/ce395323-f1e4-4fa3-802a-8b46140530a6)

**Comment by pavlenex** [comment] 2024-01-25 08:35
This should be resolved in https://github.com/btcpayserver/btcpayserver/pull/5700

**Closed by pavlenex** 2024-01-25 08:35 UTC
Labels: need-info
