### ISSUE TITLE
[Bug]: standard Tea shop (PoS app) first item breaks after going from shop + cart to just shop 

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver#4889] opened 2023-04-17 15:13 UTC
### What is your BTCPay version?

BTCPay Server v1.9.0 and BTCPay Server v1.9.1

### How did you deploy BTCPay Server?

Luna node standard deployment

### What happened?

After trying to figure out the new receipt situation, i switched between shop + cart to just a shop without cart.

Since this swap, the first item in the shop list brings a 404 page. 

### How did you encounter this bug?

Create a PoS shop. 

Switch to a Product list + cart. 
Save
Buy product 1 in the list ( or at least mark as settled on that invoice) 
Switch to just Product list. 
Save

it seems however, it breaks only in the same view i had open before. 
If you reopen the view from the PoS it seems fine?

### Additional information

petzsch and i were going through some motions of the shop and encountered this bug. 
Petzsch runs 1.9.1 and i'm running on the 1.9.0 version. 

![image](https://user-images.githubusercontent.com/102448109/232529657-ad9e8663-6bff-43d7-b076-78e6cb5e3507.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment] 2023-04-17 15:39
Problem does not occur when Hard-Reloading (Ctrl - Shift - R in Firefox) the page after changing from product list with cart to product list.

Also doesn't occur when closing the shop tabs and re-opening them through the "View" button from the backend.

So it could be a caching issue. Perhaps something with LocalStorage? 404 (NotFound) seems to be the kind of [standard reply](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs#L198) if something went wrong on this PoS.

**Comment by NicolasDorier** [comment] 2023-04-20 00:15
I can't reproduce this.

1. Create a new PoS with cart view
2. Buy an item, see the receipt, go back to PoS view
3. Change the PoS to product via
4. F5 on the PoS view page

Then the first item works. That said, the HTML @petzsch  show isn't right, but I can't reproduce it.

**Comment by NicolasDorier** [comment] 2023-04-20 00:31
I tried the other way around, where I create a pos without cart, pay and then switch on the pos with cart.
It works.

**Comment by dennisreimann** [comment] 2023-04-20 09:56
I cannot reproduce this either.

**Comment by dennisreimann** [comment] 2023-04-20 10:50
I tested in Firefox

**Comment by Bas02** [comment] 2023-04-20 15:56
Reproducible for sure on as it seems any firefox install, freshly installed or with extensions doesn't matter. Even Android Firefox is affected. Tried multiple Chromium based browsers (chrome and Chromium) they seem fine. 

![AnimationBUG](https://user-images.githubusercontent.com/102448109/233420400-24ff4198-9418-4891-b94a-308df9f988a3.gif)

**Comment by dennisreimann** [comment] 2023-04-26 08:13
I think this is a caching problem in the browser. I was able to reproduce it on first load, after reloading the page once more it works as intended. The weird thing is: even though the values are correct on first load (verified via debugger), the choiceKey for the first item is set incorrectly to an integer value.

imho we should close this, as this also seems to be Firefox specific and is a rather unlikely scenario to matter in practice.

**Comment by Bas02** [comment] 2023-05-03 13:16
The consensus is no fix at this time.

**Comment by rockstardev** [comment] 2023-05-04 15:39
I've asked @Bas02 to show me how to reproduce the problem and in the process managed to fix this issue. 

Team, please see PR 4950, I've also included screen recording there and merge the fix if it looks good to you.

**Closed** 2023-05-04 16:49 UTC
Labels: Bug, PoS
