### ISSUE TITLE
Withdrawing funds using Spark console

### ISSUE THREAD

**Issue by RhinoAK** [btcpayserver/btcpayserver#1195] opened 2019-11-27 00:31 UTC
Whenever I attempt to issue the command `withdraw bech_address satoshi_amount ` I keep getting Cannot afford transaction even though I have 900000+ sats on the node. My question is what limitation does using this command have in terms of the number of uses? Also when attempting the same command with the parameter of "all" I get the same error.

**Comment by pavlenex** [comment] 2019-11-28 09:53
I've noticed the same, I think you should post this in [Spark](https://github.com/shesek/spark-wallet)/[c-lightning ](https://github.com/ElementsProject/lightning/issues/)repository since it's not really related to BTCPay itself.

**Comment by RhinoAK** [comment] 2019-11-28 09:59
Ah, I'm glad to see I'm not the only one experiencing this issue. Your recommendation has merit, but let me ask how can you be so certain? What solution have you found within the repo you're referring me to?

**Comment by pavlenex** [comment] 2019-11-28 16:36
Because Spark is a wallet your using and c-lightning is implementation you're using that function independently of btcpay.

**Comment by pavlenex** [comment] 2019-11-28 18:41
@RhinoAK hey, I've taken a look and this is indeed something between bitcoind and c-lightning. I've [opened an issue for myself here ,](https://github.com/ElementsProject/lightning/issues/3302) so feel free to chime in, I hope we'll troubleshoot it with the help of c-lightning devs.

**Comment by pavlenex** [comment] 2019-12-10 12:49
I think I figured out the issue, it's both technical and UX issue.
First of all, the two channels I had did not close for over 2 weeks. 
I've noticed they're in `closing` status in Spark for quite a while.
What I did was force-closed those stuck channels with this:
```
close id [unilateraltimeout] [destination]
Close the channel with {id} (either peer ID, channel ID, or short channel ID). Force a unilateral close after {unilateraltimeout} seconds (default 48h). If {destination} address is provided, will be used as output address.
```
You can do this from Spark itself, but I did it from btcpay's ssh.
`bitcoin-lightning-cli.sh close channelidgoeshere 2`

I'm hoping this was the problem, we'll see but you may want to check if you're having some stuck channels as well.

**Comment by pavlenex** [comment] 2019-12-10 12:58
But then again, `listfunds` provides me with a list of txid's that are confirmed but it seems c-lightning can't read them as such, probably due to pruning issues I'm unable to troubleshot myself.

**Comment by pavlenex** [comment] 2019-12-12 11:51
Okay, I think I figured out the issue. It took  a while, but as i mentioned, I think this is a UX issue in Spark first, since spark shows you the balance, even though it's not confirmed, leading  you to think you can withdraw it. 

@shesek you may want to separate unconfirmed vs confirmed on-chain balance in the future?

The other part of the issue is c-lightning, which, even though transactions are confirmed, does not see them as confirmed, possibility because of the use of a pruned node. I've left my [comment on their repo,](https://github.com/ElementsProject/lightning/issues/3302) but so far nobody was able to help.

@RhinoAK  I'll go ahead and close this issue mostly due to inactivity and the fact that , it's problem with Spark's UI and c-lightning even more. You can comment on the issue I opened or just let me know if you solved your somehow meanwhile.

**Closed by pavlenex** 2019-12-12 11:51 UTC
Labels: Lightning

**Comment by shesek** [comment] 2019-12-12 22:30
@pavlenex when developing this I assumed that all funds must be confirmed because c-lightning doesn't not process mempool transactions, but I neglected to take unconfirmed transactions issued by c-lightning itself into account (this effects not only channel closures, but also the change output of on-chain withdrawals). I opened https://github.com/shesek/spark-wallet/issues/129 to keep track of fixing this.

**Comment by pavlenex** [comment] 2019-12-18 22:32
Thanks @shesek , appreciate it.

@RhinoAK I've solved my issue by following cdecker [instructions here](https://github.com/ElementsProject/lightning/issues/3302#issuecomment-567219590), I am quite certain your issue is the same in case you haven't figured it out yet.
