### ISSUE TITLE
Sold items from POS app not exported

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#937] opened 2019-07-21 16:51 UTC
**Is your feature request related to a problem? Please describe.**
It's impossible to process sold items in automated fashion because the item data is missing from exported invoices. The only way to do that is to manually open each invoice and copy-paste the item data.

**Describe the solution you'd like**
Add the items into the exported data. In case it is undesirable to mix them, create a separate export items feature.

**Describe alternatives you've considered**
We're thinking about writing some simple SQL commands that will do that directly on the server. This will be easy to do once we understand the data in the database, but a nicer, official solution would be useful for other merchants. If you decide against this feature, it'd be very helpful if you could hint us at what exactly is in the database (the proper SQL command to get the data)

**Comment by pavlenex** [comment] 2019-07-21 16:55
Related slightly to #590

**Comment by Kixunil** [comment] 2019-07-21 16:59
Yes, resolving that one would be also helpful for us. I thought that while similar, it makes sense to keep the issues separate.

**Comment by bolatovumar** [comment] 2019-08-21 15:11
@Kixunil what status do the invoice that are missing have? I'm trying to repro the issue but can't as I'm not sure what status the invoice should be in in order for me to repro the issue.

The status that exist as far as I can see are: complete, paid, confirmed, invalid, expired, new.

And just to confirm I'm talking about this screen:
![Screen Shot 2019-08-21 at 6 07 27 PM](https://user-images.githubusercontent.com/1934678/63444298-00fbda80-c43f-11e9-9180-bd8e35407754.png)

**Comment by Kixunil** [comment] 2019-08-21 15:40
The status is complete. The Export button is there of course, but if you try to export the data, you'll see that the POS items aren't there - just invoices.

FYI, I've implemented a hacky ugly script to do that, but it'd be better if we could do it directly.

**Comment by bolatovumar** [comment] 2019-08-21 16:30
@Kixunil, oh, okay, I misunderstood your issue then. I thought you meant that invoices for items marked as "complete" weren't getting exported but the issue seems to be that there is no indication as to which POS items these invoices correspond to, correct?

**Comment by bolatovumar** [comment] 2019-08-21 16:34
@Kixunil what data specifically would you want to see? I have "invoice item code" and "invoice item description" in my export. Is there anything else you would like to see alongside these two or am I missing the point?
![Screen Shot 2019-08-21 at 7 31 45 PM](https://user-images.githubusercontent.com/1934678/63450427-a8cad580-c44a-11e9-842e-0ee20211e82d.png)

**Comment by Kixunil** [comment] 2019-08-21 17:36
You're correct now. Those two are enough. (I guess the time is already there, right?)

I'm not sure what's the best way to represent several items paid by a single invoice, though.

**Comment by bolatovumar** [comment] 2019-08-21 17:44
@Kixunil I don't know how BTCPay currently represents the case of multiple items paid for with a single invoice as I don't have an example of such transaction but I would assume it would have a comma separated list of items as such:
`black tea, green tea, some other tea`

**Comment by Kixunil** [comment] 2019-08-21 17:49
It's stored as cart inside `posData` inside invoice. I think a separate "Export POS items" feature would be more reasonable, which would contain time, invoice ID, product name and count. Time and invoice ID would get duplicated if multiple items were paid by same invoice.

**Comment by pavlenex** [comment] 2023-03-03 09:55
@Kixunil Is this still important to you? We're thinking of exposing this in the receipts #4716 perhaps it would make sense to have better way to expose this for PoS users, care to provide more feedback if anything changed since you requested this feature? How do you guys handle accounting?

**Comment by pavlenex** [comment] 2023-03-03 09:56
@NicolasDorier I think this issue basically requests to add `export pos` function to invoices. We currently export `paid` but it's been requested to have a separate functionality for #2601, is there a way we could somehow scope this?

**Comment by Kixunil** [comment] 2023-03-03 10:26
@pavlenex unfortunately since then COVID took down our space, so this is not urgent but would be nice to have eventually in case we manage to reopen.

We were using BTCPayServer as the main source of truth. So we wanted to know which items were sold and when.

**Comment by jooray** [comment] 2023-03-03 11:14
Yes, our space is closed, but Paralelni Polis Prague and Košice are both using the pos mode. I'll share this issue with them so they can comment.

**Comment by pavlenex** [comment] 2023-03-03 11:32
Thanks @Kixunil @jooray! 🙏

**Comment by michaltakac** [comment] 2023-03-03 13:49
At Paralelná Polis Košice, as @jooray and @Kixunil said, we have the same usecase.

**Comment by NicolasDorier** [comment] 2023-06-22 01:23
This is details of the field needed: https://github.com/btcpayserver/btcpayserver/discussions/4598

**Closed** 2023-07-11 09:39 UTC
Labels: Feature Request, App, Invoice, PoS
