### ISSUE TITLE
Lightning node doesn't start anymore UNUSUAL plugin-bcli: bitcoin-cli

### ISSUE THREAD

**Issue by Alko89** [btcpayserver/btcpayserver#2152] opened 2020-12-19 12:32 UTC
After updating BtcPay server I'm unable to ping or create channels to the lightning node. I have ssh to the server and checked the logs in the docker container and see the same warning being logged:

`UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000001afc2c9ef915b14d51f92938832734466a93d93f518bd7 0 exited with status 1`

**Comment by pavlenex** [comment] 2020-12-20 13:59
Seems a duplicate of #373

**Closed** 2020-12-20 14:00 UTC
Labels: need-info
