### ISSUE TITLE
[Bug]: Pay invoices with LNDHub connection to Phoenixd Server LN Backend

### ISSUE THREAD

**Issue by Hodladi** [btcpayserver/btcpayserver#6100] opened 2024-07-10 20:13 UTC
### What is your BTCPay version?

Im running BTCPay Server v1.13.3

### How did you deploy BTCPay Server?

Through ParmaNode as Docker deploy.

### What happened?

The setup and the config works like a charm but since im running a node with Phoenixd Server as backend and connect it to BTCPay Server through LNDHub i get errors in Pay button, Crowdfund and with Lightning Address when i try to pay the generated LN Invoice.

I can scan the QR and get either a pre-set amount through Pay button or enter an amount with the crowdfund and with lightning address ( it do route correctly with ln address and its possible to fill in the amount ) .

But when paying with for example Wallet of Satoshi i get an modal saying
"Lightning node could not generate invoice with description hash: DescriptionHas ('h' field) is not specified in the BOLT11 object"

It doesnt matter if I add an note to the payment or not.
I have tried to change all different settings in BTCPay Server without success.

The weird part is that the POS works as its supposed.

### How did you encounter this bug?

When trying to pay an LN invoice generated from Pay button, crowdfund or through lightning address.

### Relevant log output

```shell
I dont have logging enabled.
```

### What browser do you use?

All different kinds
but its when paying with a LN wallet it fails

### Additional information

I would love to see Phoneix Server as LN backend.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment] 2024-07-17 13:18
Duplicate of #6070, closing in favor of that one

**Closed by pavlenex** 2024-07-17 13:18 UTC
