### ISSUE TITLE
UI of cryptocurrency selection in the invoice

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#434] opened 2018-12-04 19:07 UTC
We were discussing with @bitcoinshirt that many customers do not get, how they can select the payment currency in the invoice. Maybe the tech people get that the dotted underline means that it is clickable, but many other customers do not get it and even though they know that there are other payment methods, they keep asking, how to select them.

**Comment by NicolasDorier** [comment] 2018-12-07 09:02
pign @rockstardev

**Comment by astupidmoose** [comment] 2018-12-10 06:53
I agree with this, we are still getting some customers asking "how to use this", or even worse some of them are simply sending LTC to our BTC addresses (This might not be fixable, not sure you can fix stupid lol).

I think maybe the currency in the "Pay with" needs to be formatted as a dropdown box, similar to the styling of the conversion tab on changelly. 

![image](https://user-images.githubusercontent.com/3916318/49715422-288a7a00-fc05-11e8-86fe-ebff3a6d80f8.png)

This boxed button approach gives a bit better hint at "You can click this and see more".

**Comment by bitcoinshirt** [comment] 2018-12-10 09:00
@astupidmoose  If you remember in past we had coin icons one next to the other, imo it's much better UX, but I think there was a technical problem with this setup. Especially if someone decides to have 10+ coins...

**Comment by mariodian** [comment] 2018-12-12 11:44
Why not just start with a screen that forces user to select a currency? When clicked, the currency list would roll up, the currency option would be added to the "Choose Currency" section (which also explicitly tells user that he can choose anytime) and the QR code would be displayed. That way user should be able to assume that when he clicks it again the currency list would roll down and he can choose again.

See the pic:

![checkout](https://user-images.githubusercontent.com/3636406/49867562-db491b00-fe45-11e8-80df-f0523a6acb33.png)

**Comment by bitcoinshirt** [comment] 2018-12-12 11:48
@mariodian This is good concept.

We discussed this in #22 already and exactly the idea that I had.
Two problems with this:
1. Adds additional step for the end-user on the checkout
2. In BTCPay user can pay invoice in multiple coins. You can pay 0.4 in BTC and 0.2 in LTC. How would end user switch currencies in that case? We probably should have a drop-down in the invoice for those.
I'm not sure if this technically creates any trouble on the back-end.

**Comment by mariodian** [comment] 2018-12-12 11:54
> Adds additional step for the end-user on the checkout

True, but if he doesn't want to pay with the predefined currency, he will need to perform an additional step anyway. If he's forced to choose a currency first at least he knows how to do it.

> In BTCPay user can pay invoice in multiple coins.

That I think shouldn't be allowed. Seems like an UX nightmare to me.

> But if the user has to select a coin, pay with another, then select a coin from the drop-down to pay for the rest of the invoice, perhaps then we only need drop down. 

Think of the list that I designed as a "dropdown". There's no need for extra control. 

Select BTC from the list, pay 0.4BTC, click the "choose currency" again, select LTC and pay the rest.

**Comment by bitcoinshirt** [comment] 2018-12-12 11:59
It's not that easy. People actually pay invoices like that and that's sort of a feature. But I don't think many people use it (according to @astupidmoose he has good portion of customers paying like that).

The thing is this would not only improve the coin selection UX, but also reduce the amount of unnecessary invoices. BTCPay currently creates a new address for every coin regardless if you pay with it or not, which creates a gap limit issue.

I think compromise in this case would be to allow the selection of the main coin you want to pay in, then have a drop-down in invoice (more visible drop down). This can be good also if customer changed his mind regarding the coin, or just wants to pay partially.

Question for @NicolasDorier if we do this, do we actually reduce gap limit or does BTCPay still need multi addresses?

**Comment by mariodian** [comment] 2018-12-12 12:12
> If invoice is paid partially we show again coin screen with the amount and also a warring that invoice is partially paid.

Yup it could be something like this:

![checkout-partial](https://user-images.githubusercontent.com/3636406/49869081-4399fb80-fe4a-11e8-96d1-01162bd1b9ce.png)

**Comment by bitcoinshirt** [comment] 2018-12-12 12:14
ACK from me. 

I only want to hear if that solves the gap limit issue, if it does, we can kill an amazing amount of issues with this. You may be my favorite person of the day now.

**Comment by mariodian** [comment] 2018-12-12 12:31
Then what Nicolas said https://github.com/btcpayserver/btcpayserver/issues/46#issuecomment-360729906

> The desired alternative is to add one more step in checkout. The customer is directed to a page asking him to select the currency in which he wants to pay the invoice. Then only this currency will be supported by this invoice. This prevent getting huge address gap.

The currency selection would have to be explicitly confirmed (with a button) though to prevent mis-clicks. 

When the user partially pays he'd be forced to select a currency again.

**Comment by bitcoinshirt** [comment] 2018-12-12 14:49
So I'll just copy what Nicolas said on Slack:
> problem is that I can't create an invoice until I know all the crypto used. I can't create an "half invoice"

Perhaps we allow the user to select right there on the checkout. If you select two you can pay in two parts. Seems clunky.
Any better ideas @mariodian?

**Comment by mariodian** [comment] 2018-12-12 15:41
>  I can't create an "half invoice"

What's the reasoning behind this?

**Comment by NicolasDorier** [comment] 2018-12-13 03:35
In other words, it would require a huge refactoring and would introduce difficult issues that I prefer not having to think about.
An invoice, once created, is independant and immutable. I rely on this assumption and breaking it will cause lot's of non obvious breakage. Not only on consumer software, but in btcpay itself.

**Comment by mariodian** [comment] 2018-12-13 05:53
Then the invoice should only be created after user selects a currency (if we want to solve the gap issue). Which is also lots of work on the side of the invoice but shouldn't break anything.

**Comment by bitcoinshirt** [comment] 2018-12-16 09:10
> Then the invoice should only be created after user selects a currency

User has to pre-select all the coins. However, the majority of users is not aware the invoice can be paid with multiple coins. What happens if user just selects one? Do we wait for him to "confirm" after the selections?

I can't think of a user-friendly way to handle this, @mariodian I'm sure you'll have better ideas.

**Comment by NicolasDorier** [comment] 2018-12-28 08:42
> Then the invoice should only be created after user selects a currency (if we want to solve the gap issue). Which is also lots of work on the side of the invoice but shouldn't break anything.

We can't do this without breaking every client. Because the process is:
1. They create the invoice through the API
2. They redirect user to the invoice url

**Comment by pavlenex** [comment] 2019-02-27 13:58
Okay lads, @hubiktomas  @astupidmoose @mariodian our man @rockstardev added an improvement in 1.0.3.67 and now the coin selection is more obvious and has a boarder

![d0z2ki9vsaesz1g](https://user-images.githubusercontent.com/36959754/53495337-0e439800-3aa0-11e9-805f-09b644449635.png)

Happy, not happy? I'll mark this one as `closing` but let's discuss and see how it works. If you have complains from customers even if we close it, we'll re-open it and find solution.

This issue had some productive discussion on various topics, so will leave it open to see if we can come to an agreement.

**Comment by astupidmoose** [comment] 2019-02-27 19:24
Looks good, I like that its more of a button look to indicate an action

**Comment by Eskyee** [comment] 2019-02-27 19:25
Happy 😃🎉

**Comment by hubiktomas** [comment] 2019-02-28 07:59
Cool, it is much more intuitive now. :)

**Comment by pavlenex** [comment] 2019-02-28 12:10
Okay, in that case let's consider this issue solved and re-open if any of you gets feedback from customers that it's not enough.

**Closed by pavlenex** 2019-02-28 12:10 UTC
Labels: Closing, Enhancement, Invoice, UI / UX
