### ISSUE TITLE
Customizable BOLT11 invoice expiration time from submission

### ISSUE THREAD

**Issue by Jossec101** [btcpayserver/btcpayserver#3332] opened 2022-01-18 18:49 UTC
Hi, thanks for the amazing project!

We have been using btcpayserver lately and we found that BOLT11 invoices expiration date have to be at least 30 days from submission and this is hardcoded, we find that this value could be a environment variable or another configuration setting instead of being hardcoded.

https://github.com/btcpayserver/btcpayserver/blob/04b8eafacbece8ca507c5ce487cd0fe2fad9297c/BTCPayServer/Data/Payouts/LightningLike/LightningLikePayoutHandler.cs#L97

The main motivation is that we want to make BOLT11 pull payments short-lived and 30 days is too much for us.

We are happy to make a PR for this, 

Best regards,

**Comment by NicolasDorier** [comment] 2022-01-19 12:12
Agree probably need to do something about it, closing as it is a duplicate of https://github.com/btcpayserver/btcpayserver/issues/3281

**Closed by NicolasDorier** 2022-01-19 12:12 UTC
