### ISSUE TITLE
Frontend and Backend Page web locally

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#437] opened 2018-12-08 11:19 UTC
I think HTML pages must be registered in own server because this is always a dependency on GitHub and this is not good because if it closes github the btcpay will not do anything nit work ... in the next implementations I would recommend to implement the system have their own html pages locally.

**Comment by Kukks** [comment] 2018-12-08 14:17
There is no dependency on Github. The pages are hosted internally on your instance.

**Comment by darkban** [comment] 2018-12-08 14:19
It does not turn out to me because I do not see web pages in the paths ... what would be the path in locally?

**Comment by britttttk** [comment] 2018-12-09 00:57
@darkban It looks like you've forked the btcpayserver repository. Have you cloned/downloaded it as well? After you do that you will have a [local copy](https://github.community/t5/Support-Protips/The-difference-between-forking-and-cloning-a-repository/ba-p/1372) to make your own changes.

If you have more questions about Github/Git they have a place to ask questions and you can get answers very quickly from the experts https://github.community/t5/How-to-use-Git-and-GitHub/bd-p/Board_1

**Comment by darkban** [comment] 2018-12-09 12:13
@britttttk  exactly what I was referring to ... all the settings and files should not reside on github but locally on the #britttttk server ... because if you lose access to your account, or github closes you lose all the work done and this is not good ... even html files must reside locally and not on github. Moreover, the fork solution is not a valid solution because this forces to update manually... this type of configuration is not secure. Everyone must have a copy on their server without having external dependencies

**Comment by Kukks** [comment] 2018-12-09 12:17
Forking is an advanced scenario and if you do not have basic understanding of how git works, should not be doing it. The files in your local are "not there" because they are deployed in docker containers.

If you dont want to use it on github, download the code, edit it, build the docker images yourself and deploy them. Yes, you will need to update it manually.

**Comment by darkban** [comment] 2018-12-09 12:46
here this is what I mean ... I should not download and edit anything I should have everything available on my server without depending on third parties and if there should be an update this can be done directly from my deployment. in this way there are too many external dependencies ... in the end my proprietary server is useless because it depends on github and if the github files are deleted the server is useless... it's like having an online wallet ... if the company closes you've lost everything

**Comment by bitcoinshirt** [comment] 2018-12-09 13:08
@darkban  It appears you do not have basic understanding of how GitHub works. Kukks and britkelly already explained pretty well what happens. 

Your rant about third-parties makes no sense.
Please do some further reading on GitHub. Here's [where to start](https://guides.github.com/)

It seems from your post history that you're trying to white-label  BTCPay without any technical knowledge. 

I'm sorry but BTCPay is here to provide secure payment processing, not allow users to make fancy websites on go. Hire a developer to do a white-labeling for you or take some time to understand the basics.

**Comment by bitcoinshirt** [comment] 2018-12-10 12:47
@darkban It seems to me that your initial concern was addressed. I

The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2018-12-10 17:02 UTC
Labels: Question, preparing-to-close
