### ISSUE TITLE
BIP78 sending maxaddtionalfeecontribution without also sending additionalfeeoutputindex

### ISSUE THREAD

**Issue by AdamISZ** [btcpayserver/btcpayserver#2007] opened 2020-10-22 15:57 UTC
**Describe the bug**
BIP 78 requirements:
"Note that both maxadditionalfeecontribution= and additionalfeeoutputindex= must be specified and valid for the receiver to be allowed to decrease an output belonging to the sender. This fee contribution can't be used to pay for anything else than additional input's weight."

In fact BTCPayServer is (sometimes? i have not been able to test much yet) sending only `maxadditionalfeecontribution` without `additionalfeeoutputindex`, and note the case shown below does have a change output.

I note this part of the code which seems pertinent:

https://github.com/btcpayserver/btcpayserver/blob/e2eb26eb93b9080654db03edf90541d7a7324e4b/BTCPayServer/Services/PayjoinClient.cs#L104-L107

**To Reproduce**
Create a store, create a p2wpkh wallet, with payjoin enabled, send a trial payment to Joinmarket receiver.

**Expected behavior**
Payjoin transaction should be broadcast as wallets are compatible (same script type).

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version 1.0.5.8

 
**Logs (if applicable)**

The joinmarket receiver wallet log (not much here, just shows the parameters in the URI:

```
2020-10-22 16:17:28,297 [DEBUG]  The server got this POST request: 
2020-10-22 16:17:28,298 [DEBUG]  <Request at 0x7f978c1a0438 method=POST uri=/?v=1&maxadditionalfeecontribution=8777 clientproto=HTTP/1.1>
2020-10-22 16:17:28,300 [DEBUG]  b'POST'
2020-10-22 16:17:28,300 [DEBUG]  b'/?v=1&maxadditionalfeecontribution=8777'
2020-10-22 16:17:28,300 [DEBUG]  {b'v': [b'1'], b'maxadditionalfeecontribution': [b'8777']}
2020-10-22 16:17:28,301 [DEBUG]  b'/'
2020-10-22 16:17:28,301 [DEBUG]  request content: 63484e6964503842414845424141414141514f7558714e4d72676232547072683066495772417330394a484b6c7a676e43516d674e30562b64694b57414141414141442f2f2f2f2f416d44714141414141414141466741556d3772755778426f32686c3139523654322b37437a494b75784a52354e774d414141414141425941464f6d46453634726f556c457068317a54716f396f71313065577355414141414141414241522f78614151414141414141425941464b3845312f6f707969556a6c3545443676484a61626b756a654e6e41516872416b6377524149675255757a62493071497344476b366b2f617277494a4b716f5541696b4d6f5a49417152554d6d476d613741434948534b384f385a796d684c56634b553769675337656347474b794743395849386b413939356c4a6f35772f41534544676137717768554a6d377a685a57664f694a31717a6176696f7154366753676e65624e7a4e6542684e444d414141413d
2020-10-22 16:17:28,307 [DEBUG]  Returning an error: original-psbt-rejected: Invalid request parameters.
2020-10-22 16:17:28,307 [WARNING]  Negotiation failure. Payment has not yet been made, check wallet.
```

Here is the deserialized initial payment that btcpayserver sent to JM:

```
{
    "hex": "0100000000010103ae5ea34cae06f64e9ae1d1f216ac0b34f491ca9738270909a037457e7622960000000000ffffffff0260ea0000000000001600149bbaee5b1068da1975f51e93dbeec2cc82aec4947937030000000000160014e98513ae2ba14944a61d734eaa3da2ad74796b14024730440220454bb36c8d2a22c0c693a93f6abc0824aaa85008a432864802a4543261a66bb00220748af0ef19ca684b55c294ee2812ede70618ac860bd5c8f2403df79949a39c3f01210381aeeac215099bbce16567ce889d6acdabe2a2a4fa81282779b37335e061343300000000",
    "inputs": [
        {
            "outpoint": "9622767e4537a00909273897ca91f4340bac16f2d1e19a4ef606ae4ca35eae03:0",
            "scriptSig": "",
            "nSequence": 4294967295,
            "witness": "024730440220454bb36c8d2a22c0c693a93f6abc0824aaa85008a432864802a4543261a66bb00220748af0ef19ca684b55c294ee2812ede70618ac860bd5c8f2403df79949a39c3f01210381aeeac215099bbce16567ce889d6acdabe2a2a4fa81282779b37335e0613433"
        }
    ],
    "outputs": [
        {
            "value_sats": 60000,
            "scriptPubKey": "00149bbaee5b1068da1975f51e93dbeec2cc82aec494",
            "address": "bc1qnwawukcsdrdpja04r6fahmkzejp2a3y56c6ctc"
        },
        {
            "value_sats": 210809,
            "scriptPubKey": "0014e98513ae2ba14944a61d734eaa3da2ad74796b14",
            "address": "bc1qaxz38t3t59y5ffsawd8250dz4468j6c53ykhc8"
        }
    ],
    "txid": "f13e7e8e74c0a9f71c1cf4dfac3b2e5a71b877acc890f5cc96d74d5617c031f0",
    "nLockTime": 0,
    "nVersion": 1
}
```
**Setup Parameters**
Using BIP84 native wallet

**Comment by NicolasDorier** [comment] 2020-10-23 02:34
@AdamISZ the code you show me now, means that we don't include `additionalfeeoutputindex` if there is no change. Your code seems to have a change. Will take a look.

**Comment by NicolasDorier** [comment] 2020-10-23 02:39
So I checked in our tests and the aditionalfeeoutputindex is included. Will try manually testing.

**Comment by NicolasDorier** [comment] 2020-10-23 02:52
If there is no change, I confirm the behavior you are pointing out. Is it problematic we still include `maxadditionalfeecontribution=6800` in this case? I can fix that.

But I could not reproduce if there is a change.

**Comment by NicolasDorier** [comment] 2020-10-23 02:59
trying with JM receiver.

**Comment by NicolasDorier** [comment] 2020-10-23 03:11
I don't manage to use JoinMarket QT. Created a wallet, trying to load it now but it says it is not a valid wallet. (using regtest)

**Comment by NicolasDorier** [comment] 2020-10-23 03:14
I think at least not including `maxadditionalfeecontribution` will fix this specific situation, as the pj should still work.
As to why there is no change, I could not reproduce :(

You used the hotwallet to send from btcpay?

**Comment by AdamISZ** [comment] 2020-10-23 09:49
On your first comments: indeed I understood that the case could refer to a no-change scenario, and that's why I showed the transaction does have change. But I also don't think that *either* parameter should be set, if there is no change output.

As to the test:
Sorry I can't remember the exact naming of different setups for btcpayserver, so 'hotwallet' I'm not sure but let me try to write, in a more exact way, what I did:

I registered an account on `mainnet.btcpayserver.btcpayserver.org`.

I went to the onion at `http://fc4booz5wmoq3knc63gf4sn7oisz45sc7zxtlgnqkeqb2pvzqow6ydqd.onion` and did the rest from there.

Then I created a single dummy store.

Then I configured a new wallet: I entered an `xpub` - so BIP84 addresses.

Then, in order to make signing work, I edited a setting of the wallet: for `Account key path` I entered, manually: `m/84'/0'/0'` - note, I did not enter 'Master key fingerprint'

Then, I went to the Send tab, clicked the icon for URI, and pasted the URI generated by Joinmarket.

Then, when I sent the payment I got the error message as described:
"The payjoin transaction could not be created.
The original transaction was broadcasted instead. (f13e7e8e74c0a9f71c1cf4dfac3b2e5a71b877acc890f5cc96d74d5617c031f0)
The payjoin receiver could not complete the payjoin: original-psbt-rejected: The receiver rejected the original PSBT.. (Receiver message: Invalid request parameters.) "

... and the other side of the conversation, you have already seen, in particular the parameters sent.

For regtest setup of Joinmarket, the IRC bridge for your channel now works, so either there or on #joinmarket we can talk through what might be wrong. I will drop a few notes here though:

First, please use this PR since I was testing it, when I encountered this issue (and our current code in master is wrong):

https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/713

For regtest testing, your config should be ~ like what is seen in the `test/regtest_joinmarket.cfg` file. If you want a separate regtest setup from your mainnet setup, you can pass `--datadir=.` to any script (including `joinmarket-qt.py`) to tell it to pick up the `joinmarket.cfg` in that directory rather than the default `~/.joinmarket`.

An error in loading wallet:
JM-Qt has a particular foible about testnet or regtest wallets.
If you  use command line nothing will be strange: you can generate `python wallet-tool.py generate`, you can then run the payjoin receiver: `python receive-payjoin.py -m1 yournewwallet.jmdat 0.25` and it will spit out the BIP21 URI. (i think this is easier for your case).

If you use Qt though, wallets for regtest are just controlled with a hex seed. Usually these are created on the fly for more automated tests, but you can just enter one (click Generate and it will ask for a hex seed of 16 bytes/32 chars).
(and uh yes we should fix this for more general testing scenarios!)

There is more detail in `docs/TESTING.md` but I think *most* of that isn't too relevant to you.

**Comment by NicolasDorier** [comment] 2020-10-24 03:13
>  But I also don't think that either parameter should be set, if there is no change output

Yes, this is fixed next release. Pinging @lontivero probably wasabi has same issue.
That said, I think you should be as flexible as possible and just ignore instead of rejecting in this case. As the robustness principle says `Be conservative in what you send, be liberal in what you accept`.

Thanks for the details of the repro, this is probably a bug in the "sign with mnemonic" method that I need to fix. Looking to it now.

**Comment by NicolasDorier** [comment] 2020-10-24 06:34
@AdamISZ I could not replicate your bug the change not having the keypaths on our master, it is possible it has been solved, though I don't see how.

Since this is a separate issue than the title of this issue, I will close this issue as "solved", as now we will not send the `maxadditionalfeecontribution` if there is not change.
But I highly advise you to just ignore it instead of aborting the payjoin on your side.

If you want to play with payjoin, your steps of manually copy/pasting an xpub is a bit painful, instead I advise you to 
`Import from ... a new/existing seed". This is easier, this will just work.

**Closed** 2020-10-24 06:35 UTC

**Comment by AdamISZ** [comment] 2020-10-24 08:32
I have spent a full day figuring out how to set up btcpayserver locally in a dev environment and get a workflow so that I can pay joinmarket on the same machine on regtest (I may have found another bug in that process, but it's very obscure and perhaps not, just explaining why it took so long). It's now working so I will investigate. There must be some reason for this.

> `Import from ... a new/existing seed". This is easier, this will just work.

Indeed it does "just work", but only if that option is enabled by Server admin, which I am now doing in the dev environment mentioned above.
I'd appreciate it if you could outline what conceivable, possible causes there are for this problem.

> But I highly advise you to just ignore it instead of aborting the payjoin on your side.

I don't agree, because I think it violates the BIP to send only one of these parameters, although the text does not make it perfectly clear:

""Note that both maxadditionalfeecontribution= and additionalfeeoutputindex= must be specified and valid for the receiver to be allowed to decrease an output belonging to the sender. This fee contribution can't be used to pay for anything else than additional input's weight."

**Comment by AdamISZ** [comment] 2020-10-24 08:57
I mean OK, we can just ignore it. But I don't like processing a request from a client that doesn't seem to follow the protocol as defined in payjoin v1 (it seems like the document in two separate places says that both parameters should be sent, if either are).

**Comment by NicolasDorier** [comment] 2020-10-24 11:29
@AdamISZ as I said, we fixed it so next release we will not specify on `maxadditionalfeecontribution`. I am just suggesting to not be too strict in what you accept to make the life easier for future implementers as well.

**Comment by NicolasDorier** [comment] 2020-10-24 11:31
@AdamISZ if you can do a step by step repro, of when it happen, with btcpayserver on master, I can try to reproduce.

But I tried what you said: Copy an xpub in btcpayserver, go to wallet settings and setup only the account key path, then "sign with the seed", and I got a change as expected.

**Comment by NicolasDorier** [comment] 2020-10-24 11:33
> If the additionalfeeoutputindex is out of bounds or pointing to the payment output meant for the receiver, the receiver should ignore the parameter. See fee output for more information.

**Comment by AdamISZ** [comment] 2020-10-24 11:34
Yeah. I am struggling to reproduce it (ie I can't, yet ...) .. i tried a couple txs on regtest, so far, and it "just works". So I think practically I have to agree with your point of view on this. 

Maybe it's something to do with high fees (pure guess, just wondering if there might be a mainnet delta). (just to clarify: the mainnet cases I saw did have change. they just didn't specify additionalfeeoutputindex).

**Comment by AdamISZ** [comment] 2020-10-24 11:34
It won't be very interesting but I did at least document how I set up the test: https://gist.github.com/AdamISZ/32b948bb1c725ce12230001c503df401

**Comment by NicolasDorier** [comment] 2020-10-24 11:38
@AdamISZ the mainnet case you saw was transactions you did yourself? Because there might be some corner case if for example you asked btcpay to sign a PSBT directly rather than using the `Send Wallet` feature.

**Comment by AdamISZ** [comment] 2020-10-24 11:43
Yeah I did myself with the 'sign with seedphrase' option. I used `mainnet.demo.btcpayserver.org` (iirc that's the URL)

**Comment by AdamISZ** [comment] 2020-10-24 11:44
Hmm I see now I should have written more detail on the btcpayserver side setup. Something about that wallet set up could indeed be the reason.

**Comment by NicolasDorier** [comment] 2020-10-24 12:34
@AdamISZ 
in your step 12)

`Use the tools in BTCPayServer.Tests to add funds to that wallet:` Actually we have scripts inside so you don't have to do some complicated command line.

`docker-bitcoin-cli.sh` and `docker-bitcoin-generate.sh`

**Comment by AdamISZ** [comment] 2020-10-24 12:39
Yes I know. the generate command didn't work for some mysterious reason, that's why I unpacked it. The bitcoin-cli script did though, and I used it. Thanks for actually reading it :)

**Comment by AdamISZ** [comment] 2020-10-24 12:39
Oh I remember now, it said invalid address .. it was really weird. when i did each step inside the script, with the same address it worked. No idea.
