### ISSUE TITLE
Connection unexpectedly failed: Unexpected exception while connecting to socket

### ISSUE THREAD

**Issue by bereska** [btcpayserver/btcpayserver#777] opened 2019-04-21 04:36 UTC
**Describe the problem/bug**
Connection unexpectedly failed: Unexpected exception while connecting to socket in NBXplorer logs
getting "Your Nodes are syncing" warning on https://btcpay.bereska-lnd.duckdns.org from time to time
looks like NBXplorer is struggling to catch up and falls behind
is it because rpi 3+ 1 Gb RAM is too little for this stack?
I see bitcoind and lnd take up to 30% of memory each

**Your environment**
Raspiblitz 1.1 on rpi 3b+ with:
lnd version 0.5.2-beta commit=v0.5.2-beta
Bitcoin Core Daemon version v0.17.0.1
Manually installed:
dotnet 2.1.505
NBXplorer latest
BTCPay server v.1.0.3.92

**Logs (if applicable)**
admin@bereskaLND:~ $ sudo systemctl status nbxplorer
● nbxplorer.service - NBXplorer daemon
Loaded: loaded (/etc/systemd/system/nbxplorer.service; enabled; vendor preset: enabled)
Active: active (running) since Fri 2019-04-19 01:32:00 BST; 16h ago
Main PID: 10248 (dotnet)
CGroup: /system.slice/nbxplorer.service
└─10248 /usr/local/bin/dotnet /home/admin/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll -c /home/admin/.nbxplorer/Main/settings.config

Apr 19 18:19:57 bereskaLND dotnet[10248]: info: Explorer: BTC: Handshaked node
Apr 19 18:20:24 bereskaLND dotnet[10248]: fail: Explorer: BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:24 bereskaLND dotnet[10248]: info: Explorer: BTC: Starting scan at block 572322
Apr 19 18:20:25 bereskaLND dotnet[10248]: info: Explorer: BTC: Handshaked node
Apr 19 18:20:27 bereskaLND dotnet[10248]: fail: Explorer: BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:28 bereskaLND dotnet[10248]: info: Explorer: BTC: Starting scan at block 572322
Apr 19 18:20:29 bereskaLND dotnet[10248]: info: Explorer: BTC: Handshaked node
Apr 19 18:20:30 bereskaLND dotnet[10248]: fail: Explorer: BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:30 bereskaLND dotnet[10248]: info: Explorer: BTC: Starting scan at block 572322
Apr 19 18:20:31 bereskaLND dotnet[10248]: info: Explorer: BTC: Handshaked node

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by pavlenex** [comment] 2019-04-21 06:34
This appears to be a duplicate of the issue posted in [Nbxplorer repository.](https://github.com/dgarage/NBXplorer/issues/170#).

I'll mark this one as `closing` since you're already getting help in that issue over there.

**Comment by bereska** [comment] 2019-04-21 06:35
thank you

**Closed** 2019-04-22 05:31 UTC
Labels: Closing, Deployment
