### ISSUE TITLE
DOGE won’t sync at all, all other coins work.

### ISSUE THREAD

**Issue by SplatDev** [btcpayserver/btcpayserver#2824] opened 2021-08-31 00:05 UTC
**Describe the bug**
Dogecoin won't sync

**To Reproduce the bug**
Install DOGE as an alt coin and wait for it to attempt to sync.

**Expected behavior**

DOGE to accept payments

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    Latest
- Deployment Method:       
Docker
- Browser:
Brave (shields down)

**Additional context**

Running on its own dedicated IP, nothing else is on the VPS. The VPS runs Ubuntu 18.04

**Comment by SplatDev** [comment] 2021-08-31 00:07
Reposted as I think I messed up the first one, it got instantly closed as I messed up the comment. If it turns out this is against bug report rules just remove it

**Comment by pavlenex** [comment] 2021-08-31 00:10
This isn't nearly as enough info to troubleshoot your issue or consider this a bug reprort. Please look through our [troubleshooting guide](https://docs.btcpayserver.org/Troubleshooting/) and provide all necessary information including the logs.

Having to many altcoins can mess up your sync that's for sure. Altcoins are maintained by outside community and we can't really help you with them, best it to join chat.btcpayserver.org and ask in an appropriate altcoin channel for assistance.

**Comment by SplatDev** [comment] 2021-08-31 00:19
I looked through logs and found nothing related to the issue. Here's an image of the issue though. If not this then it shows node is starting but it never starts. I've tried deleting blockchain data and starting from scratch but that didn't work.
![image](https://user-images.githubusercontent.com/47852941/131421885-02b2ab3a-300e-4a71-80fd-94c6f4e3c644.jpeg)

**Comment by SplatDev** [comment] 2021-08-31 00:28
Ok ignore a bit of that, I found logs
```

{
  "chain": "main",
  "blocks": 3876871,
  "headers": 3876871,
  "bestblockhash": "b91a3a4651642ff50abe1b1de3adaf2468c4ffa21c02fc906c434d2b80a569ca",
  "difficulty": 4251851.760920678,
  "mediantime": 1630369314,
  "verificationprogress": 0.9999998290135617,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000000005a4dc9806157f05fb3e",
  "size_on_disk": 5180846518,
  "pruned": true,
  "pruneheight": 3559170,
  "automatic_pruning": true,
  "prune_target_size": 5242880000,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    }, 
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    }, 
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "failed",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 1703520
    }
  },
  "warnings": ""
}
```

**Comment by bolatovumar** [comment] 2021-09-05 18:51
ping @astupidmoose, our Dogecoin expert

**Comment by astupidmoose** [comment] 2021-09-05 18:55
![Screenshot_20210905-115504_Mattermost.jpg](https://user-images.githubusercontent.com/3916318/132138233-fad0fd73-cb12-4c5a-a37e-4fab48918d5f.jpg)

I have no idea... Lol 

This was in the chat at some point, maybe it'll help?

**Comment by SplatDev** [comment] 2021-09-05 21:05
> ![Screenshot_20210905-115504_Mattermost.jpg](https://user-images.githubusercontent.com/3916318/132138233-fad0fd73-cb12-4c5a-a37e-4fab48918d5f.jpg)
> 
> I have no idea... Lol 
> 
> This was in the chat at some point, maybe it'll help? 

I don't actually know what bootstrap is for Dogecoin sadly. Do you know what it is and how to use it? Sorry if this question is stupid.

**Comment by astupidmoose** [comment] 2021-09-05 21:07
I do not, as I haven't used it. Maybe try asking on the BTCpay chat in the Dogecoin channel. 

I'm not a dev, so I really have no idea. Dogecoins been working for me flawlessly for years so I haven't really needed to worry.

**Comment by SplatDev** [comment] 2021-09-05 21:14
Alright I'll see if they have any info.

**Comment by pavlenex** [comment] 2021-09-06 08:48
It's been mentioned that doge requires more ram, so try with a higher specs VPS if you already don't have one, at least 4GB or something.

**Comment by SplatDev** [comment] 2021-09-06 11:20
> It's been mentioned that doge requires more ram, so try with a higher specs VPS if you already don't have one, at least 4GB or something.

My VPS has 4 cores and 12GB RAM

**Comment by yannik995** [comment] 2021-09-08 06:07
Hi there,
I have the same problem, however, I see an error message in the Docker logs hundreds of times every few minutes, but can't do much with this one.
In any case, it occurs every time, even if I delete the block data and rebuild it.

>docker logs -n100 -t btcpayserver_dogecoind
`2021-09-08T06:03:21.929878412Z 2021-09-08 06:03:21 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)`

**Comment by vasu2628** [comment] 2021-09-13 06:45
please release 1.14.4 version

**Comment by SplatDev** [comment] 2021-09-17 16:46
Any updates on this? I still have my issue

**Comment by yannik995** [comment] 2021-10-05 12:52
Dogecoin's Docker Fragment has been updated to 1.14.4: (https://github.com/btcpayserver/btcpayserver-docker/pull/533)
Therefore it should work now after an update, but currently I cannot test it.

**Comment by skwp** [comment] 2021-12-09 04:49
altcoins are an attack on btcpayserver's team's time. pavlenex shouldn't have to answer github tickets about doge. terminate all related code with extreme prejudice and save precious time! Just my two sats.

**Comment by Kukks** [comment] 2021-12-09 05:16
> altcoins are an attack on btcpayserver's team's time. pavlenex shouldn't have to answer github tickets about doge. terminate all related code with extreme prejudice and save precious time! altcoiners can fork the project and maintain it as needed. Just my two sats.

We've been through these discussions before. We use minimal effort on these issues and don't focus on them at all.

**Comment by vasu2628** [comment] 2021-12-11 17:36
No issues with the sync @SplatDev . You might need to open the port 22555,22556 from the instance

**Comment by astupidmoose** [comment] 2021-12-11 18:05
It's been suggested to use https://bootstrap.sochain.com/ as a method of bootstrapping the chain. 

I have not used this myself and offer no warranty this works, use at own risk, but others say it works.

**Comment by vasu2628** [comment] 2021-12-13 01:22
Hi @astupidmoose  could you please release doge 1.14.5 when possible ?

**Comment by astupidmoose** [comment] 2021-12-13 04:41
> Hi @astupidmoose could you please release doge 1.14.5 when possible ?

Honestly, it's not a priority and might take me a couple weeks/months to get around to it. Anyone else who'd like to is open to updating.

**Comment by nosovk** [comment] 2022-01-06 10:49
hm currently there are no issues with doge, but we use their official image

**Comment by pavlenex** [comment] 2022-01-09 17:07
Closing this as a duplicate of #904 It seems there are quite often sync problems with altcoins. But very little efforts from their communities to investigate or fix it.

**Closed by pavlenex** 2022-01-09 17:07 UTC
Labels: Altcoin, need-info
