### ISSUE TITLE
[Feature Request] Facilitate Sales of Digital Goods

### ISSUE THREAD

**Issue by SeedSigner** [btcpayserver/btcpayserver#4786] opened 2023-03-18 22:39 UTC
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4785

<div type='discussions-op-text'>

<sup>Originally posted by **SeedSigner** March 18, 2023</sup>
I first proposed this concept in the BTCPay Telegram community and was asked to post it here as well as a Feature Request. The concept is for users to be able to sell digital goods using a BTCPay instance without the need for any other infrastructure. My specific use case is to sell 3D-printable .stl models but other content creators may have an interest in selling images, videos, audio files, documents or other digital media. Ideally a user would be able to upload a digital file to the BTCPay server, set a price, and create a checkout flow that makes sense for a given item. Once buyers have selected and paid for an item, they would be presented with a one-time or expirable download link for the purchased item. I am personally excited about the v4v possibilities that this feature could open up for digital content creators.

(For context, this was a response to my question in the Telegram community: "Actually we have the primitives in place for this. We have the file system which can generate unique expirable links for each file, a receipt page that can show such links when an invoice is settled, and a pos app that has a json item template that could arbitrarily hold a file ID that gets unlocked when an invoice for it gets paid. Please open a feature request so everything gets glued together!")</div>

**Comment by pavlenex** [comment] 2023-03-20 09:26
Duplicate of a discussion, since we have a discussion, until the feature is voted, closing this one.

**Closed by pavlenex** 2023-03-20 09:26 UTC
