### ISSUE TITLE
[Bug]: Lightning Address: LNURL-p comments aren't being embedded into the payment request memo

### ISSUE THREAD

**Issue by kaloudis** [btcpayserver/btcpayserver#4801] opened 2023-03-21 22:48 UTC
### What is your BTCPay version?

v1.7.11

### How did you deploy BTCPay Server?

Extended manually - but applies to all instances

### What happened?

LNURL-p comments aren't being embedded into the payment request memo.

Comments from LNURLp payments to lightning addresses in BTCPay server are not recording the comment to the memo as the should. The comment can be looked up within BTCPay Server in a different field but clients connecting to their lightning nodes remotely over RPC or REST will not be able to see them.

Instead, they see an object structure that includes the server user's lightning address and default memo on their store. This information is not useful and the UX could be greatly improved if it was replaced with the comment content.

### How did you encounter this bug?

Connect my BTCPay server to Zeus

(image courtesy Finch)

![image](https://user-images.githubusercontent.com/1878621/226758631-9608cb09-0a6f-4b8a-a2b7-31085079b487.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment] 2023-03-22 05:53
> Comments from LNURLp payments to lightning addresses in BTCPay server are not recording the comment to the memo as the should.

Is there anything in the specs that states this? We can look into changing it, but to me this seems to be more like a convention than a specified behaviour. https://github.com/lnurl/luds/blob/luds/12.md

Thoughts, @Kukks?

**Comment by Kukks** [comment] 2023-03-22 06:46
> > Comments from LNURLp payments to lightning addresses in BTCPay server are not recording the comment to the memo as the should.
> 
> Is there anything in the specs that states this? We can look into changing it, but to me this seems to be more like a convention than a specified behaviour. https://github.com/lnurl/luds/blob/luds/12.md
> 
> Thoughts, @Kukks?

It's not in the spec, this seems like a specific implementation flavor of doing things. On our end it could be quite tricky to do this right but we can check it out. But this is not a bug

**Comment by hsjoberg** [comment] 2023-03-22 10:09
The [LUD-12](https://github.com/lnurl/luds/blob/luds/12.md) `comment` field is actually not committed to the invoice desc hash, like `metadata` is.

FYI, it's possible to create new payerid type `comment` to [LUD-18](https://github.com/lnurl/luds/blob/luds/18.md), which would give us strong bindings between the invoice and the comment.
But this requires some effort.

**Comment by Lizotte37l** [comment] 2023-04-09 09:06
Can't withdraw from my account because of this

**Closed** 2023-04-19 13:20 UTC
Labels: Lightning
