### ISSUE TITLE
[Bug]: Fail to archive pull payment (405 method not allowed)

### ISSUE THREAD

**Issue by sebastianwestberg** [btcpayserver/btcpayserver#5531] opened 2023-12-03 15:07 UTC
### What is your BTCPay version?

BTCPay Server v1.11.7+a921504bc 

### How did you deploy BTCPay Server?

Docker

### What happened?

I get an error: 
405 - Method Not Allowed

A generic error occurred (HTTP Code: 405)

### How did you encounter this bug?

1. Create a pull payment
2. Press "archive" for the new pull payment (shown in a list)
3. Press "archive" in "Do you really want to archive the pull payment?" prompt

### Relevant log output

```shell
Nothing relevant in the logs.
```

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment] 2023-12-04 13:02
Are you using a specific role for this? I assume this might have been fixed in #5502, because on master I cannot reproduce this with the standard role.

**Comment by dennisreimann** [comment] 2023-12-04 13:30
Ok, this will be fixed in v1.12 then.

**Closed** 2023-12-18 10:20 UTC
