### ISSUE TITLE
New Invoice API

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#189] opened 2018-05-24 06:34 UTC
Get a cleaner invoice API not burdened by bitpay legacy.

**Comment by Kukks** [comment] 2018-05-24 07:17
Some points from the top of my head:

- No concept of a fiat currency
- Notifications 
  - Possibly remove notification url?
  - Web hooks integration
  - Signalr Invoice Notification Hub
- A list of all payment methods available for this invoice
  - Rate to invoice source currency code
  - Able to toggle which payment methods can or should be used(e.g. only allow btc payments)
  - All the data needed to create your own payment UI( to treat Btcpay as a headless payment gateway)
- A list of all payments made toward this invoice

**Comment by NicolasDorier** [comment] 2018-05-24 08:27
Maybe let's start by a cleaner GET `invoices/{id}` ? this seems the more urgent.

**Comment by Kukks** [comment] 2018-05-24 09:43
How would we handle bitpay support?

**Comment by NicolasDorier** [comment] 2018-05-24 09:51
The new API would requestion `API-Version` http header.
I would like to keep the same URL for the UI and API.

**Comment by danielalexiuc** [comment] 2018-06-11 05:10
How about something like the Lightning Charged API:

https://github.com/ElementsProject/lightning-charge

GET /invoice/:id
POST /invoice
POST /invoice/:id/webhook

That would be plenty to start with!

**Comment by NicolasDorier** [comment] 2018-06-14 11:17
Lightning-Charge API is a lightning related API, not payment processor related.

I am open at any API, if someone just document it or make a swagger with it we can review it.

**Comment by ndeet** [comment] 2018-06-27 21:23
Did not dig into this deeply but the BitPay API is really pita. 
I stumbled about some cleaner looking api from Globee when checking their site after their LightningNetwork support announcement:

https://globee.com/docs/payment-api/v1

Did not check it in detail but it looks more thought through than BitPay at first sight.

**Comment by lclc** [comment] 2018-07-05 14:52
We are currently working on a **open source mobile PoS app for BTCPay** and I'd prefer building it on a new API instead of the less-than-optimal Bitpay API.

I just discussed the new API a bit with @NicolasDorier at the BoB conference. A few points from that discussion:

- Same paths for API calls, use HTTP Header field instead (as mentioned in https://github.com/btcpayserver/btcpayserver/issues/189#issuecomment-391656597)
- Buyer information not needed
- Otherwise the same fields as those visible on the web (http://btcpay-server-testnet.azurewebsites.net/invoices/create)

I think starting with a as simple as possible API and then add more fields and features as needed would be the best approach.
All we need for our app (and I imagine is for many others the same) is:

- Creating Invoice
- Getting Invoice
- Websocket Notification

Does anyone have plans and capacity to implement a new API ?
We don't have a C# developer in our team unfortunately, but we're happy to help with feedback and testing.

**Comment by lclc** [comment] 2018-07-05 15:38
@shesek that API looks good to me. Pretty clean. Maybe a good starting point.

The only thing missing is the websocket specific for an invoice. I don't want to get notified on all payments, just for may specific invoice with the POS.

**Comment by rockstardev** [comment] 2018-07-05 18:04
@lclc I'll help you guys out as I have time... @jimmymow is working on similar thing so we can go for robust implementation from day 1.

**Comment by shesek** [comment] 2018-07-05 20:37
@lclc that's what the [`GET /invoice/:id/wait`](https://github.com/ElementsProject/lightning-charge#get-invoiceidwaittimeoutsec) endpoint is for (but using http long polling rather than websockets).

@NicolasDorier its definitely not usable as-is, just possibly a good starting point. But note that Lightning Charge does take a `webhook` argument when creating invoices (currently [undocumented](https://github.com/ElementsProject/lightning-charge/issues/39)), and has a built-in redirect-based checkout page that reads the redirect URL from `metadata.checkout.redirect_url` (see [example usage here](https://github.com/ElementsProject/nanotip/blob/a309a430d139ac42f39ae1d4dff518c9eaf46138/nanotip.js#L42), and a live instance where you can see the payment flow [here](https://tip.p2sh.info/)).

**Comment by johnnyasantoss** [comment] 2018-08-22 21:30
Hey! 👋 

I'm new here but I would like to share some thoughts about this API Versioning attempt.
I agree with some thoughts like what @Kukks proposed [here](https://github.com/btcpayserver/btcpayserver/issues/189#issuecomment-391614083) but also I agree with @lclc said 
> I think starting with a as simple as possible API and then add more fields and features as needed would be the best approach.

But I don't think that the best approach for API versioning should be a http header as it is not as clear as a URI is. Another problem with this kind of versioning would be that we would lose the conformity with Bitpay API which is not good because it would create a big barrier to people that want to migrate (they would need to search in docs and it would not be easier than just change the base url for all their API calls);
BTW I'm not saying that we should be attached forever in their API specification I'm just trying to say that we probably would want to have a version of this API that conforms with it and another that is ready for modifications and innovation.

From this project readme:
> BTCPay Server is an Open Source payment processor, written in C#, that conforms to the invoice API of Bitpay. This allows easy migration of your code base to your own, self-hosted payment processor.

We can commit ourselves to maintain a version with conformity to Bitpay API using a URI like `btcpayserver/api/bitpay/` or `btcpayserver/api/v1/` and work without fear in our new APIs in another route `btcpayserver/api/v{i}/` this would only require to conform one part of the controllers with Bitpay and unleash our creativity in others routes 😄 

More thoughts about API versioning [here](https://stackoverflow.com/questions/389169/best-practices-for-api-versioning)

@lclc 
> Does anyone have plans and capacity to implement a new API ?

I'm planing to help in this project and I have a few years of experience with .NET :) but first I'll help in minor issues to grab a felling about how things are done around here 🤔 
BTW I'm also developing an open source mobile APP to use as a Bitcoin POS ;)

**Comment by NicolasDorier** [comment] 2018-08-23 01:58
> We can commit ourselves to maintain a version with conformity to Bitpay API using a URI like btcpayserver/api/bitpay/ or btcpayserver/api/v1/ 

We can't do that without breaking existing codebase or taking additional assumption on what existing libraries can do.

**Comment by NicolasDorier** [comment] 2018-08-23 01:59
That said, for the new API, this seems reasonable to do this.

**Comment by Kukks** [comment] 2018-08-23 04:51
@NicolasDorier  I was thinking more along the lines of introducing the bitpay api under btcpayhost.com/api/v1.0/stores/{storeId}/bitpay. 
All stores using the base url via a bitpay client need to have their actions redirected to the associated sub api below to avoid breakijng anything

`
POST btcpayhost.com/api/v1.0/connect/token

GET btcpayhost.com/api/v1.0/users
POST btcpayhost.com/api/v1.0/users
GET btcpayhost.com/api/v1.0/users/{userId}
PUT btcpayhost.com/api/v1.0/users/{userId}
DELETE btcpayhost.com/api/v1.0/users/{userId}

GET btcpayhost.com/api/v1.0/stores
POST btcpayhost.com/api/v1.0/stores 
GET btcpayhost.com/api/v1.0/stores/{storeId}
PUT btcpayhost.com/api/v1.0/stores/{storeId}
DELETE btcpayhost.com/api/v1.0/stores/{storeId}

GET btcpayhost.com/api/v1.0/stores/{storeId}/wallets
GET btcpayhost.com/api/v1.0/stores/{storeId}/wallets/{walletId}
GET btcpayhost.com/api/v1.0/stores/{storeId}/wallets/{walletId}/transactions
POST btcpayhost.com/api/v1.0/stores/{storeId}/wallets/{walletId}/send

GET btcpayhost.com/api/v1.0/stores/{storeId}/rates
GET btcpayhost.com/api/v1.0/stores/{storeId}/rates/{currencyPair}
GET btcpayhost.com/api/v1.0/stores/{storeId}/rates
GET btcpayhost.com/api/v1.0/stores/{storeId}/rates

GET btcpayhost.com/api/v1.0/stores/{storeId}/invoices
WS btcpayhost.com/api/v1.0/stores/{storeId}/invoices/events
POST btcpayhost.com/api/v1.0/stores/{storeId}/invoices/
GET btcpayhost.com/api/v1.0/stores/{storeId}/invoices/{invoiceId}
WS btcpayhost.com/api/v1.0/stores/{storeId}/invoices/{invoiceId}/events
PUT btcpayhost.com/api/v1.0/stores/{storeId}/invoices/{invoiceId}
DELETE btcpayhost.com/api/v1.0/stores/{storeId}/invoices/{invoiceId}

GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay
GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/rates
GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/rates/{baseCurrency}
GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/rates/{baseCurrency}/{currency}

POST btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/tokens

GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/invoices
POST btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/invoices
GET btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/invoices/{invoiceId}
DELETE btcpayhost.com/api/v1.0/stores/{storeId}/bitpay/{invoiceId}
`

**Comment by NicolasDorier** [comment] 2018-08-23 05:04
We can't assume their httpclient make transparent redirection

**Comment by Kukks** [comment] 2018-08-23 08:26
Updated https://github.com/btcpayserver/btcpayserver/issues/189#issuecomment-415290004

**Comment by lclc** [comment] 2018-08-23 08:39
> I'm planing to help in this project and I have a few years of experience with .NET :) but first I'll help in minor issues to grab a felling about how things are done around here 🤔

That's great to hear.

The new proposed API versioning from @Kukks looks good to me. Using the URI makes most sense and is easier (also more convenient to call from command line).

**Comment by NicolasDorier** [comment] 2018-08-24 09:38
Seems cool!

**Comment by rockstardev** [comment] 2018-09-18 16:11
So me and @Kukks talked today - PayButton now already uses `/api/v1/invoices` path because of this change: https://github.com/btcpayserver/btcpayserver/commit/0d3364b3dadfc4a2af65b472b40d1e95587d1e8a

Since Kukks is doing redesign of API I would let him decide on final path for existing PayButton... if it should point to legacy style (`/pay-lala/{storeId}`) or new style (`/api/v1/...`). Seems we will need breaking change either way since proposed path is `POST btcpayhost.com/api/v1.0/stores/{storeId}/invoices/`.

**Comment by Xethron** [comment] 2018-09-20 11:35
There is no point in adding minor versions to an api route. If an additional optional field gets added and does not break backwards compatibility, why should a new route be defined? It also makes it sound like there would be a new version out every week.

I would recommend something more like `GET btcpayhost.com/api/v1/users`. If a minor update was made, it can be added to the current route. Only breaking changes would move it to `v2`.

Just my 2c :)

**Comment by Kukks** [comment] 2018-09-20 13:15
@Xethron That's fair enough. Most likely we would not have used  the minor versioning parts. It was merely a suggestion that I picked up from the  .Net Core Api Versioning lib: https://koukia.ca/api-versioning-in-asp-net-core-2-0-1b55970aa29d

**Comment by gerbz** [comment] 2018-12-26 19:35
I have an immediate need for CRUD commands via API for /users, /stores, /payment-methods and /wallets so I'm glad to see discussion and proposals here - anyone working on this?

**Comment by Kukks** [comment] 2018-12-26 19:37
Immediate need? Contact me in slack, we have a super early preview with an
API

**Comment by j-chimienti** [comment] 2019-09-29 17:17
What is the endpoint for rates?

**Comment by j-chimienti** [comment] 2019-09-29 17:36
What is the API route for rates?

None of these work

GET /rates
GET /stores/{storeId}/rates
GET /stores/{storeId}/rates/BTC
GET /stores/{storeId}/rates/BTC_USD

**Comment by justinmoon** [comment] 2020-01-21 00:25
It would be nice if "metadata" could be an arbitrary structured field like [Stripe's API](https://stripe.com/docs/api/metadata)

**Comment by NicolasDorier** [comment] 2020-01-21 08:03
@justinmoon we already have this: The `posData`

**Comment by NicolasDorier** [comment] 2020-01-21 08:03
ah sorry out of the loop, this is for the new api :p

**Comment by pavlenex** [comment] 2020-02-24 09:59
Closing this as a duplicate of #1320, anyone interested in API features improvement, join the fun there.

**Closed by pavlenex** 2020-02-24 09:59 UTC
Labels: API, Invoice, New Feature
