### ISSUE TITLE
Invoice page - Dropdown magically disappears 

### ISSUE THREAD

**Issue by trigger67** [btcpayserver/btcpayserver#3167] opened 2021-11-30 14:16 UTC
**Describe the bug**
In the invoice page, the "pay with" dropdown disappears !

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Generate an invoice, on a shop accepting more than one method of payment, like Bitcoin on-chain and lightning (try NicolasDorier donation page)
2. On the invoice payment page, click on the dropdown to select either BTC or Lightning
3. Then click on one of the two, but click on the right, on the "BTC" text (click on the span tag)

Tada, the drowdown disappears, and your choice has not been taken into account

- BTCPay Server Version: 1.3.6
- Browser: chromium

![image](https://user-images.githubusercontent.com/10185784/144065386-18833117-2a5b-4377-a54c-bb62508cfebf.png)

**Comment by trigger67** [comment] 2021-12-01 19:10
I will do a pull request to fix it.

**Comment by dennisreimann** [comment] 2021-12-03 15:43
@trigger67 Thanks for the contribution!

I think the proper way to fix it is to change the JS, so that we don't have to exclude single elements within the payment method via CSS. Here's what works for me in the `checkout.js`, can you double-check and if it works adapt the change here?

```js
delegate('click', '.payment-method', e => {
    const el = e.target.closest('.payment-method')
    closePaymentMethodDialog(el.dataset.paymentMethod);
    return false;
})
```

**Comment by trigger67** [comment] 2021-12-06 19:49
@dennisreimann I agree your code is cleaner, but the UX is a bit worse.
With my solution, when selecting an element, the dropdown disappears with a nice transition.
With your solution, it "freezes" a bit, and then the screen is refreshed (you can see it scrolls to the top of the screen).

Maybe there is a way to do it without affecting the UX in javascript...

**Comment by dennisreimann** [comment] 2021-12-06 19:50
Oh sorry, I haven't checked – need to take another look, there's a proper way to solve this with the Js approach, I must have made a mistake here.

**Comment by dennisreimann** [comment] 2021-12-07 21:31
Hmm, I just checked and as far as I can see this is working properly and as expected. I don't get a page refresh, the dropdown fades out and the chosen payment method is set.

**Comment by NicolasDorier** [comment] 2021-12-08 04:42
@trigger67 the bug of the page refreshed happened before, but not too long ago (should have been fixed in 1.3.6 already)
I can't reproduce either. Are you sure the server is updated?

**Comment by trigger67** [comment] 2021-12-08 08:37
@NicolasDorier @dennisreimann my bad I did a mistake, I checked again and it is working fine with the js code.
I will update the pull request later today!
Thank you

**Comment by NicolasDorier** [comment] 2021-12-12 06:06
Fixed on https://github.com/btcpayserver/btcpayserver/pull/3169

**Closed by NicolasDorier** 2021-12-12 06:06 UTC

**Comment by NicolasDorier** [comment] 2021-12-14 03:15
Making 1.3.7 today with this fix
