### ISSUE TITLE
Cannot Remove Store

### ISSUE THREAD

**Issue by conscott** [btcpayserver/btcpayserver#1226] opened 2019-12-17 16:11 UTC
**Describe the problem/bug**
When attemping to remove a Store on the `/stores` page, clicking "Remove" will reload the page with confirmation "Store successfully deleted" but the Store is still listed. Logs to console show no indication of error.

Removing Apps still works fine. 

**Your environment**
* Version of BTCPay Server: master@ 579e0d2e0973540daa92d67b46c3d290809a2293
* Deployment method: Manual Deploy on Ubuntu 16.04
* Other relevant environment details: Running Sqlite

**To Reproduce**
1. Go to `/stores`
2. Click "Remove" button
3. Accept on "Delete This Store" Page

**Expected behavior**
The Store is removed

**Actual behavior**
The Store is not removed

**Screenshots/Links**

![no_delete](https://user-images.githubusercontent.com/14220652/71012524-2cd65680-20e7-11ea-8d43-a5ed39f7ae5b.gif)

**Comment by bolatovumar** [comment] 2019-12-18 05:23
@conscott I just tried this locally on my machine and it works just fine if I create a store and delete it right away. Are you doing special with the store after creating it and before deleting it?

**Comment by conscott** [comment] 2019-12-18 10:15
Thanks for looking @bolatovumar 

I have put no special settings on the store. I have attached a larger gif a the bottom show I am using a clean build of master, and just simple create/delete does not work. 

I tried doing a full `clean` and also removing the db at `~.btcpayserver/TestNet/`, with no success

![demo2](https://user-images.githubusercontent.com/14220652/71077347-285d7c80-217f-11ea-8b35-2e7cf4a51bdc.gif)

Really curious what is happening here. Any other ideas?

**Comment by Eskyee** [comment] 2019-12-18 23:57
works just fine if I create a store and delete it right away, I too have no problems deleting stores![Screenshot 2019-12-18 at 23 53 21](https://user-images.githubusercontent.com/30862925/71133221-c558fd80-21f1-11ea-9a03-0ef39174af75.png)
![Screenshot 2019-12-18 at 23 53 52](https://user-images.githubusercontent.com/30862925/71133238-ce49cf00-21f1-11ea-8b80-4db59f813f27.png)

I can't reproduce your error

**Comment by Eskyee** [comment] 2019-12-19 00:04
I see your local host port @ 8000, maybe your setup not config so good @conscott just a idea?? I using port 14142 local

**Comment by NicolasDorier** [comment] 2019-12-19 07:26
@conscott the problem is that your deployment is using SQlite.

I did not remove SQLite support but I intend to deprecate it in favor of Postgres.

**Comment by conscott** [comment] 2019-12-19 12:43
Thanks @NicolasDorier 

After inspecting, it looks like the change was quite intentional, I am not sure I got that context from your response. 
bbd19a96ecccbf062926b64478edf5f917e0aba4

I haven't dug into what would need to change to make it work. Looks like it's because `ctx.Database.SupportDropForeignKey` for SQLite is intentionally false but I dont understand any of the context around that. 

Regardless, it looks like this is working 'as expected'? Given commit history. 

If so we can close.

**Comment by conscott** [comment] 2019-12-19 12:47
If anyone has successfully migrated an SQLite store to Postgres, that would also be helpful to know. `pgloader` seems to want to force table names to lowercase, and `quote identifiers` isn't supported for SQLite. I suppose I could manually change the table names after the fact but I still may have trouble.

**Comment by NicolasDorier** [comment] 2019-12-21 11:50
@conscott I think you should not try to migrate and start fresh if you can.

> Looks like it's because ctx.Database.SupportDropForeignKey for SQLite is intentionally false 

This is the migration scripts. Sometimes migrations need to drop foreign keys, but sqlite don't support that.

**Comment by NicolasDorier** [comment] 2020-01-16 07:30
Closing this as we can't fix this issue for SQlite.

**Closed by NicolasDorier** 2020-01-16 07:30 UTC
