### ISSUE TITLE
 expose point of sale and custom form data in the receipt (product, form, tip, discount)

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#4716] opened 2023-02-27 13:05 UTC
Yo, 

Would it be possible to create an abstract view to print usefull data only from invoice page? 

Imagine the following : 
I run a restaurant, with the custom form i now have to power to add table number to invoices, which in theory would make a perfect receipt for the kitchen. If the view printed would show the Custom fields Data + Items ordered only. 

Currently the only way to do this is to print the full invoice and get between 5-6 pages A4 size.. However kitchen printers are 9/10 times thermal receipt printers, this turns into a Loooooong receipt. So the workaround now is to copy all data from invoice view to notepad, dump unnecessary data and send to printer.

**Comment by pavlenex** [comment] 2023-03-03 09:41
So there are two tasks here:

- expose point of sale and custom form data in the receipt
- optimize invoice print view

I think he later is out of scope of this one, and should be a separate issue. Will log it now.

**Comment by pavlenex** [comment] 2023-03-03 09:53
@Bangalisch Is this a duplicate of [#4715](https://github.com/btcpayserver/btcpayserver/issues/4715) now that I separated the issue in two #4729?

**Comment by pavlenex** [comment] 2023-03-07 16:31
Closing as agreed with @Bangalisch

**Comment by ndeet** [comment] 2023-03-15 14:54
Adding to the above it might be useful if we had a textfield that can be filled on store level and gets printed on the receipt, where merchants can enter their legal data (address, vat id, etc.). Afair in some countries this is required.

I know we want to reduce settings but putting it out there so it is considered in the conceptional discussion.

**Comment by Kukks** [comment] 2023-03-15 15:26
We can potentially just have a default Metadata object at store level that
each invoice gets as a base. This allows default receipt data and also
allows default invoice info

**Comment by ndeet** [comment] 2023-03-15 20:56
Interesting, so you can have read-only metadata? Sounds great if it avoids another setting :+1:

**Comment by Kukks** [comment] 2023-03-16 07:46
For the record, I'm opposed to just adding all that data by default to the receipt page, and to have a toggle for each one of that data item.


#4774 fixes this on an API level, but when combined with https://github.com/btcpayserver/btcpayserver/issues/4716#issuecomment-1470243123 , it should be sufficient.

**Closed** 2023-04-05 13:42 UTC
Labels: Receipt
