### ISSUE TITLE
Breaking change 2.0

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#5964] opened 2024-05-01 01:57 UTC
This is documenting the breaking changes for 2.0.

## Pull payments

* Pull payments can't renew automatically through the `period` property anymore (https://github.com/btcpayserver/btcpayserver/pull/5963)
* `POST api/v1/stores/{storeId}/pull-payments`: Rename `PaymentMethods` => `PayoutMethods`
* `GET api/v1/stores/{storeId}/pull-payments/payouts`
  * Added: `originalCurrency` (eg. USD)
  * Renamed: `amount`=>`originalAmount` (eg. 10000 USD)
  * Renamed: `cryptoCode` => `payoutCurrency` (eg. BTC)
  * Renamed: `paymentMethodAmount`=>`payoutAmount` (eg. 0.1 BTC)

## Payment Methods

https://github.com/btcpayserver/btcpayserver/pull/5809
Payment methods id name have been rewritten to be consistent between API and Backend.

* `BTC-OnChain` or `BTC_BitcoinLike` or `BTC-BitcoinLike` or `BTC-BTCLike` -> `BTC-CHAIN`
* `BTC-LightningNetwork` or `BTC_LightningLike` or `BTC_OffChain` or `BTC_Off-Chain`  -> `BTC-LN`
* `BTC-LNURLPAY`->`BTC-LNURL`
* `XMR-MoneroLike`->`XMR-CHAIN`
* `ZEC-ZcashLike`->`ZEC-CHAIN`

Note that it isn't a breaking change for input data to API, as BTCPay will automatically convert the old strings to the new format.
However, data returned by BTCPay API will return the new names.

The API needed to be changed to reflect the fact payment methods doesn't have a PaymentType anymore:

Removed routes:
* `GET /api/v1/stores/{storeId}/payment-methods/LNURL`
* `GET /api/v1/stores/{storeId}/payment-methods/LNURLPay/{cryptoCode}`
* `PUT /api/v1/stores/{storeId}/payment-methods/LNURLPay/{cryptoCode}`
* `DELETE /api/v1/stores/{storeId}/payment-methods/LNURLPay/{cryptoCode}`
* `GET /api/v1/stores/{storeId}/payment-methods/LightningNetwork`
* `GET /api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}`
* `PUT /api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}`
* `DELETE /api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}`
* `GET /api/v1/stores/{storeId}/payment-methods/OnChain`
* `GET /api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}`
* `PUT /api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}`
* `DELETE /api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}`

Modified route:
* `GET /api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods`
  * Renamed `networkFee` to `paymentMethodFee` like with the other endpoints
  * Renamed `cryptoCode` field to `currency`
  * Renamed the `paymentMethod` to `paymentMethodId` field
  * Added `includeSensitive` parameter defaulting to `false`. If `true`, `additionalData` might include sensitive data such as xpub; the permission `btcpay.store.canmodifystoresettings` is required
  
* `GET /api/v1/stores/{storeId}/payment-methods`
  * Removed the `cryptoCode` field
  * Added `paymentMethodId` field
  * Renamed the `data` property to `config`
  * Renamed the query parameter `enabled` to `onlyEnabled`
  * Added `includeConfig` parameter defaulting to `false`. If `true`, the config of the payment method will be returned and the permission `btcpay.store.canmodifystoresettings` is required
* `/api/v1/stores/{storeId}/invoices/{invoiceId}/refund`: The field `paymentMethod` renamed to `payoutMethodId`
* `/api/v1/stores/{storeId}/payout-processors/(LightningAutomatedPayoutSenderFactory|OnChainAutomatedTransferSenderFactory)`: The field `paymentMethod` renamed to `payoutMethodId`
* `/api/v1/stores/{storeId}/payouts`: The field `paymentMethod` renamed to `payoutMethodId`
* `/api/v1/stores/{storeId}`: The field `paymentMethod` renamed to `payoutMethodId`

Added route:
* `PUT /api/v1/stores/{storeId}/payment-methods/{paymentMethodId}`
* `DELETE /api/v1/stores/{storeId}/payment-methods/{paymentMethodId}`
* `GET /api/v1/stores/{storeId}/payment-methods/{paymentMethodId}`

Renamed route:
* `GET api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}/preview` to `api/v1/stores/{storeId}/payment-methods/{paymentMethodId}/wallet/preview`
* `POST api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}/generate` to `api/v1/stores/{storeId}/payment-methods/{paymentMethodId}/wallet/generate`
* Removed properties `cryptoCode` and `paymentMethod` from their response.
* Added property `paymentMethodId`, `config` so the format of `generate` is the same as the `GET /api/v1/stores/{storeId}/payment-methods/{paymentMethodId}`

Rename `/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}/*` to `/api/v1/stores/{storeId}/payment-methods/{paymentMethodId}/wallet/*`.

Webhook change:
* Rename `paymentMethod` field to `paymentMethodId`

Legacy Bitpay API:
* Removal of the `confirmed` state, an invoice directly goes to the `complete` state.

## Apps

Removal of `embeddedCSS`, `customCSSLink` for PaymentRequests, Crowdfund app and PoS app.
Instead, customizations should be done at the store's branding level through `logoUrl`, `cssUrl`, `paymentSoundUrl` and `brandColor`. (https://github.com/btcpayserver/btcpayserver/pull/5947)

## Modal Checkout

* When the Checkout is in modal mode, it posts the message ` { invoiceId, status }` to the parent window. Previously, the status could be `new`, `paid` `complete`, `invalid`, `expired` state. These have been replaced by `New`, `Processing`, `Settled`, `Invalid`, `Expired`.

## Feature

Removal of Checkout v1.

## Boltcard plugin

If you are using boltcard factories, you will need to activate lightning automated payment processor and check the box `Process approved payouts instantly`.

**Comment by dennisreimann** [comment] 2024-05-01 06:28
I think we should turn this into a 2.0 Migration page in the docs once this is done :)

**Comment by nostitos** [comment] 2024-05-06 16:58
Can't wait, What's the ETA on this release?

**Comment by ndeet** [comment] 2024-09-06 10:33
@NicolasDorier I think there is some info missing:
you  write:
> GET /api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods
> Remove the cryptoCode field
> Renamed paymentMethod to paymentMethodId
> Add a currency field

It seems like
- renaming of `cryptoCode` to `currency`?
- you also renamed `networkFee` to `paymentMethodFee` like with the other endpoints

**Comment by ndeet** [comment] 2024-09-06 13:25
@NicolasDorier 
> Legacy Bitpay API:
> Removal of the confirmed state, an invoice directly goes to the complete state.

It likely does not break anything but why did you make that change? Did not hurt how it was before or?

**Comment by NicolasDorier** [comment] 2024-09-08 23:37
@ndeet because initially BTCPay was built on Bitpay's model. Over time, we had our model. In our model there is no concept of `confirmed` versus `complete`. So I removed that out.

**Comment by ndeet** [comment] 2024-09-09 09:33
Makes sense but wasn't there something with the number of confirmations option you can set on bitcoin wallet level? Wasn't it `confirmed` whenever the 1st confirmation arrived but depending on store settings of the "Consider the invoice settled when the payment transaction ..."? When that option is set to 1 conf it would go immediately to settled/complete but if that was set to 6 conf then it would first go to "confirmed" and only after 6 conf to settled? Or do I remember that wrong?

![screenshot-testing_btcpay_tech-2024_09_09-11_29_47](https://github.com/user-attachments/assets/4877075c-a8c8-415b-b381-d74867f14130)

**Comment by NicolasDorier** [comment] 2024-09-19 13:07
Before Complete was always equal to 6 conf. And Confirmed was configurable.
The reason we had Complete was just to keep Bitpay compatibility, which we don't need anymore. There is no logic into why 6 conf is a magic number which signify something more than confirmed.

**Comment by ndeet** [comment] 2024-09-25 14:20
To summarize our dev call about api changes (please correct me if wrong):
- new / changed endpoints will have /v2/ api prefix and deprecated /v1/ will throw an error with more information how to upgrade
- existing endpoints that only have data property changes will return the same properties alongside new properties (will be mapped internally), affected endpoints are all the ones listed in "Modified route:" at the top (mostly about PaymentMethod rename to PaymentMethodId):

-  `/api/v1/stores/{storeId}/payment-methods ` (important for our integrations)
- `/api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods` (important for our integrations)
- /`api/v1/stores/{storeId}/invoices/{invoiceId}/refund`
- `/api/v1/stores/{storeId}/payout-processors/(LightningAutomatedPayoutSenderFactory|OnChainAutomatedTransferSenderFactory)`
- `/api/v1/stores/{storeId}/payouts`
- `/api/v1/stores/{storeId}`

**Comment by ndeet** [comment] 2024-10-09 07:38
@NicolasDorier 

The routes that are low hanging fruits to not break integrations:

`/api/v1/stores/{storeId}/payment-methods`
Old properties missing:
- cryptoCode

A breaking change here is the rename of `data` to `config` which is also only available when you pass `includeConfig`. But at least the returned list of payment methods would be not breaking.

`/api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods`
Old properties missing:
- cryptoCode
- paymentMethod
- networkFee

**Comment by ndeet** [comment] 2024-10-09 07:54
In the opening post documenting the changes there seems to be some errors:
> Modified route:
> 
> * `GET /api/v1/stores/{storeId}/payment-methods`
>   
>   * Renamed `networkFee` to `paymentMethodFee` like with the other endpoints
>   * Renamed `cryptoCode` field to `currency`
>   * Rename the `paymentMethod` to `paymentMethodId` field
>   * Rename the `data` property to `config`
>   * Rename `networkFee` to `paymentMethodFee`
>   * Rename the query parameter `enabled` to `onlyEnabled`
>   * Add `includeConfig` parameter defaulting to `false`. If `true`, the config of the payment method will be returned and the permission `btcpay.store.canmodifystoresettings` is required.
> * `GET /api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods`
>   
>   * Remove the `cryptoCode` field
>   * Renamed `paymentMethod` to `paymentMethodId`
>   * Add a `currency` field


Seems mix up of invoices and store endpoint with the listed changes, should be:

* `GET /api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods`
  * Renamed `networkFee` to `paymentMethodFee` like with the other endpoints
  * Renamed `cryptoCode` field to `currency`
  * Renamed the `paymentMethod` to `paymentMethodId` field
  * Added `includeSensitive` parameter defaulting to `false`. If `true`, `additionalData` might include sensitive data such as xpub; the permission `btcpay.store.canmodifystoresettings` is required
  
* `GET /api/v1/stores/{storeId}/payment-methods`
  * Removed the `cryptoCode` field
  * Added `paymentMethodId` field
  * Renamed the `data` property to `config`
  * Renamed the query parameter `enabled` to `onlyEnabled`
  * Added `includeConfig` parameter defaulting to `false`. If `true`, the config of the payment method will be returned and the permission `btcpay.store.canmodifystoresettings` is required

**Comment by pavlenex** [comment] 2024-10-29 09:33
Closing since this is a tracker, but we can keep discussion and questions going on.

**Closed by pavlenex** 2024-10-29 09:33 UTC
