### ISSUE TITLE
[Bug]: HTTP 500 when generating a BTC address

### ISSUE THREAD

**Issue by rtarnaud** [btcpayserver/btcpayserver#4403] opened 2022-12-05 22:38 UTC
### What is your BTCPay version?

v1.7.1.0+e11a775be

### How did you deploy BTCPay Server?

Docker

### What happened?

When trying to generate a BTC address to receive an on-chain payment, BTCPay server returns a 500 response.
I believe this issue is linked to https://github.com/btcpayserver/btcpayserver/issues/4332.

### How did you encounter this bug?

Bitcoin Wallet > Receive > Generate next available BTC address > Blank page (HTTP 500)

### Relevant log output
Output of `docker logs --tail 100 generated_nbxplorer_1`:

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMMBSTV8UG02", Request id "0HMMBSTV8UG02:0000006D": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 924
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 919
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 845
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 846
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

If I create a wallet as suggested by the error above, the issue persists but this time, the error is:

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMMBSTV8UG01", Request id "0HMMBSTV8UG01:00000058": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: Only legacy wallets are supported by this command
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 924
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 919
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 845
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 846
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Additional information

I am using the testnet "version" of BTCPay server. My Bitcoin wallet was initially a watch-only wallet and the receive function was (and still is) working fine. Later, I decided to replace that wallet by a hot one and came across that bug.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by mbio16** [comment] 2022-12-06 09:44
Might be the bug connected to issue I see in my setup. Manual install with PSQL. Version v1.7.1.0. When I want anything from /wallets after wallet has been created I go HTTP 500. Log from btcpay server sevice:
```
Dec 06 10:25:11 btcpay-server dotnet[1399291]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](I>
Dec 06 10:25:11 btcpay-server dotnet[1399291]:   Exception data:
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     Severity: ERROR
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     SqlState: 42703
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     MessageText: column "AType" does not exist
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     Hint: Perhaps you meant to reference the column "wos.Type".
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     Position: 278
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     File: parse_relation.c
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     Line: 3393
Dec 06 10:25:11 btcpay-server dotnet[1399291]:     Routine: errorMissingColumn
```

**Comment by rtarnaud** [comment] 2022-12-06 11:33
I have found a workaround. When creating the hot wallet, you need to toggle the "Import keys to RPC" option in the advanced settings and then the address generation works.

**Comment by mbio16** [comment] 2022-12-06 12:21
Hi, thanks for reply, but this happens not only with hot wallet also with imported xpub.

**Comment by pavlenex** [comment] 2022-12-09 09:59
@dennisreimann since we included this one into potential 1.7.2, did we manage to replicate and find a root cause of it?

**Comment by NicolasDorier** [comment] 2022-12-13 01:10
hey @rtarnaud can you update it's a bug I should have fixed yestersday?

**Comment by NicolasDorier** [comment] 2022-12-13 01:11
@mbio16 as well can you try ?

**Comment by NicolasDorier** [comment] 2022-12-13 01:13
Can you also run this command on the server

```bash
docker exec -ti generated_postgres_1 psql -U postgres -d nbxplorermainnet
```

Then enter

```sql
UPDATE  nbxv1_metadata SET data='"Descriptors"' WHERE key='ImportAddressToRPC' AND data != '"False"';
```
Then it should fix your exception.

**Comment by NicolasDorier** [comment] 2022-12-13 01:18
@pavlenex @dennisreimann @petzsch this bug was pretty bad and I didn't see it until too late as it happened only on new instance. If people have trouble with this, then redirect to this issue, if they are confused send them to me on mattermost.

**Comment by rtarnaud** [comment] 2022-12-13 12:53
@NicolasDorier 
1. The version I am running (v1.7.1.0+e11a775be) still is the latest one, so I couldn't update.
2. I ran your SQL command and it fixed the bug indeed.

Should I close the issue now?

**Comment by NicolasDorier** [comment] 2022-12-14 06:47
@mbio16 this error should only happen if you did run a version of BTCPay that wasn't tagged as release. Is it the case? How did you deployed btcpay?

**Comment by NicolasDorier** [comment] 2022-12-14 06:50
@rtarnaud if you use our docker deployment, running the update is updating not only BTCPay, but dependencies to BTCPay, and one of the dependencies had this bug.

**Comment by NicolasDorier** [comment] 2022-12-14 06:50
Let's close this issue, @mbio16 if you running a released version of BTCpay, please open different issue.

**Closed by NicolasDorier** 2022-12-14 06:50 UTC
Labels: Bug
