### ISSUE TITLE
[UX improvement] Expired invoices' message can be confusing for newbies

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver#325] opened 2018-10-09 09:52 UTC
I showed the checkout process to a friend of mine that knows very little about Bitcoin or BTCPay, and she was puzzled by the message for expired invoice.

Here is some of her remarks and suggestion : 
* There are 3 paragraphs that look like they are for 3 different cases, but I figured out it's more like 2 possibilities, with the second one having 2 more cases. According to my understanding of this message, it is like this : 
    * If I didn't send any payment ==> I have to go back to the shop site (click on the big button on bottom) and do the checkout again.
    * If I did send a payment : 
        * Either it will eventually be accepted in a few hours and I have nothing to do but wait.
        * Either it will never make it and I'll see my money back in 48 up to 72 hours, depending on the software I'm using
* I see the following problems : 
    * I'd like to have more precise instructions about what I need to do, especially if I already send a payment I'd be nervous about losing my money,
    * It is not a good idea to have the "go back to site" button on the bottom like this, it made me think at first that I need to go back to site regardless of my actual situation (payment sent or not)
    * There's a real possibility that I would have sent a payment again and pay twice for the same order
    * Do I have really to wait up to 72 hours to be sure that my payment was not accepted ? If it happens to me, I'd sure give up and go for another site or payment.

Here is the solution she suggested : 
* Rewrite slightly the 3 paragraphs, so that each one states very clearly one of the possible outcome : 
    * You didn't send any payment ==> Go back to site
    * You did send a payment ==> Do NOT go back to site and checkout again
        * your payment should probably be accepted in a few hours
        * in some rare cases, it might not be accepted, but don't worry it means your money will be back in your wallet in 72 hours max, you can check your wallet software for further information.
* It could be better to either pull the "go back to site" button up to the bottom of the 1st paragraph (you didn't send the payment, so go back to site), or drag this paragraph down to the 3rd position.
* What are the last two pieces of information ("order ID" and "invoice ID") for ? Should I give it to the shop owner if I contact him ? In what cases should I contact the shop owner anyway ?

**Comment by sondreb** [comment] 2018-11-16 13:41
I'm gonna drop this minor bug here, there is an \n character shown in the expired dialog.

![image](https://user-images.githubusercontent.com/309938/48624794-a7e1b080-e9ad-11e8-8eb1-90cad8028675.png)

**Comment by bitcoinshirt** [comment] 2018-12-01 10:57
I think that some points were addressed in this [commit](705dbf12d7e59e5a2d63ad869ee91a7155c4972f) and we can close this one now.
There's no need to complicate things imo.

**Comment by bitcoinshirt** [comment] 2018-12-31 10:49
![screen shot 2018-12-31 at 11 47 26](https://user-images.githubusercontent.com/36959754/50558892-eb8c4180-0cf1-11e9-8ebf-b8e20eae577d.png)

This is how the expired invoice page looks now. It's impossible to add that much information, imo this looks quite concise and clear. Haven't seen any complaints from merchants or customers about the clarity.

The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2018-12-31 17:21 UTC
Labels: UI / UX, preparing-to-close
