### ISSUE TITLE
Refactor `LNURL.LNURL.Parse` to be smart enough to handle the case when input is email

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6095] opened 2024-07-08 13:11 UTC
This issue is stemming from the conversation in https://github.com/btcpayserver/btcpayserver/pull/6061/files#r1658119228.

So instead of:

```
var lnurl = lnurlPayClaimDestinaton.LNURL.IsValidEmail() ?
                        LNURL.LNURL.ExtractUriFromInternetIdentifier(lnurlPayClaimDestinaton.LNURL)
                        : LNURL.LNURL.Parse(lnurlPayClaimDestinaton.LNURL, out var lnurlTag);
```

we could just have: `LNURL.LNURL.Parse(...);`.

**Comment by Castro1g** [comment] 2024-07-15 01:54
- [ ] /
Duplicate of #

![Uploading 

1. > 

- [ ] TJy2LR9FFrP7ZQw99CRfHeiFCG2RZUasGF.png…]()

**Comment by Castro1g** [comment] 2024-07-15 01:55
```javascript
[c36dfb21...b98be738](https://mempool.space/tx/6fbed93b0b3267369b5b8c3de073e8b797a36bfb548001cbd46c56220072632f)
```

**Comment by pavlenex** [comment] 2024-11-20 14:26
In a follow up conversation we decided not to implement this.

**Closed by pavlenex** 2024-11-20 14:26 UTC
Labels: Lightning
