### ISSUE TITLE
Multiple issues with JavaScript disabled (befault in onion browsers)

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#2057] opened 2020-11-07 22:27 UTC
**Describe the bug**
There are several problems with JavaScript disabled:

* Crowdfunding appears inactive even when it is active (appears active on JS-enabled websites)
* Redirect to noscript invoice is missing `rootPath`, therefore leads to 404 when `rootPath` is set to e.g. `/btcpay`
* When `rootPath` is inserted manually, all the links on that site have `rootPath` missing as well (payment methods as well as Go back to Javascript enabled invoice)

Note that `rootPath` works correctly everywhere else as far as I can tell.

**To Reproduce**
1. Setup BTCPay with onion, `rootPath = /btcpay`
2. Setup a crowdfunding app and activate it
3. Setup a POS app
4. Copy the address of crowdfunding app to onion browser with JS disabled
5. See crowdfunding being inactive
6. Visit the address of POS app in the onion browser
7. Try to buy something
8. Click "Continue to javascript-disabled invoice" on the next page
9. See Error 404
10. Insert `/btcpay` manually
11. Inspect links on the site

**Expected behavior**
Crowdfunding should appear active when JS is disabled. The links in invoice site should contain the `rootPath` (`/btcpay` in this example)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: `1.0.5.9`
- Deployment Method: Debian package
- Browser: Torbrowser - same behavior on Android and Linux desktop

**Logs (if applicable)**

<details>
<summary>Logs, don't seem to contain anything interesting</summary>

```
Nov 07 22:28:05 <redacted> systemd[1]: Started A cross platform, self-hosted server compatible with Bitpay API.
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  Data Directory: /var/lib/btcpayserver-system-mainnet/.btcpayserver/Main
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  Configuration File: /etc/btcpayserver-system-mainnet/btcpayserver.conf
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  Network: Mainnet
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  Supported chains: BTC
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  LogFile: /var/log/btcpayserver-system-mainnet/debug.log
Nov 07 22:28:06 <redacted> btcpayserver[1658]: info: Configuration:  Log Level: Debug
Nov 07 22:28:07 <redacted> btcpayserver[1658]: info: Configuration:  Network: Mainnet
Nov 07 22:28:07 <redacted> btcpayserver[1658]: info: Configuration:  Supported chains: BTC
Nov 07 22:28:07 <redacted> btcpayserver[1658]: info: Configuration:  LogFile: /var/log/btcpayserver-system-mainnet/debug.log
Nov 07 22:28:07 <redacted> btcpayserver[1658]: info: Configuration:  Log Level: Debug
Nov 07 22:28:07 <redacted> btcpayserver[1658]: info: Configuration:  Postgres DB used
Nov 07 22:28:10 <redacted> btcpayserver[1658]: info: Configuration:  Root Path: /btcpay
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24445/
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: Configuration:  BTC: Cookie file is /var/lib/nbxplorer-mainnet/Main/.cookie
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      Starting listening NBXplorer (BTC)
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: Events:         NBXplorer BTC: NotConnected => Ready
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      Start watching invoices
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      BTC: 0 payments happened while offline
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
Nov 07 22:28:11 <redacted> btcpayserver[1658]: info: PayServer:      Starting payment request expiration watcher
Nov 07 22:28:12 <redacted> btcpayserver[1658]: info: Configuration:  Listening on http://127.0.0.1:23000
Nov 07 22:28:12 <redacted> btcpayserver[1658]: info: PayServer:      0 pending payment requests being checked since last run
Nov 07 22:28:55 <redacted> btcpayserver[1658]: info: PayServer:      User logged in.
Nov 07 22:37:45 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
Nov 07 22:48:11 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
Nov 07 22:55:45 <redacted> btcpayserver[1658]: info: Events:         Invoice PmZf31pDidAYQdyjzpnzTr new event: invoice_created (1001)
Nov 07 22:55:45 <redacted> btcpayserver[1658]: info: Events:         BTCPayServer.HostedServices.AppInventoryUpdaterHostedService+UpdateAppInventory
Nov 07 23:02:48 <redacted> btcpayserver[1658]: info: Events:         Invoice CWRuT6qbigJaR28tfCqgFA new event: invoice_created (1001)
Nov 07 23:02:48 <redacted> btcpayserver[1658]: info: Events:         BTCPayServer.HostedServices.AppInventoryUpdaterHostedService+UpdateAppInventory
Nov 07 23:07:23 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
Nov 07 23:10:05 <redacted> btcpayserver[1658]: info: Events:         Invoice 9QmQHQqEzXFAHYokVzbkA6 new event: invoice_created (1001)
Nov 07 23:10:05 <redacted> btcpayserver[1658]: info: Events:         BTCPayServer.HostedServices.AppInventoryUpdaterHostedService+UpdateAppInventory
Nov 07 23:12:29 <redacted> btcpayserver[1658]: info: Events:         Invoice NTRXT54n2T1yyWU3Vzk2ph new event: invoice_created (1001)
Nov 07 23:12:29 <redacted> btcpayserver[1658]: info: Events:         BTCPayServer.HostedServices.AppInventoryUpdaterHostedService+UpdateAppInventory
Nov 07 23:12:29 <redacted> btcpayserver[1658]: info: PayServer:      BTC (Lightning): Start listening http://127.0.0.1:8080/
Nov 07 23:14:27 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
Nov 07 23:19:03 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
Nov 07 23:19:06 <redacted> btcpayserver[1658]: info: Events:         BTC: New block
```

</details>

**Additional context**
<details>
<summary>Config file</summary>

```
btc.explorer.cookiefile=/var/lib/nbxplorer-mainnet/Main/.cookie

btc.explorer.url=http://127.0.0.1:24445/

debuglog=/var/log/btcpayserver-system-mainnet/debug.log

port=23000
btc.lightning=type=eclair;server=http://127.0.0.1:8080/;password=XXXXXX

rootPath=/btcpay
postgres=User ID=btcpayserversystemmainnet;Password=XXXXXX;Host=localhost;Port=;Database=btcpayserversystemmainnet;
```

</details>

**Comment by bolatovumar** [comment] 2020-11-08 06:02
Looks like the logic for the JS-enabled and JS-disabled versions of the crowdfund app is different. Not sure which one is the correct one. I assume the JS-enabled version is the correct one?

JS logic sets `ended` to `false` if end date is not explicitly set:
![Screen Shot 2020-11-07 at 7 46 37 PM](https://user-images.githubusercontent.com/1934678/98458371-a4b8cf80-2144-11eb-8bf3-11e568f73ee2.png)

C# logic sets `Ended` to `true` if end date is not explicitly set:
![Screen Shot 2020-11-07 at 7 47 16 PM](https://user-images.githubusercontent.com/1934678/98458372-a5e9fc80-2144-11eb-9b25-ac6379a358f5.png)

**Comment by Kukks** [comment] 2020-11-08 11:10
fixed in #2059

**Closed** 2020-11-08 11:10 UTC

**Comment by bolatovumar** [comment] 2020-11-08 19:35
@Kukks there are multiple issues in this bug report. I fixed the issue wit the root path being ignored but I haven't done anything for the crowdfund app not working properly with JS disabled. I wasn't sure what the expected behavior is (see my above comment). Perhaps that bug should be a separate Github issue?

**Comment by Kixunil** [comment] 2020-11-08 21:39
Thanks for working on this so quickly!

@bolatovumar the JS version works as expected, non-JS doesn't so apparently it should be the same as JS version. :)

Any ETA when the release with fixes will be released?

**Comment by bolatovumar** [comment] 2020-11-11 21:27
> Thanks for working on this so quickly!
> 
> @bolatovumar the JS version works as expected, non-JS doesn't so apparently it should be the same as JS version. :)
> 
> Any ETA when the release with fixes will be released?

Not sure about the ETA. I guess the URL update for root path should be in the next release.
