### ISSUE TITLE
Invoice creation of Large number of invoices, using multiple coins, creates high CPU load and delays further invoices

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#744] opened 2019-04-07 06:35 UTC
**Describe the problem/bug**
When our site is active, and we have a decent amount of invoice generation (10+ active invoices), BTCPay seems to stall and crash to the point where it takes between 10-30 seconds per invoice to generate. 

This is an issue I have been struggling with a long time, however, it's gotten a lot worse on my docker deployment vs my manual setup. In the past, this happened every 2 weeks with a manual setup, but now a docker setup will go nuts within several hours. I am assuming docker is taking slightly more overhead and CPU resources. 

I've noticed a large spike in CPU load when this issue happens and invoices take so long to generate that our woocommerce instance times out as well and the customers are unable to place orders. 

I thought I should put this here for future discussion and see if anyone else is having this issue. 

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.3.92
* Deployment method: Docker and Manual
* Other relevant environment details: Ubuntu 18.04 LTS, Intel Xeon D-1520 - 32GB DDR4 ECC 2133 MHz - SoftRaid 2x2TB

**Logs (if applicable)**
Below is an example of the worst case, however it is a real example. 

4/6/2019 11:09:53 AM    Creation of invoice starting
4/6/2019 11:09:53 AM    BTC_CAD: The rating rule is kraken(BTC_CAD)
4/6/2019 11:09:53 AM    BTC_CAD: The evaluated rating rule is (6797.7, 6800)
4/6/2019 11:09:53 AM    LTC_CAD: The rating rule is (kraken(LTC_BTC) * kraken(BTC_CAD)) * 0.95
4/6/2019 11:09:53 AM    LTC_CAD: The evaluated rating rule is ((0.018283, 0.018325) * (6797.7, 6800)) * 0.95
4/6/2019 11:09:53 AM    DASH_CAD: The rating rule is (kraken(DASH_BTC) * kraken(BTC_CAD)) * 0.95
4/6/2019 11:09:53 AM    DASH_CAD: The evaluated rating rule is ((0.0259, 0.02598) * (6797.7, 6800)) * 0.95
4/6/2019 11:09:53 AM    DOGE_CAD: The rating rule is (kraken(DOGE_BTC) * kraken(BTC_CAD)) * 0.95
4/6/2019 11:09:53 AM    DOGE_CAD: The evaluated rating rule is ((0.00000066, 0.00000067) * (6797.7, 6800)) * 0.95
4/6/2019 11:09:58 AM    BTC (Off-Chain): Payment method details creation took 4 seconds
4/6/2019 11:09:58 AM    BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning
4/6/2019 11:10:09 AM    BTC (On-Chain): Payment method details creation took 15 seconds
4/6/2019 11:10:14 AM    LTC (On-Chain): Payment method details creation took 20 seconds
4/6/2019 11:10:18 AM    DASH (On-Chain): Payment method details creation took 25 seconds
4/6/2019 11:10:22 AM    DOGE (On-Chain): Payment method details creation took 29 seconds
4/6/2019 11:10:23 AM    Saving invoice took 152 milliseconds
4/6/2019 11:10:23 AM    Invoice DscqoKyiKN9EGNxfMEjAfy new event: invoice_created (1001)
4/6/2019 11:10:23 AM    Error while sending IPN (1001 invoice_created): Unexpected return code: 500

**To Reproduce**
1. Create a new node with BTC, LTC, DOGE and DASH
2. Create multiple invoices
3. As more invoices are created in a short burst, CPU usage dramatically increases
4. CPU is so high, invoices take 20-30 seconds to complete. 
5. Reboot BTCPay, Repeat. 

**Expected behavior**
Invoice should be delivered within 2 seconds. BTCPay should try to have all invoice details prepped in the lowest amount of time possible. Even when the load is small, invoices take 5-8 seconds to deliver to the customer. This is often too long for a customer and results in them closing the window and moving on.

**Comment by NicolasDorier** [comment] 2019-04-08 04:17
this is very strange indeed. Do you think it has to do with the amount of pending invoice?

**Comment by NicolasDorier** [comment] 2019-04-08 04:18
@astupidmoose can you know what is takign so much CPU? BTCPAY server or NBXPlorer?

**Comment by astupidmoose** [comment] 2019-04-08 04:33
When the issues hit, LND and Bitcoind seem to be the highest CPU Usage, however I have also seen times when BTCPayServer.DLL is also taking a lot of CPU as well. 

I don't think its so much amount of pending invoices, vs the amount of invoices generated in a short amount of time. It seems that if the server is active, and lots of invoices are generated it gets harder to create the invoices and the time to do so spikes.

**Comment by NicolasDorier** [comment] 2019-04-08 04:59
I can reproduce, the problem is NBXplorer. Trying to fix it.

**Comment by NicolasDorier** [comment] 2019-04-08 08:22
This has been solved in nbxplorer 2.0.0.27, can you give a try?

**Comment by astupidmoose** [comment] 2019-04-08 15:44
Invoice creation still takes just as long it seems but will see if continuous usage causes any congestion today. 

4/8/2019 8:23:17 AM    BTC (Off-Chain): Payment method details creation took 994 milliseconds
4/8/2019 8:23:18 AM    LTC (On-Chain): Payment method details creation took 2 seconds
4/8/2019 8:23:19 AM    DOGE (On-Chain): Payment method details creation took 3 seconds
4/8/2019 8:23:21 AM    DASH (On-Chain): Payment method details creation took 4 seconds
4/8/2019 8:23:22 AM    BTC (On-Chain): Payment method details creation took 5 seconds
4/8/2019 8:23:22 AM    Saving invoice took 184 milliseconds

**Comment by astupidmoose** [comment] 2019-04-08 19:59
Just for more context, I had this issue again today. 2 of the last 5 invoices failed. I updated the docker to include 2.0.0.27 today. 

Unfortunately I was not watching CPU usage at the time. 

OK: 
Invoice 1: 4/8/2019 12:34:36 PM - 
4/8/2019 12:34:36 PM | BTC (Off-Chain): Payment method details creation took 155 milliseconds
4/8/2019 12:34:36 PM | BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning
4/8/2019 12:34:37 PM | BTC (On-Chain): Payment method details creation took 1 seconds
4/8/2019 12:34:39 PM | DASH (On-Chain): Payment method details creation took 2 seconds
4/8/2019 12:34:40 PM | DOGE (On-Chain): Payment method details creation took 3 seconds
4/8/2019 12:34:41 PM | LTC (On-Chain): Payment method details creation took 4 seconds

OK: 
Invoice 2: 4/8/2019 12:36:04 PM - 
4/8/2019 12:36:07 PM | BTC (Off-Chain): Payment method details creation took 2 seconds
4/8/2019 12:36:07 PM | BTC (On-Chain): Payment method details creation took 2 seconds
4/8/2019 12:36:08 PM | LTC (On-Chain): Payment method details creation took 3 seconds
4/8/2019 12:36:09 PM | DASH (On-Chain): Payment method details creation took 4 seconds
4/8/2019 12:36:10 PM | DOGE (On-Chain): Payment method details creation took 6 seconds

FAILED:
Invoice 3: 4/8/2019 12:36:09 PM - 
4/8/2019 12:36:09 PM | BTC (Off-Chain): Payment method details creation took 116 milliseconds
4/8/2019 12:36:09 PM | BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning
4/8/2019 12:36:29 PM | BTC (On-Chain): Payment method details creation took 19 seconds
4/8/2019 12:36:31 PM | DASH (On-Chain): Payment method details creation took 21 seconds
4/8/2019 12:36:36 PM | LTC (On-Chain): Payment method details creation took 26 seconds
4/8/2019 12:36:40 PM | DOGE (On-Chain): Payment method details creation took 31 seconds

FAILED: 
Invoice 4: 4/8/2019 12:36:29 PM - 
4/8/2019 12:36:29 PM | BTC (Off-Chain): Payment method details creation took 108 milliseconds
4/8/2019 12:36:29 PM | BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning
4/8/2019 12:36:49 PM | BTC (On-Chain): Payment method details creation took 20 seconds
4/8/2019 12:36:53 PM | DASH (On-Chain): Payment method details creation took 23 seconds
4/8/2019 12:36:55 PM | DOGE (On-Chain): Payment method details creation took 26 seconds
4/8/2019 12:36:57 PM | LTC (On-Chain): Payment method details creation took 27 seconds

OK: 
Invoice 5: 4/8/2019 12:38:23 PM - 
4/8/2019 12:38:23 PM | BTC (Off-Chain): Payment method details creation took 165 milliseconds
4/8/2019 12:38:23 PM | BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning
4/8/2019 12:38:25 PM | BTC (On-Chain): Payment method details creation took 2 seconds
4/8/2019 12:38:27 PM | LTC (On-Chain): Payment method details creation took 4 seconds
4/8/2019 12:38:29 PM | DASH (On-Chain): Payment method details creation took 6 seconds
4/8/2019 12:38:30 PM | DOGE (On-Chain): Payment method details creation took 7 seconds

**Comment by astupidmoose** [comment] 2019-04-13 20:59
After some further work on this, It seems that the issue lies with the I/O of the disks themselves. 

BTCPay in a multicoin setup potentially has issues when using regular SATA drives. SSD drives DRASTICALLY cut the processing times down. 

In our own instance, we have migrated our server to an NVMe SSD and now we see the following results: 

4/13/2019 1:55:06 PM | BTC (Off-Chain): Payment method details creation took 82 milliseconds
-- | --
4/13/2019 1:55:06 PM | BTC (On-Chain): Payment method details creation took 53 milliseconds
4/13/2019 1:55:06 PM | DOGE (On-Chain): Payment method details creation took 45 milliseconds
4/13/2019 1:55:06 PM | LTC (On-Chain): Payment method details creation took 54 milliseconds
4/13/2019 1:55:06 PM | DASH (On-Chain): Payment method details creation took 63 milliseconds
4/13/2019 1:55:06 PM | Saving invoice took 139 milliseconds
4/13/2019 1:55:06 PM | Invoice VNY7wkn7qKuSa1WGLX2u5M new event: invoice_created (1001)

**Comment by NicolasDorier** [comment] 2019-04-22 09:06
Closing this. I wished I could find what was wrong. I think the problem is deep inside the DB we are using. I might need to fork them and fix it.

**Comment by Kukks** [comment] 2019-04-22 12:50
I still think we should consolidate to using the same db engine as BtcPay
so we only worry about one storage :)

**Comment by NicolasDorier** [comment] 2019-04-23 03:37
I don't want to worry about migration and potentially breaking something that work great for lots of people.

**Comment by pavlenex** [comment] 2019-05-07 15:45
Alright, closing this one, it seems to be specific to @astupidmoose's setup. We'll keep monitoring and re-open if people continue to have problems with CPU load and invoices.

**Closed by pavlenex** 2019-05-07 15:45 UTC
