### ISSUE TITLE
[Bug]: Wrong fee estimation for Litecoin

### ISSUE THREAD

**Issue by 0x627562** [btcpayserver/btcpayserver#4498] opened 2023-01-03 14:20 UTC
### What is your BTCPay version?

I run BTCPay Server v1.7.2.0+5e983641b (Altcoins)

### How did you deploy BTCPay Server?

It is deployed on Azure with automated deployment

### What happened?

When trying to send Litecoin transaction I get wrong fee estimation (0.993-0.994 sat/b) for all time ranges. Also I have Payout Processors configured which don't work as configured. Transactions getting back-forward from "Awaiting Payment" to "In Progress". In the "In Progress" when you click the link the transaction is not found in the block explorer. I suspect that transactions get rejected by the node because of very low fee rate.

I have also Bitcoin and Dogecoin wallets with payment processors, and they work fine.

### How did you encounter this bug?

1. Click LTC Wallet
2. Click Send
3. Check the Fee Rate

### Additional information

As a workaround, in the payout processor I set the fee block target to 10000, which reset fee rate to default 100 sat/b. Little expensive but it works.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment] 2023-02-06 07:26
@0x627562 0.993 sat/b seems correct to me. Litecoin have different fee policy than Bitcoin, and if the nodes give wrong estimate, ask why on https://github.com/litecoin-project/litecoin/ as we are just taking what they give us.

`litecoin-cli.sh estimatesmartfee 1` or something like this should show you the same value.

**Comment by NicolasDorier** [comment] 2023-02-15 07:17
Closing this, this is not a bug, fee estimation on Litecoin can be less than 1 sat per bytes, but some block explorers still require 1 sat per bytes.

Please ask the litecoin community or the block explorers in question to do something about it.

**Closed by NicolasDorier** 2023-02-15 07:17 UTC
Labels: Altcoin, need-info
