### ISSUE TITLE
Liquid invoices not completing 

### ISSUE THREAD

**Issue by nharmon9** [btcpayserver/btcpayserver#1249] opened 2020-01-01 01:34 UTC
Invoices paid in Liquid Bitcoin not completing. Initially BTCPayServer doesn't recognize a transaction occurred despite NBXplorer recognizing the transaction belonging to the extPubkey for the app. If I restart BTCPayServer, BTCPS finds the transaction with "1 payments happened while offline." But, the invoice shows only paid partial and is still open.

**Comment by Kukks** [comment] 2020-01-01 10:17
The feature isn't released yet. Can you provide more info, especially about
your setup and wallet  configuration?

**Comment by nharmon9** [comment] 2020-01-02 20:02
Sure. 
OS: OSX 10.15.2
Commit: `4a0d29c700e1fd4b7e676fd98358f4545e439024`
I tried with different wallet settings both `ReadonlyWallet = true/false` in ElementsLikeBtcPayNetwork.cs but it is the same with both. The only reason I tried with false is to see what the wallet controller is doing. I think the problem is that for Liquid NBXplorer ExplorerClient returns balance which is a JSON Array of `AssetMoney` and is grabbing both the `assetId` and `value` and concatenating them into `<Value>-<PeggedAssetID>`.

**Comment by Kukks** [comment] 2020-01-14 13:10
I can't reproduce on a fresh install. What kind of settings did you use for the wallet?

**Comment by nharmon9** [comment] 2020-01-15 19:12
I wanted to test with regtest, so I created a Liquid BTC clone, with Liquid as the mainnet and my elements sidechain as the regtest, and added it into NBitcoin and NBXplorer. For a wallet I just used my local NBitcoin to generate the xpubkey and entered that with `ReadonlyWallet = true` in ElementsLikeBtcPayNetwork.cs.

What wallet settings in particular would help you?

**Comment by NicolasDorier** [comment] 2020-01-16 07:28
can you pull the latest version of btcpayserver, we release officially today.

You can only use liquid with the RPC wallet and command line (elements-cli.sh) you need to use the hotwallet feature.

**Comment by NicolasDorier** [comment] 2020-01-17 13:28
Marking as closing now if you don't come back in 7 days. I think it should be fixed.

**Comment by nharmon9** [comment] 2020-01-24 00:49
Ok so I have updated and now when I try to make a payment to in invoice, it does not complete. So I restart BTCPay Server, reload the invoice and now I get 

```
fail: PayServer:      Unhandled error on watching invoice 2RFoUQxyvhMYAzxo93gF9P
System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by nharmon9** [comment] 2020-01-24 01:46
Additionally, when I use an Unblinded scheme the invoice does complete but only after restarting BTCPay Server

**Comment by NicolasDorier** [comment] 2020-01-24 12:22
@nharmon9 your error really seems a bug. Do you have the full description of the error with the stacktrace?

**Comment by NicolasDorier** [comment] 2020-01-24 12:22
ping @Kukks

**Comment by Kukks** [comment] 2020-01-24 12:44
@nharmon9  please share the full error stack trace

**Comment by nharmon9** [comment] 2020-01-27 20:04
Sure:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Payments.Bitcoin.BitcoinLikePaymentData.GetValue() in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentData.cs:line 70
   at BTCPayServer.Services.Invoices.PaymentEntity.GetValue(PaymentMethodDictionary paymentMethods, PaymentMethodId paymentMethodId, Nullable`1 value, Int32 precision) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 997
   at BTCPayServer.Services.Invoices.PaymentMethod.<>c__DisplayClass44_0.<Calculate>b__3(PaymentEntity _) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 861
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BTCPayServer.Services.Invoices.PaymentMethod.Calculate(Func`2 paymentPredicate) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 855
   at BTCPayServer.Services.Invoices.InvoiceEntity.EntityToDTO() in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 410
   at BTCPayServer.Controllers.InvoiceController.GetInvoiceModel(String invoiceId, PaymentMethodId paymentMethodId) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 203
   at BTCPayServer.Controllers.InvoiceController.GetStatus(String invoiceId, String paymentMethodId) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 329
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /Users/user/BTCPayServer/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by NicolasDorier** [comment] 2020-02-26 04:30
ping @Kukks

**Comment by Kukks** [comment] 2020-02-29 10:15
Is the database used here the one you used before we released Liquid officially? There could be some data missing from a registered payment.

**Comment by nharmon9** [comment] 2020-03-02 19:22
No, when liquid went live I switched back to the master branch.

**Comment by Kukks** [comment] 2020-03-02 19:59
Yes, but did you have payments that occurred before that moment? If the
data was created with the version before the final release, it may be
missing the sufficient data

**Comment by nharmon9** [comment] 2020-03-02 23:16
This I will have to get back to you on I just rebooted my regtest chain and will try again, but it may be a few days.

**Comment by nharmon9** [comment] 2020-03-03 19:50
So where I have been playing with https://github.com/Simplexum/python-elementstx and blockstreams gdk they have a branch working on electrum calls, https://github.com/Blockstream/gdk, to their electrs fork. Check it out

**Closed** 2020-03-22 15:49 UTC
Labels: Closing
