### ISSUE TITLE
[Bug]: Pay in Wallet button does not work with certain browsers

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#5266] opened 2023-08-21 21:24 UTC
### What is your BTCPay version?

BTCPay Server v1.11.2

### How did you deploy BTCPay Server?

Running on a VPS. CLN instance

### What happened?

https://chat.btcpayserver.org/btcpayserver/pl/xxd89e7gi7gk9nw4c9jpp6pjzr

When opening an invoice in modal, the "Pay in Wallet" button will not work with Chromium, Brave and Safari.

Likely a scheme compatibility issue on BTCPay's side when in modal using Chromium, Brave and Safari. Possibly something analogous to the issue with the QR code not appearing, that we figured a couple months ago with @dennisreimann 

It works fine using Firefox. 

Tested https://wordpress.demo.btcpay.tech/ and I could replicate the same bug that I experience on my BTCPay server

This is a known issue fixed by @ndeet in the past and that came back with recent release. 

### How did you encounter this bug?

https://chat.btcpayserver.org/btcpayserver/pl/xxd89e7gi7gk9nw4c9jpp6pjzr

When opening an invoice in modal, the "Pay in Wallet" button will not work with Chromium, Brave and Safari.

Likely a scheme compatibility issue on BTCPay's side when in modal using Chromium, Brave and Safari. Possibly something analogous to the issue with the QR code not appearing, that we figured a couple months ago with @dennisreimann 

It works fine using Firefox. 

Tested https://wordpress.demo.btcpay.tech/ and I could replicate the same bug that I experience on my BTCPay server

This is a known issue fixed by @ndeet in the past and that came back with recent release. 

### What browser do you use?

Chromium, Brave and Safari.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment] 2023-08-21 21:47
I tested Brave on Linux and Brave and Safari on MacOS using checkout v2 on that wordpress demo site of mine connected to BTCPay 1.11.2. It worked as expected.

**Comment by ndeet** [comment] 2023-08-21 21:49
The connected BTCPay server to that wordpress demo site is also running CLN.

**Comment by strnly** [comment] 2023-08-21 21:58
In modal ?

**Comment by ndeet** [comment] 2023-08-21 22:05
Yes on my testsite https://wordpress.demo.btcpay.tech

Also checked now on Android with DuckDuckGo and Chrome and it worked as expected.

Would be great if you could open up developer tools or javascript console to check for any error. Without beeing able to reproduce some more information would help.

Do you have that problem in your own modal implementation or do you use the WooCommerce plugin on your own site? So is this really not a general BTCPay modal problem but for the WooCommerce plugin?

**Comment by strnly** [comment] 2023-08-21 22:12
I have my own modal implementation. Not using WooCommerce nor any plugin. 

See what I get 

Failed to launch 'lightning:lnbc3780640n1pjw8c8gsp55u34gxn055v6ck5z6n652sp8hmw2h9m69hxczhsf4g63686jk6zqpp5sze4thh90mf7dj97hyrrvsqftu2p0pnpnknd8zwqwhc0vchemdhsdpc2pskjepqw3hjq5652f8yckfq9p8hyer9wgsyj3p6yqck6argtac8ymefxqzurcqpjrzjqfsj8yvhgs4a5ewfjve4nw7t5uhgnul80j58ahtmutjt77afyxq3wz7vwsqqsysqqqqqqqlgqqqq05qqjq9qxpqysgqg7gslgfekwl9axll7hnkvhul98zhkl40rhnzatjltu76etrmcj4smchzfm3ve42adaet0lq36acltlp9rqx998rxdysk2572xjgm3scp58940k' because the scheme does not have a registered handler.

On demo site as well 

Failed to launch 'lightning:lnbc998640n1pjw8cfxsp5hvcatc75mvjxws0p5x5rn2fyxndpt6ddqq6zw0vqs9kxjkdehk4spp50pw8pqezywy9hep033qp3u2gqhm26uf08ej6umtz330g09z2p8fsdpa2pskjepqw3hjq46sypxxjut4d9jzq3r9d4hjq2z0wfjx2u3qf9zr5gp3xs6zjxqzrhcqpjrzjq2xdezhrmths0vyvscted6evykep0t7zrylz8ts44a2rp9xddd597zanlyqqrgcqqyqqqq9vqqqq9tsqyg9qxpqysgqdwf4knr8q8l3gz00p9att6xadv0hul6s7tfd653ujk8rp72zevrrjhwnjqj4v6yyutahcs4g5n9ssr947jgx8z86cj2sxtkfusl3q7spcufxhy' because the scheme does not have a registered handler.

I remember it is the exact same message I was getting before.

**Comment by ndeet** [comment] 2023-08-21 22:37
This error happens normally when there is no app installed that can handle that custom scheme, in this case "lightning". So if it works on the same device with other browsers then maybe there is a security setting preventing the browser form checking if a supported app is installed?

Here are two links for testing, both use the scheme "bitcoin" which should open a bitcoin wallet. There is a difference in the links "target" behaviour though. If both of them fail for you then we know that is not the issue. I would assume something like the browser is not allowed to check for installed apps for some reason then.

https://jsbin.com/qavetoxinu/edit?html,output

**Comment by strnly** [comment] 2023-08-21 22:43
The second "Pay in wallet, target blank" link works perfect on my same device and browser.

**Comment by ndeet** [comment] 2023-08-22 06:59
Ok great, so there seems to be a problem with some browser and OS combinations then maybe.

@dennisreimann the difference between the two links is that one time it is like we have now that the pay in wallet button link has `target="_top"` and the other time (when it works all the time it seems) is `target="_blank"`. No idea why target `_top` would be needed, it seems to cause problems for weird reasons. Do you see any problem changing it to `_blank`?

**Comment by NicolasDorier** [comment] 2023-08-28 01:00
fixed in 1.11.3. @strnly please re-open if you still see it. I updated our testnet demo.

**Comment by strnly** [comment] 2023-08-28 12:40
Works now. Thanks!

**Comment by strnly** [comment] 2023-08-28 21:37
@NicolasDorier @ndeet Please test it on your end with your own browsers.
It works for me, but one of my users just reported it no longer works for them.

**Comment by strnly** [comment] 2023-08-29 17:41
@NicolasDorier @ndee you need to test more guys. It is not working with Safari now. And I have users complaining it is not working with Chrome. 

It was working fine before the last upgrades. Not sure why that was messed with.

**Comment by strnly** [comment] 2023-08-29 19:07
Does not work with DuckDuckGo 

When i test using this link 

https://jsbin.com/qavetoxinu/edit?html,output and hit "blank" with DuckDuckGo, it works fine, but not BTCPayServer "Pay In Wallet" button. 

It used to work fine v1.11.2 before you applied the fix in v1.11.3

**Comment by ndeet** [comment] 2023-08-29 20:31
Seems no target does not work. You yourself confirmed it works in the PR here :) https://github.com/btcpayserver/btcpayserver/pull/5270#issuecomment-1689761218

Can confirm it does not work with DuckDuckGo. Works in Chrome and Brave for me though. 

@dennisreimann @NicolasDorier seems we need to go with `target="_blank"` to cover all browsers

**Comment by strnly** [comment] 2023-08-29 20:36
I know. I tested Firefox, Chromium, Brave, all worked. I don't use DuckDuckGo... (who does? :) ). Someone pointed it to me.

**Comment by NicolasDorier** [comment] 2023-08-29 22:38
@strnly if you

**Comment by NicolasDorier** [comment] 2023-08-29 22:39
@strnly if you modify with target blank, does it work on duckduckgo?

**Comment by ndeet** [comment] 2023-08-30 07:20
> @strnly if you modify with target blank, does it work on duckduckgo?

Yes he confirmed here https://github.com/btcpayserver/btcpayserver/issues/5266#issuecomment-1697985220

**Comment by ndeet** [comment] 2023-08-30 07:21
duckduckgo is also a privacy browser on Android which seems to have some usage

**Comment by strnly** [comment] 2023-08-30 19:01
SUPPOSEDLY... a privacy browser. 
A user just reported the same issue with:
Safari on phone 
Microsoft Edge on laptop 

I don't use iOS nor do I use Microsoft. Safari on laptop works fine so not sure why it does not on iOS.

When is the fix (blank) being merged? 

Thanks

**Closed** 2023-08-31 00:44 UTC

**Comment by strnly** [comment] 2023-09-09 21:12
@NicolasDorier @ndeet still not fixed. Can you please make it happen?  Thanks guys.

**Comment by ndeet** [comment] 2023-09-11 09:28
No idea how, we tried every possible combination which you also confirmed to be working. Maybe time to file a bug at duckduckgo if it is only not working with their browser but everywhere else.
