### ISSUE TITLE
[Bug]: PoS product section missing

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5226] opened 2023-08-02 20:30 UTC
### What is your BTCPay version?

BTCPay Server 1.11.1

### How did you deploy BTCPay Server?

docker

### What happened?

2 users reported the whole products section is missing for them. Seems to be some JS error, a problem deserializing the template according to the screenshots they provided.

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/e4b8d487-b562-4b55-94bc-07723a67c4b0)

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/dbf3bdf3-d866-4c37-b6e5-05571ea3aafb)

https://chat.btcpayserver.org/btcpayserver/pl/sxaq49kxf7d4xqdxafbgm8nzgw
 

### How did you encounter this bug?

On adding PoS app

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment] 2023-08-03 13:42
It seems this is caused by the File Seller plugin as suggested by @Kukks; one person already confirmed, waiting for the second to confirm too

**Comment by pavlenex** [comment] 2023-08-03 17:49
So this is not BTCPay issue, but plugin conflict?

**Comment by dennisreimann** [comment] 2023-08-03 21:59
It seems this was fixed by Kukks/BTCPayServerPlugins@a5b83ad38b1eea2b45956122faf8772d43e86c4e — can you confirm, @Kukks? I tried and couldn't reproduce it with the new version and our standard POS.

**Comment by Kukks** [comment] 2023-08-04 06:50
Correct, fixed in latest plugin.

**Closed by Kukks** 2023-08-04 06:50 UTC
Labels: Bug
