### ISSUE TITLE
Transaction fees as a balance feature 

### ISSUE THREAD

**Issue by KAISDev** [btcpayserver/btcpayserver#2109] opened 2020-12-06 21:17 UTC
Hi,

@NicolasDorier 
You say it cannot to charge a processing fee on each transaction as a host and such fee would be very small the transaction cost onchain might surpass it.

What do you think to make charging the balance in an account of merchant and add minimum balance 20 $ for example, and when add this balance,.. fees of every transactions will deducted from this balance ... And when the balance is 0 will disable this merchant to Force him to charge his balance.

This would be a great feature to help offset server costs, encouraging more implementations of BTCPay servers.

Regards,
KAISDev

**Comment by pavlenex** [comment] 2020-12-09 15:44
In a way this is a duplicate of #1970 so I'll go ahead and close it. Feel free to continue conversation or contribute ideas there.

**Closed by pavlenex** 2020-12-09 15:44 UTC
