### ISSUE TITLE
Pay Button Price generates wrong price value

### ISSUE THREAD

**Issue by leblitzdick** [btcpayserver/btcpayserver#638] opened 2019-03-03 22:47 UTC
Hy,
i found a little mistake:

If you enter a value with decimal point in Pay Button Price e.g.:

**0.01**      (**0,01** is not accepted)        

then the html code **value="0.01"** is generated. This is not correct it would have to be **value="0,01"** otherwise the leading zeros are simply discarded and **1** is displayed as the invoice amount when i click the Pay button.

I have tried it, I change the invoice amount by hand to **"0,01"** everything is correct.

**Comment by pavlenex** [comment] 2019-03-03 23:56
Can you [check which version](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-can-i-see-my-btcpay-version) of BTCPay you're running?

**Comment by Kukks** [comment] 2019-03-04 06:26
I am guessing your local culture inverts the usage of `,` and `.`
so 0.001 BTC is actually written as 0,001 BTC and 10,000BTC = 10.000 BTC?

**Comment by leblitzdick** [comment] 2019-03-04 08:42
No i don't  think so. It is not possible to insert an ", " in the amount field, no matter what local keyboard layout i choose.



This will be acceptet but produces a wrong result:
![ok](https://user-images.githubusercontent.com/22169878/53720273-98a14880-3e60-11e9-9b28-81f6d4d16800.png)



This will not be accepted but the correct result will be produced if I change it in the html code by hand![wrong](https://user-images.githubusercontent.com/22169878/53720447-11a0a000-3e61-11e9-8c96-17e3f074f30e.png)

I hope it becomes clearer what I mean :-)

**Comment by britttttk** [comment] 2019-03-05 19:36
0,01 <-- In words, what fraction or how many USD are you wanting here?
0.01 <-- This is one hundredth of a USD or one cent.

Your issue is not clear how they are not equivalent. (0.01 does not discard leading zeros. Paste invoice  image details if you feel that it does appear as simply "1" after you enter the value 0.01).

**Comment by leblitzdick** [comment] 2019-03-07 11:42
I'll try to explain the problem again. If you enter 1 cent (0.01) into the Price field you will get 1$ when generating the pay butten. 
![pay](https://user-images.githubusercontent.com/22169878/53954332-3b163180-40d6-11e9-8a00-b25e5396773f.png)
![invoice](https://user-images.githubusercontent.com/22169878/53954343-410c1280-40d6-11e9-9350-25a44d63a814.png)

**Comment by pavlenex** [comment] 2019-03-07 11:47
@leblitzdick Hey, [update your BTCPay](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-update-btcpay-server), there was a bug with decimals in one of the earlier versions, it should be fixed. I tried to replicate this by entering 0.01 in payment button and it generated the amount of 0.01 correctly, not rounding it up.

**Comment by leblitzdick** [comment] 2019-03-07 12:28
i just tried it again while creating the pictures. Form me the error is there, i use the current version v1.0.3.80!

**Comment by pavlenex** [comment] 2019-03-07 13:27
You're manually changing a generated code.
Don't change the value to 0,01. Use 0.01. 
This is not bug, it's just the way in which different cultures perceive decimals, unfortunately we can't change that, we use 0.01, don't change it and you'll get correct amount.

**Comment by leblitzdick** [comment] 2019-03-09 09:13
sorry, but if i don't change it by hand to 0,01 i get the wrong result. 0.01 calculates 1 in the result for the pay button. This is OK?

**Comment by pavlenex** [comment] 2019-03-09 09:59
I think you're changing it, share the button code here so that we can embed and test.

**Comment by leblitzdick** [comment] 2019-03-09 10:16
that i already have please look back 6 postings!

**Comment by pavlenex** [comment] 2019-03-09 10:19
And how can I embed and test image? Share the entire `code` if you won't someone to try to replicate.

**Comment by leblitzdick** [comment] 2019-03-09 10:33
To reproduce the error you only have to enter 0.01 in the price field and press the "Pay with BTCPAY" button. I'm not sure how to transmit this code here. just try it yourself in your btcpayserver to replicate the error!

**Comment by pavlenex** [comment] 2019-03-09 10:35
Now I understand the nickname. Stop acting like one. I'm trying to help you out. Of course I tried to reproduce the issue on 3 different machines, but was not able, that's why I asked you to paste a code. But go solve the issue yourself now, it's on your end.

**Comment by leblitzdick** [comment] 2019-03-09 10:56
perhaps it is my problem, maybe it's just me, but I don't talk nonsense. https://youtu.be/T1af4M8b-6s

**Comment by pavlenex** [comment] 2019-03-09 10:58
I never asked it was a nonsense, I just asked you for a code to reproduce, suit yourself.

**Comment by leblitzdick** [comment] 2019-03-09 11:15
Is't  OK i don't feel attacked, but the error is there with me and i honestly don't know which code i should send you? do you mean the html code that creates the button?? If it helps...t: 

```
<form method="POST" action="https://9sjnbu5bjwitwju9.myfritz.net/api/v1/invoices">
    <input type="hidden" name="storeId" value="5FoTBFcDy5S2DG61Rmxp3V6aHfdE89ecceVS16MRqmqm" />
    <input type="hidden" name="price" value="0.01" />
    <input type="hidden" name="currency" value="USD" />
    <input type="image" src="https://9sjnbu5bjwitwju9.myfritz.net/img/paybutton/pay.png" name="submit" style="width:209px" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor">
</form>
```

**Comment by pavlenex** [comment] 2019-03-09 12:19
In issue #635 the code you provided shows you use `12,34` instead `12.34` on your instance, which leads to conclusion you somehow modified decimals on your end to switch. This can't be done afaik without doing some hard-coded changes on the back-end.

The only way I am able to reproduce your issue on three different servers (including BTCPay mainnnet demo) is to use `0,01` in pay button as modified amount. That means it's either an edge-case or you modified something. I'm unable to reproduce your issue otherwise. 

the reason I needed your entire code is so I can create an invoice on your server, but you keep providing me with half-code, possibly for privacy reasons, which I understand. Unfortunately, I can't help you with the information you provided. I hope you can troubleshoot it on your end, it's definitely not something on BTCPay's end according to my tests.

B

**Comment by leblitzdick** [comment] 2019-03-09 12:55
I'd like to cooperate, but please, what exactly do you need? I never made any changes to the backend, just because I don't know anything about it :-). i use a german localized german keyboard ubuntu 18.04 on a cubietruck/cubieboard hardware. Nothing unusual, just a bit older. Maybe I should try to install a newer dotnet version, maybe that's the problem if it's not on the btcpayserver?

**Comment by NicolasDorier** [comment] 2019-03-09 13:38
@leblitzdick what is your deployment? Docker on a VPS?

**Comment by leblitzdick** [comment] 2019-03-09 13:44
I try it with the newest versions dotnet-sdk-2.1.504-linux-arm.tar.gz and dotnet-runtime-2.1.8-linux-arm.tar.gz git clone btcpayserver everything from scratch and build.sh it...nothing changed... 

now i will try to change the localisation and keyboard to US, maybe this helps

**Comment by NicolasDorier** [comment] 2019-03-09 13:50
It can be actually caused by your **browser** culture.

**Comment by NicolasDorier** [comment] 2019-03-09 13:51
Can you give me the button to click somewhere?

**Comment by leblitzdick** [comment] 2019-03-09 14:03
sure, here you are:
```
<form method="POST" action="https://9sjnbu5bjwitwju9.myfritz.net/api/v1/invoices">
    <input type="hidden" name="storeId" value="5FoTBFcDy5S2DG61Rmxp3V6aHfdE89ecceVS16MRqmqm" />
    <input type="hidden" name="price" value="0.01" />
    <input type="hidden" name="currency" value="USD" />
    <input type="image" src="https://9sjnbu5bjwitwju9.myfritz.net/img/paybutton/pay.png" name="submit" style="width:209px" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor">
</form>
```

**Comment by NicolasDorier** [comment] 2019-03-09 14:04
So this is not a error from browser, but localisation of your server (https://stackoverflow.com/questions/17708344/how-to-set-the-culture-of-all-valueproviderresult-used-in-model-binding-to-a-giv) working on a fix.

**Comment by leblitzdick** [comment] 2019-03-09 14:19
ok then I don't need to look any further? that's already 5 years old, is something happening or can I change something there myself to get around the error? But it's probably easiest for me to just replace the "." with a ","       
:-)

**Comment by NicolasDorier** [comment] 2019-03-09 14:40
Fix will be next version (probably released tomorrow)

**Closed** 2019-03-09 14:40 UTC
Labels: App

**Comment by leblitzdick** [comment] 2019-03-09 14:43
cool, thanks!!!!

**Comment by leblitzdick** [comment] 2019-03-10 13:09
the  error is gone, works like a charm !!
