### ISSUE TITLE
Make it easier to enter correct Derivation Scheme

### ISSUE THREAD

**Issue by Moller40** [btcpayserver/btcpayserver#1263] opened 2020-01-10 12:24 UTC
![Screenshot from 2020-01-10 13-08-37](https://user-images.githubusercontent.com/42067009/72152700-0e910d00-33ac-11ea-9695-785e953a6861.png)

Most people do not have deep knowledge about Derivation Schemes and address types, so it’s hard to know what should be put there. Sometimes it should be the zpub, but that is not mentioned in the “BTCPay format memo”.
I think it would help a lot if an “Address Format” column is added, like:

![Screenshot from 2020-01-10 13-17-16](https://user-images.githubusercontent.com/42067009/72152717-1c469280-33ac-11ea-9523-49d7e1f7d33e.png)

**Comment by pavlenex** [comment] 2020-01-11 07:54
This one is quite challenging. I've been thinking a lot lately how we can improve this, it's indeed not intuitive and certainly one of the most challenging things user has to do in the UI.

Challenge here is that we automatically convert xpub to ypub or zpub when user applies a suffix at the end of the xpub.

In the example you provided while it's clear what xpub,ypub and zpub are it's not clear what has to be done.

@NicolasDorier the only way we can do this is to delete suffix and simply stop converting xpub with a suffix and start calling Extended Public Key instead of xpub everywhere. `Derivation scheme` term is also a bit scary. Not sure if you have any ideas for this.

**Comment by NicolasDorier** [comment] 2020-01-12 07:54
I think the best way is that we prevent users from entering directly the scheme in the box, and force them to use the `import from...`.

**Comment by pavlenex** [comment] 2020-01-22 10:30
@NicolasDorier What we currently have is a bit chaotic.
I think by adding a big upload like button that says "Import from" then adds a drop down:
- A hardware wallet (BTCPay Vault)
- External wallet (manual)
- ColdCard (AirGap) 
- Ledger Wallet
- A new / existing seed 

When external wallet is selected, then it opens a form for manually importing the derivation scheme. Obviously this is just the first attempt, hopefully we can brainstorm this a bit more.

**Comment by Dailybread5** [comment] 2020-04-04 02:30
Total noob here, maybe I can share my perspective on this, as i'm trying to link my wallet to my store currently. 

The first problem I have is that I tried to use the import function, but nothing pops up, not sure why, I checked for pop up blockers etc, but nothing worked. (I should mention I am running BTCPay Server on my RasberryPi, using the MyBTC Node software. 

So then I figured I could do this manually. I checked on my ledger for the xpub address, copied it and tried to import it. I realized it was choosing the wrong addresses, so I used the Hint address function. It seemed at this point that I had successfully confirmed the address and linked my wallet to my store, but I go to create an invoice and it gives me an error, saying that I have not linked a wallet to my store. 

Sorry if i'm asking in the wrong place, but just thought i'd provide you guys with a typical noob problem.

**Comment by pavlenex** [comment] 2020-04-04 11:52
> I had successfully confirmed the address and linked my wallet to my store, but I go to create an invoice and it gives me an error, saying that I have not linked a wallet to my store.

Probably because you have not clicked `Save` or `Confirm` once you veriried, but you abandoned the screen upon verifying..

**Comment by Dailybread5** [comment] 2020-04-04 23:54
> > I had successfully confirmed the address and linked my wallet to my store, but I go to create an invoice and it gives me an error, saying that I have not linked a wallet to my store.
> 
> Probably because you have not clicked `Save` or `Confirm` once you veriried, but you abandoned the screen upon verifying..

I did make this mistake the first try, but I realized that it had not completed. Since then I have made sure it confirmed completely, still having the issue.

**Comment by NicolasDorier** [comment] 2020-04-07 04:04
@pavlenex I am thinking to just save before the user click on Confirm... even me I made this mistake several time...

**Comment by NicolasDorier** [comment] 2020-04-07 04:05
@Dailybread5 ` checked on my ledger for the xpub address, copied it and tried to import it. ` please do not do this, use "Import from Vault" instead.

The popup does not show?

**Comment by Dailybread5** [comment] 2020-04-07 04:12
> @Dailybread5 `checked on my ledger for the xpub address, copied it and tried to import it.` please do not do this, use "Import from Vault" instead.
> 
> The popup does not show?

So I actually didn't know about Vault at the time that I posted, but I found it and tried it out, still my attempt to set up and invoice shows an error saying that the wallet is not linked to the store. The one other thing I realized is potentially a problem is the fact that my store hasn't fully synced...

**Comment by NicolasDorier** [comment] 2020-04-07 04:16
@Dailybread5 this is very strange, you clicked on confirm at the end ? You know the screen when you validate the addresses, theree is a confirm button at the bottom.

**Comment by Dailybread5** [comment] 2020-04-07 04:22
> @Dailybread5 this is very strange, you clicked on confirm at the end ? You know the screen when you validate the addresses, theree is a confirm button at the bottom.

Yes, it confirms and shows the green confirmation message at the top of the screen, it also shows that there is an xpub, the crypto (BTC) and a check mark for enabled. It shows that I can modify it as well. I'm definitely confused about what could have gone wrong.

**Comment by NicolasDorier** [comment] 2020-04-07 04:28
@Dailybread5 ah sorry, the problem is indeed that you did not fully synched. I fixed this error message in the next release. (or previous one, I don't remember)

**Comment by Dailybread5** [comment] 2020-04-07 04:31
> @Dailybread5 ah sorry, the problem is indeed that you did not fully synched. I fixed this error message in the next release. (or previous one, I don't remember)

So it's been saying it's syncing for over a week now, do you have any advice on what I might need to do to fix this?

**Comment by NicolasDorier** [comment] 2020-04-07 04:33
@Dailybread5 I don't know, never used MyBTC. But normally BTCPayServer let you know the current progress, what does it says?

**Comment by Dailybread5** [comment] 2020-04-07 04:35
![Screenshot_20200406-211352_Brave](https://user-images.githubusercontent.com/61529790/78630418-86a58c80-784e-11ea-8315-67d1a6e2fc16.jpg)

**Comment by Dailybread5** [comment] 2020-04-07 04:37
![20200406_213626](https://user-images.githubusercontent.com/61529790/78630514-c3718380-784e-11ea-837b-acf140a52907.jpg)

**Comment by NicolasDorier** [comment] 2020-04-07 04:38
@Dailybread5 this is not synching, your bitcoin node has trouble starting. I don't know why, if you use MyBTC, check how to diagnostic it.

**Comment by Dailybread5** [comment] 2020-04-07 04:41
Ok, thanks. Everything else on my node appears to be syncing correctly, so maybe I need to attempt to reinstall. I have asked someone from Mynode for advice as well.

Cheers.

**Comment by pavlenex** [comment] 2020-05-04 20:44
Adding just a concept, will edit this as I add more stuff. This does not tackle the OP's issue, but derivation scheme entering needs to be tackled at a much deeper level.  (Based on Kukkie's idea for the apps)

![derivation scheme](https://user-images.githubusercontent.com/36959754/81011700-ae414200-8e58-11ea-8604-e6fed3c5b0f9.PNG)

**Comment by pavlenex** [comment] 2020-05-19 15:21
## WIP
These mockups are for brainstorming purposes only. The basic idea is a separate concept of presenting `connect existing wallet` and `create a new one`

### Connecting an existing wallet > Hardware wallet

![New Mockup 1](https://user-images.githubusercontent.com/36959754/82344268-216bbc00-99f4-11ea-824c-0b91b901efbf.png)

![New Mockup 1 copy](https://user-images.githubusercontent.com/36959754/82344278-2466ac80-99f4-11ea-9fe1-6556d9580a17.png)

![New Mockup 1 copy 5](https://user-images.githubusercontent.com/36959754/82344470-5ed04980-99f4-11ea-91e7-3b0ac78a8252.png)

### Connecting an existing wallet > Software wallet
![New Mockup 1 copy 9](https://user-images.githubusercontent.com/36959754/82344621-93440580-99f4-11ea-9e87-a2eac7c83d08.png)

![New Mockup 1 copy 6](https://user-images.githubusercontent.com/36959754/82344651-9b03aa00-99f4-11ea-8ea9-7ced026e093c.png)

![electrum](https://user-images.githubusercontent.com/36959754/82344984-00f03180-99f5-11ea-9de3-469e565d082d.png)

### Generating a new wallet

![New Mockup 1 copy 7](https://user-images.githubusercontent.com/36959754/82345081-23824a80-99f5-11ea-9550-3d969e6294f8.png)

![New Mockup 1 copy 4](https://user-images.githubusercontent.com/36959754/82345133-3006a300-99f5-11ea-8667-911f8f2cdc1f.png)

![New Mockup 1 copy 3](https://user-images.githubusercontent.com/36959754/82345144-339a2a00-99f5-11ea-8d62-34846d9a0622.png)

**Comment by pavlenex** [comment] 2020-06-27 17:27
Closing this one since the issue is better explained in #1703

**Closed by pavlenex** 2020-06-27 17:27 UTC
Labels: Brainstorming, Stores
