### ISSUE TITLE
Add spread on exchange rate decreases the rate spread instead of increasing it

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2658] opened 2021-07-04 21:30 UTC
**Describe the bug**
This bug has been reported by devoutness on Mattermost.
In the Store Settings > Rates when you input the % for example `10%` the generated invoice actually lowers the spread instead of increasing it by 10%.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Store > Rates > `Add spread on exchange rate`
2. Set exchange rate to 10%
3. Create an invoice for that store
4. See the invoice logs `BTC_USD: The rating rule is (coingecko(BTC_USD)) * (0.9, 1.1)`

This means that spread is actually 10% lower which makes no sense. 

**Expected behavior**

If user inputs 10% `add spread` implies 10% increase, I am not sure what we can do for decreases, but this is def a bad UX we have here. This question abotu this particular field gets asked here and there and is def confusing for the users.
 

**Screenshots**

![Screenshot 2021-07-04 at 23 22 40](https://user-images.githubusercontent.com/36959754/124399927-1de1e400-dd1f-11eb-8dcf-54965443c2b2.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   `v1.1.2.0 Environment: Development Build: Debug` 
- Deployment Method:     Dev Enviroment   
- Browser:        Safari          

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

SInce it's late and Sunday, I haven't looked in-depth into the issue, so it could as well be a poor UX rather than a technical bug ,but def confusing.

**Comment by Zaxounette** [comment] 2021-07-04 21:43
Confirmed on Live deployment (Lunanode - BTCPay Server 1.1.2.0).

![chrome_bsitp2hWZr](https://user-images.githubusercontent.com/51208677/124400146-ce041c80-dd20-11eb-8952-6729b864462f.png)

In the above example: With a 0% spread the UI says 34k USD per BTC.
With 10% it says 30k.

**Comment by qkimchi** [comment] 2021-07-05 01:44
Why not use +positive and -negative?

**Comment by bolatovumar** [comment] 2021-07-06 22:02
@pavlenex doesn't this kind of make sense though? If you are a merchant you would want to have the spread at the lower end so that if BTC is 40k, for example, and you set a 10% spread, as long as BTC doesn't go down more than 10% while the purchase is being processed you are good. Doing it the other way around would make the BTC price seem higher which means the merchant would be giving away more stuff than necessary unless the BTC price jumps up the spread amount while the purchase is being made. I don't really see why the merchant would want a negative spread here.

**Comment by pavlenex** [comment] 2021-07-07 07:46
@bolatovumar Certain merchants want to charge a premium for accepting BTC. So 1% more than total to compensate for the fees they're having or whatever. We need a way better UI for this one, its' really confusing for people judging by Mattermost comments.

**Comment by bolatovumar** [comment] 2021-07-08 02:03
@pavlenex isn't adding a spread as it currently the same as charging a premium for accepting BTC?

Let's say you are selling a gift card of dollar value of $100 and BTC price is $1000. This means the price is 0.1 BTC. If you use a spread of 10% then BTC price will be $900 so the gift card will cost 100/900 = 0.11111111 BTC. This is equivalent to charging a premium as I see it.

If you set a negative spread of 10% then BTC price would be $1100 and gift card price would be 100 / 1100 = ~0.9 BTC so you would be charging less than the market price in BTC terms.

**Comment by NicolasDorier** [comment] 2021-07-09 02:02
I doubt there is a bug on the spread

For a spread of 1% you get this calculation on the BID/ASK, which effectively widen the spread, as it should.
Here is an example ` ((33211.5, 33211.6)) * (0.99, 1.01)` 

For the merchant, we are taking the bid. So what is selected here is  `33211.5 * 0.99` making the BTC received cheaper, and thus the customer paying more.

**Comment by NicolasDorier** [comment] 2021-07-09 02:38
So here is a specific case of a store with a spread of 1%, a bid of 33211.5 USD.

2500/(33211.5*0.99) =0.07603549 (Expected BTC with spread of 1%)

The same without the spread would be
2500/33211.5 =0.075275131  (Expected BTC for no spread)

So it means that with the spread, the merchant received 0.000760355 more BTC. Which is exactly 1% more than without the spread.

Or, in your expected rate with spread 0.000760355 * (33211.5*0.99) = 25 USD.

**Comment by NicolasDorier** [comment] 2021-07-09 02:42
Closing this as it is working as expected, and is indeed what the merchant wants when they add a spread.

**Closed by NicolasDorier** 2021-07-09 02:42 UTC
Labels: Bug, UI / UX

**Comment by NicolasDorier** [comment] 2021-07-09 06:02
@qkimchi you can't use negative, because else the bid will become the ask and the ask will become the bid. If we allow this to be negative, we should remove this, as it will not do what the merchant is expecting to.

**Comment by NicolasDorier** [comment] 2021-07-09 06:06
For example, a -50% would mean this:

`((33211.5, 33211.6)) * (1.50, 0.5)`, which mean `(49817.25, 16605.8)`. But this means the bid, would be higher than the ask, so this would be transformed to `(16605.8, 49817.25)` and the final rate chosen would be `16605.8`.
