### ISSUE TITLE
Invoices sorting is erratic.

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#1329] opened 2020-02-11 07:57 UTC
BtcPay Server

On the invoices screen I have a few hundred invoices.
Latest invoices do not appear at the top of the list i.e. 11/2/2020 dd/MM/yyyy
Should be at the top for today but appear much further down and have to page to see.
Clicking the date column changes it to "xx days ago" format but no different.
I suspect this is a region issue, I'm in NZ format dd/MM/yyyy

![Capture](https://user-images.githubusercontent.com/2274034/74219191-014fa100-4d11-11ea-8bc2-8c73f10dae64.PNG)

The image attached shows the issue with date sort. Later invoices do not appear at top of older.

Windows 10
BTCPay Server: v1.03.155
Dotnet run

**Expected behavior**
Sorting should be correct order for dates, format independant

**Actual behavior**
Sorting is not correct date order

**Comment by pavlenex** [comment] 2020-02-11 10:19
@rockstardev Any idea why this would happen?

**Comment by NicolasDorier** [comment] 2020-02-13 05:48
how did you deployed BTCPayServer? If it is manual deploy (not docker/luna), did you setup postgres or use sqlite?

**Comment by mjlamb** [comment] 2020-02-13 07:20
Hi @NicolasDorier 
I git pull and run dotnet run --no-launch-profile --no-build -c Release -p .\BTCPayServer\BTCPayServer.csproj

So I just run locally.

**Comment by NicolasDorier** [comment] 2020-02-13 08:43
mmh I think this is a problem with sqlite then. I will check.

**Comment by Sjors** [comment] 2020-02-18 20:13
I have the same issue, which indeed suggests sqlite. I have once invoice from 2020 which is all the way at the bottom, regardless of whether I sort by ascending or descending date.

v1.0.3.158 on Ubuntu, Docker free.

I'll probably install Postgres soon though.

**Comment by mjlamb** [comment] 2020-02-18 22:03
Any help docs on how to migrate to postgres, on Windows / C#

**Comment by Sjors** [comment] 2020-02-18 22:22
I was planning to just nuke the old DB and start from scratch. Properly migrating data might be more involved. I guess a PR is welcome? :-)

**Comment by NicolasDorier** [comment] 2020-02-19 12:55
Migrating data is too difficult, I won't do it.
I will try to find out the problem with sort order of invoices though.

**Comment by NicolasDorier** [comment] 2020-02-19 13:05
I don't know why it was sorting properly on postgres.

**Comment by Sjors** [comment] 2020-02-19 15:26
Fake news, I just tried on master and it still has the same bug :-)

**Comment by rockstardev** [comment] 2020-02-20 23:42
@NicolasDorier we were already doing `query.OrderByDescending(q => q.Created)` when generating query, so that change won't do anything:

https://github.com/btcpayserver/btcpayserver/blob/dc4f8a1fbe841c0824d545582cc46ae533e955c4/BTCPayServer/Services/Invoices/InvoiceRepository.cs#L577

The problem is obviously because of the way database is setup to sort... to me it doesn't seem erratic, but rather it sorts by first number (day) in descending order (and disregards all else):

3/5
3/4
2/11

Outside of you two properly setting up databases for sorting, the only temporary relief I can think of is using that filtering which will only give you invoices for last 7 days:

![image](https://user-images.githubusercontent.com/5191402/74990190-3db58800-5408-11ea-956c-617393a7d754.png)

Otherwise we would need someone like @Sjors who can run solution locally and create migration that would properly setup Created column on mySql databases.

**Comment by NicolasDorier** [comment] 2020-02-21 02:28
Is it again a fuckery of Entity Framework?

**Comment by NicolasDorier** [comment] 2020-02-21 02:29
I reverted my commit.

**Comment by NicolasDorier** [comment] 2020-02-21 02:35
Ok the problem come from another hack I did to workaround an unsolvable problem on SQLite after a migration to .NET Core 3.1 https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Data/Data/ApplicationDbContext.cs#L260

**Comment by NicolasDorier** [comment] 2020-02-21 02:41
Actually I am not even sure this is related to this hack. :/

I am wondering if my hack did not changed the DB format of datetimes for SQLite, which had for side effect to mess with the ordering of old invoices versus new invoices.
But if it was the case, the date should be wrong and this is not the case...

**Comment by djseeds** [comment] 2020-04-21 13:14
I also have this issue in v1.0.4.0 -- one workaround I've found is exporting to CSV and then sorting in Excel works, and the dates look correct

**Comment by pavlenex** [comment] 2020-08-04 17:08
Since we consider sqlite support  deprecated, I'll close this issue.

**Closed by pavlenex** 2020-08-04 17:08 UTC
Labels: Invoice
