### ISSUE TITLE
[Bug]: Can't update plugin, dependency not detecting the right version, (On 1.11.17)

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#5561] opened 2023-12-16 18:44 UTC
### What is your BTCPay version?

© BTCPay Server v1.11.7+a921504bc

### How did you deploy BTCPay Server?

vps

### What happened?

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/827e3fcf-98ed-470d-bc2f-c4260099e07b)

### How did you encounter this bug?

.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment] 2023-12-17 16:11
Can you update your BTCPay to a newer version first? Also if you're running an instance that is public you should disable LNBank until it's updated. See https://x.com/BtcpayServer/status/1735703168598565365

**Comment by nostitos** [comment] 2023-12-17 17:19
Never been able to figure out how to setup channels, I think I'm fine.
Thanks, will delete lighitning stuff.

**Comment by pavlenex** [comment] 2023-12-18 09:52
@Kukks @dennisreimann any idea why plugin update won't be shown?

**Comment by dennisreimann** [comment] 2023-12-18 13:48
Cannot reproduce this with current master and it'll most likely be fixed with v1.12 (about to get released this week). If not, please let us know and I'll dig deeper, @nostitos.

**Comment by nostitos** [comment] 2023-12-18 17:10
> @nostitos what happens when you click on `show update info`?

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/1219472e-d8d1-44ca-a0ce-ced901b23436)

**Comment by nostitos** [comment] 2023-12-18 17:40
Also turns out this toggle doesn't stick after Saving. 
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/35cd1a20-b757-4fcd-84ca-d80fcb0826e6)

**Comment by pavlenex** [comment] 2023-12-22 15:12
I believe this should be fixed in 1.2.3, @nostitos check and let's re-open if it still occurs.

**Closed by pavlenex** 2023-12-22 15:12 UTC
