### ISSUE TITLE
When creating a store redirect to a wallet creation page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1959] opened 2020-10-07 15:48 UTC
**Is your feature request related to a problem? Please describe.**
When people create a store, in most cases they create it and forget that they need a wallet. Store without a wallet is not complete and pretty much useless.

This issue builds on continues improvements we offered in #1290 and should direct people to #1703 for overall better experience.

**Describe the solution you'd like**
The workflow is as following. While a store is created we should automatically redirect users to #1703 where they can configure their wallet. We can offer either a checkbox in create a store page or simply do it behind the scenes so when a user creates a store they'll be moved to a wallet page.

This issue is just a remind for a workflow but heavily relies on what we implement in #1703

@rockstardev may be able to expand more on technicalities. Also @NicolasDorier had some ideas.

**Comment by rockstardev** [comment] 2020-10-08 19:23
What I had in mind is that you just redirect to Store page, but:

1. Rearrange sections so that you have General, Wallet, and then Payment
2. Have persistent warning in Wallet section to notify user Derivation Scheme (XPUB) should be defined

So, small steps for start... if you like this direction I can open PR to start going in that direction: 

![image](https://user-images.githubusercontent.com/5191402/95504032-cec67880-0971-11eb-9f67-ce357d0a8f75.png)

**Comment by rockstardev** [comment] 2020-10-08 19:27
We can also improve descriptions as part of this PR, for Lightning paragraph we could go with something like:

```
If you want to receive payments over Lightning you will need to define a connection to a Lightning Node which will generate Lightning Network (LN) invoices. Keep in mind that Lightning Node requires a hot wallet to operate, as well as channels with incoming liquidity.
```

**Comment by pavlenex** [comment] 2020-10-08 19:30
@rockstardev your suggestion above seems to be what I had in mind for #1290. I just opened this issue to remind us that once we merge in #1703 we can use this issue to set up some sort of redirection when user creates a store to the wallet page, is that what you were thinking as well?

For lightning ACK, it makes sense. But I also think that process there could be improved, having to click on a `click here` link is not the best UX.

**Comment by rockstardev** [comment] 2020-10-08 22:42
No, my thinking was along the lines of not doing any extra redirection after store creation... just informing the user directly on the store page what needs to be done.

I really think we shouldn't make this too complicated with wizards - because if you wanted to enforce certain steps on the store you would do all that on "Create Store" page and do small wizard like:
 1. Pick a store name
 2. Define a wallet
 3. Define lightning connecting if you want it
 4. Define rate

Doing those steps would result in summary page and when you click `Create` button you would finally get fully initialized store.

Now, the problem is that steps 2, 3, 4 require step 1. Step 2 is also quote complex. Forcing all users through step 4 is not optimal.

Thus - I would just focus on providing information on the Store page what we recommend users do in each section. And allow them to dismiss "warnings" - maybe user doesn't want a wallet, but just a store with Lightning.

Think about this, and if you don't want me to create a PR with these small tweaks - then I would recommend we close this issue. There are already enough issues dealing with this and I wouldn't want to draw away from those discussions.

**Comment by dstrukt** [comment] 2020-10-09 06:08
I agree with @rockstardev's approach, and it's basically what I've been exploring as well on both fronts.

A. For this flow (directly from the wallet), we should immediate next steps, no wizard. The only question being if we want to show two alert modals or just one (that should persist until you manually wave it away). I would argue we need to make more prominent alerts (which is what the visual exploration is below), as it should immediately catch your attention and keep it as long as you're on that page (I don't feel the smaller alerts push this enough).

B. If you enter from the wallet, there are two derivations, but still should direct you to finish up creating a store, then a wallet.

C. If the user enters from the dashboard, we can show a semi-persistent wizard / guide that pushes them to any of the flows above (in this case, pushes to option A, and should finish up the process). After the store, and subsequently the wallet is setup, the dashboard would update to show metrics and details.

Here are the examples & flows for full context:

A)
<img width="1108" alt="Screen Shot 2020-10-08 at 11 05 18 PM" src="https://user-images.githubusercontent.com/6250771/95548930-ff7ed000-09ba-11eb-9e8b-a2021c5f4410.png">

<img width="1848" alt="Screen Shot 2020-10-08 at 11 04 58 PM" src="https://user-images.githubusercontent.com/6250771/95548928-fdb50c80-09ba-11eb-94e6-8b05ec7d782b.png">

B) 
<img width="1333" alt="Screen Shot 2020-10-08 at 11 06 49 PM" src="https://user-images.githubusercontent.com/6250771/95548946-07d70b00-09bb-11eb-86d0-ddcccb51ed6d.png">

C)
<img width="1490" alt="Screen Shot 2020-10-08 at 10 56 03 PM" src="https://user-images.githubusercontent.com/6250771/95548972-19201780-09bb-11eb-9894-f60ecb3a7f70.png">

A lot of the little details are still w.i.p while I'm working through the design system component standardization, but you get the rough idea.

Still iteration needed.

**Comment by pavlenex** [comment] 2020-10-10 07:46
Love the direction in which you guys are going 😍 

@rockstardev I agree, let's open up a PR so we can discuss it directly. Is there any chance you can adapt it somehow to look like in 
@dstrukt's example A? It's basically what you already have just with slightly different wording. Challenge would be how to have a "Set up wallet button" when we have more currencies.


@dstrukt that's it, thaaaaat's it!!!! 🔥

**Comment by dstrukt** [comment] 2020-10-10 11:04
I'm working on pushing the "wallet setup" / derivation scheme flow further at the moment  as well so we can critique that further - should have updates soon.

https://github.com/btcpayserver/btcpayserver/issues/1703

As for this, I think simple wording updates would be a step in the right direction for the time being (if we can't implement something as simple as "set up wallet" at this moment in time), but ultimately would like to get to the point where we can handle every case (new wallet, hardware/software, and alternative currencies) with the updated / simplified set up.

Dashboard UI, etc.. will be improved as well, but wanted to toss out some ideas to kick around.

**Comment by rockstardev** [comment] 2020-10-14 17:22
My only concern is that we don't get too focused on "wallet setup"... it's just one of 3 additional steps we're talking about. I'll give it a try with PR and then we can build off from there.

**Comment by pavlenex** [comment] 2020-10-14 17:34
No worries uncle, we're keeping these quite focused and separate so far 😃 
A PR would be a great starting point. @dennisreimann may be interested into looking at the PR as well.

**Comment by dstrukt** [comment] 2020-10-14 20:27
Sounds good!

Agreed, we should stay focused, was posting the others to provide context that we're pushing the user to complete this flow (regardless of how they navigate the product), but you could easily just focus on the screens that pertain to this specific view.

**Closed** 2020-10-18 08:11 UTC
Labels: Enhancement, Stores, UI / UX, Wallet
