### ISSUE TITLE
Error parsing postgres connection string from command line

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver#375] opened 2018-10-30 20:34 UTC
Hi there!

I have problem with passing postgres connection string via command line. 

I use

```
./run.sh --testnet --postgres User ID=postgres;Password=psw;Host=myHost;Port=5432;Database=btcpayserver
```

and keep getting 

```
Unhandled Exception: CommandLine.CommandParsingException: Unrecognized command or argument 'ID=postgres'
   at CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at CommandLine.CommandLineApplication.Execute(String[] args)
   at StandardConfiguration.DefaultConfiguration.CreateConfiguration(String[] args)
```

**Comment by sipsorcery** [comment] 2018-10-31 07:08
@sigHash you need to put the connection string in double quotes otherwise any spaces in it will be interpreted as a separate option.

`./run.sh --testnet --postgres "User ID=postgres;Password=psw;Host=myHost;Port=5432;Database=btcpayserver"`

**Comment by sigHash** [comment] 2018-10-31 16:49
@sipsorcery I tried that before and it still gives me error:

```
Unhandled Exception: CommandLine.CommandParsingException: Unrecognized command or argument 'ID=postgres;Host=postgres;Port=5432;Database=btcpayserver'
   at CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at CommandLine.CommandLineApplication.Execute(String[] args)
   at StandardConfiguration.DefaultConfiguration.CreateConfiguration(String[] args)
```

I tried:

```
./run.sh --network testnet --postgres "User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver"
```

```
OS: MacOs
IDE: VSCode
```

**Comment by sipsorcery** [comment] 2018-10-31 18:06
@sigHash I was able to reproduce the problem. It only occurs when using the `run.sh` shell script and I'm pretty certain it's related to the way command line arguments are passed from the bash (or other) shell through to the application. 

I recall @NicolasDorier posting some tweets about command line escaping recently?

You can execute  btcpayserver without the `run.sh` script and achieve the same effect using:

`dotnet run --no-launch-profile --no-build -c Release -p "BTCPayServer/BTCPayServer.csproj" --postgres "User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver"`

**Comment by sigHash** [comment] 2018-10-31 19:41
@sipsorcery Thanks, it works!

**Closed** 2018-11-01 04:49 UTC

**Comment by kosuodhmwa** [comment] 2024-12-14 14:34
there seems to be a lot of crap in manual, lol 

https://github.com/dgarage/NBXplorer/issues/498
