### ISSUE TITLE
/sbin/ip: not found

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#712] opened 2019-03-24 12:38 UTC
**Describe the problem/bug**
`ip` library is missing in docker image.  It is used in `docker-entrypoint.sh` to update `/etc/hosts`, which as a result is not correct and maybe the source of other problems I have. 

**Your environment**
* Version of BTCPay Server:  v1.0.3.89
* Deployment method: Docker
* Other relevant environment details: Single-board Odroid xu4

**Logs (if applicable)**
```
root@odroid:~# docker logs generated_btcpayserver_1
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
```

```
root@odroid:~# docker exec -ti generated_btcpayserver_1 sh -c "/sbin/ip route|awk '/default/ { print \$3 }'"
sh: 1: /sbin/ip: not found
```

**Comment by NicolasDorier** [comment] 2019-03-24 13:27
The problem is that you installed Docker separately. You need to install docker by running `btcpay-setup.sh` script. NOT manually.

You need docker for arm32v7, not docker for arm64v8 to run btcpay

**Comment by NicolasDorier** [comment] 2019-03-24 14:38
disregard what I said, this is another issue.

**Comment by NicolasDorier** [comment] 2019-03-24 14:57
This will be fixed next release. Thanks for the report. That said this should not prevent the rest to work.

**Closed** 2019-03-24 14:56 UTC
