### ISSUE TITLE
LND fails to unlock wallet after docker container restart in testnet

### ISSUE THREAD

**Issue by PeerZetZzZzZ** [btcpayserver/btcpayserver#1859] opened 2020-08-20 20:55 UTC
**Describe the bug**
Restarting lnd docker container fails on unlocking wallet.
This happens in testnet network, I didn't notice the problem in regtest.
The problem is because walletunlock.json is not present under bitcoin/datadir/data/chain/bitcoin/testnet. It is present under bitcoin/datadir/data/chain. When I manually copy the file to the expected folder - it works correctly after restart.

docker-compose (my version has slightly different names):
```
 lnd_bitcoin:
    image: btcpayserver/lnd:v0.10.1-beta
    container_name: lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_EXTERNALIP:  lnd_bitcoin
      LND_PORT: 1025
      LND_ALIAS: ${LIGHTNING_ALIAS}
      LND_ENVIRONMENT: ${NBITCOIN_NETWORK}
      LND_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        listen=0.0.0.0:1025
        bitcoin.node=bitcoind
        bitcoind.rpcuser=lnd
        bitcoind.rpcpass=afixedpasswordbecauselndsuckswithcookiefile
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        adminmacaroonpath=/data/admin.macaroon
        invoicemacaroonpath=/data/invoice.macaroon
        readonlymacaroonpath=/data/readonly.macaroon
        notls=0
        bitcoin.testnet=true
        bitcoin.active=1
        tlscertpath=/data/tls.cert
        tlskeypath=/data/tls.key
        tlsextradomain= lnd_bitcoin
        debuglevel=info
      HIDDENSERVICE_NAME: lnd
      HIDDENSERVICE_PORT: 1025
    volumes:
      - ../../volumes/lnd/bitcoin/datadir:/data
      - ../../volumes/bitcoind/datadir:/deps/.bitcoin
      - ../../volumes/nbxplorer/datadir:/root/.nbxplorer
    ports:
      - 1025:1025
    expose:
      - 8080
      - 10009
```
**Expected behavior**
LND container should work correctly after restart.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer] 
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist]

btcpayserver:1.0.5.3
docker-compose based setup
btcpayserver/lnd:v0.10.1-beta

**Logs (if applicable)**
LND container logs when after restart:
```
LND_CHAIN=btc
LND_ENVIRONMENT=testnet
Added bitcoin.active and bitcoin.testnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
[lnd_unlock] WARNING: UNLOCK FILE DOESN'T EXIST! MIGRATE LEGACY INSTALLATION TO NEW VERSION ASAP
2020-08-20 20:45:21.671 [INF] LTND: Version: 0.10.1-beta commit=basedon-v0.10.1-beta-dirty, build=production, logging=default
2020-08-20 20:45:21.671 [INF] LTND: Active chain: Bitcoin (network=testnet)
2020-08-20 20:45:21.671 [INF] LTND: Opening the main database, this might take a few minutes...
2020-08-20 20:45:21.702 [INF] CHDB: Checking for schema update: latest_version=13, db_version=13
2020-08-20 20:45:21.702 [INF] LTND: Database now open (time_to_open=31.096207ms)!
2020-08-20 20:45:21.742 [ERR] LTND: Unable to unlock macaroons: invalid password
2020-08-20 20:45:21.743 [INF] LTND: Shutdown complete
Unable to unlock macaroons: invalid password
LND_CHAIN=btc
LND_ENVIRONMENT=testnet
Added bitcoin.active and bitcoin.testnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
[lnd_unlock] WARNING: UNLOCK FILE DOESN'T EXIST! MIGRATE LEGACY INSTALLATION TO NEW VERSION ASAP
```

**Comment by pavlenex** [comment] 2020-08-28 08:02
As error says, you're using a legacy version ,you'd need to [migrate](https://blog.btcpayserver.org/btcpay-lnd-migration/).

**Comment by PeerZetZzZzZ** [comment] 2020-08-28 09:53
> As error says, you're using a legacy version ,you'd need to [migrate](https://blog.btcpayserver.org/btcpay-lnd-migration/).

I run btcpayserver in multi LND environment. I believe then it's matter of `BTCPAY_BTCEXTERNALLNDSEEDBACKUP` set in BTCPay? In this case it's not an option for me.

The bug is to close in that case, since it's matter of specific setup different than default configuration.

**Comment by pavlenex** [comment] 2020-08-28 11:28
afaik, the only reason to do this is through following the migration steps in the guide, close all channels, and re-create as described there.

**Comment by pavlenex** [comment] 2020-09-12 05:58
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2020-09-22 10:01 UTC
Labels: Closing
