### ISSUE TITLE
[Bug]: NBXplorer synchronization hanging

### ISSUE THREAD

**Issue by selukov** [btcpayserver/btcpayserver#4906] opened 2023-04-22 22:38 UTC
### What is your BTCPay version?

I'm running 
btcpayserver/btcpayserver:1.9.1
nicolasdorier/nbxplorer:2.3.62

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a docker swarm

### What happened?

I was updating the server nbxplorer:2.3.33 to 2.3.62, now my BTCPay is not syncing

### How did you encounter this bug?

infinite loop docker Log from nicolasdorier/nbxplorer:2.3.62
info: NBXplorer.Indexer.BTC: Restarting node connection...
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
--- loop begin
info: NBXplorer.Indexer.BTC: Full node version detected: 240001
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 50 seconds
System.OperationCanceledException: The operation was canceled.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 104
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 104
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 165
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 78
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
info: NBXplorer.Indexer.BTC: Restarting node connection...
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
---- loop end
info: NBXplorer.Indexer.BTC: Full node version detected: 240001
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by selukov** [comment] 2023-04-23 07:54
[![Screenshot-from-2023-04-23-05-17-20.png](https://i.postimg.cc/jd1jFkXf/Screenshot-from-2023-04-23-05-17-20.png)](https://postimg.cc/jLzKWcBq)

**Comment by pavlenex** [comment] 2023-04-24 09:00
@NicolasDorier can you take a look please?

**Comment by selukov** [comment] 2023-04-25 16:19
I wanted to reindex the database, but it didn't help
```
>docker exec -it btcpay-server_postgres.1.j2pe3b7idahp8khf1ny4gyh6m psql -U postgres
>postgres=# \c nbxplorermainnet
>nbxplorermainnet=# REINDEX DATABASE nbxplorermainnet
```
if I delete the nbxplorermainnet database, will it be created automatically again?

**Comment by selukov** [comment] 2023-04-25 16:33
nbxplorermainnet=# SELECT * FROM "nbxv1_migrations";
```
-----------------------------+-------------------------------
 001.Migrations              | 2022-08-20 20:19:09.69685+00
 002.Model                   | 2022-08-20 20:19:09.727644+00
 003.Legacy                  | 2022-08-20 20:19:09.955933+00
 004.Fixup                   | 2022-08-20 20:19:09.978204+00
 005.ToBTCFix                | 2022-08-20 20:19:09.981389+00
 006.GetWalletsRecent2       | 2022-08-20 20:19:09.984107+00
 007.FasterSaveMatches       | 2022-08-20 20:19:09.988124+00
 008.FasterGetUnused         | 2022-08-20 20:19:09.991341+00
 009.FasterGetUnused2        | 2022-08-20 20:19:09.996456+00
 010.ChangeEventsIdType      | 2022-08-20 20:19:10.00034+00
 011.FixGetWalletsRecent     | 2023-03-18 12:03:27.829337+00
 012.PerfFixGetWalletsRecent | 2023-03-18 12:03:27.938332+00
 013.FixTrackedTransactions  | 2023-03-18 12:03:27.947004+00
 014.FixAddressReuse         | 2023-03-18 12:03:27.996194+00
(14 rows)
```

**Comment by hemangjoshi37a** [comment] 2023-04-25 18:12
@selukov, I've analyzed the issue and here's a potential solution to resolve the synchronization hanging problem:

1. First, stop your BTCPay Server and NBXplorer containers using the following command:
```
docker-compose down
```

2. Next, we need to remove the existing `nbxplorermainnet` database. To do this, execute the following commands:
```
docker exec -it btcpay-server_postgres.1.j2pe3b7idahp8khf1ny4gyh6m psql -U postgres
postgres=# DROP DATABASE nbxplorermainnet;
```

3. Now, start your BTCPay Server and NBXplorer containers again using the following command:
```
docker-compose up -d
```

When you restart the containers, the `nbxplorermainnet` database will be created automatically, and the synchronization process should begin without issues. This operation won't affect the main server's data, as it only involves the `nbxplorermainnet` database.

Please try these steps and let me know if the synchronization issue is resolved or if you need further assistance.

**Comment by selukov** [comment] 2023-04-26 00:25
It worked, thank you, at first there was an error see below, but then everything worked

```
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at NBXplorer.Backends.Postgres.PostgresRepository.TrimmingEvents(Int32 maxEvents, CancellationToken cancellationToken) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 1156
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 210
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 5 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 210
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop()
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.StartAsync(CancellationToken cancellationToken) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 492
   at NBXplorer.Backends.Postgres.PostgresIndexers.<>c__DisplayClass27_0.<StartAsync>b__0(IIndexer v) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 601
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at NBXplorer.Backends.Postgres.PostgresIndexers.StartAsync(CancellationToken cancellationToken) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 601
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at NBXplorer.Backends.Postgres.PostgresIndexers.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.<>c__DisplayClass3_0.<StartAsync>b__0(IHostedService service)
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at NBXplorer.Backends.Postgres.PostgresRepositoryProvider.StartAsync(CancellationToken cancellationToken) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 101
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at NBXplorer.Backends.Postgres.PostgresRepository.TrimmingEvents(Int32 maxEvents, CancellationToken cancellationToken) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 1156
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 210
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 240001
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
info: NBXplorer.Indexer.BTC: Current Index Progress not found, start syncing from the header's chain tip (At height: 787012)
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => Ready
info: NBXplorer.Events: BTC: New block 00000000000000000001231ad56982a94b051bea81969cca1a1dbac17a3392bd (787012)
info: NBXplorer.Events: BTC: New block 00000000000000000000de3360998be6426588227d6cc6203c4cd6eb263a5cc6 (787013)
info: NBXplorer.Events: BTC: New block 00000000000000000000f8ae7a2f52a095c2c3ae230a48da3d3f869c4f91eabf (787014)
```

**Comment by selukov** [comment] 2023-04-26 00:36
but
btcpay-server_clightning_bitcoin is crash 
```
network=bitcoin added in /root/.lightning/config
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
Waiting /var/lib/tor/hidden_services/c-lightning/hostname to be created by tor...
announce-addr=jobbxgauvxskpa2fp55bzltww3pif7orzqkynyvggumybnzmv7acvkad.onion:9735 added to /root/.lightning/config
rpc-file=/root/.lightning/lightning-rpc added to /root/.lightning/config
Installing bundled plugins
C-Lightning starting, listening on port 9735
Refusing to irreversibly upgrade db from version 190 to 216 in non-final version basedon-v23.02-1 (use --database-upgrade=true to override)
2023-04-26T00:31:03.576Z INFO    lightningd: Refusing to irreversibly upgrade db from version 190 to 216 in non-final version basedon-v23.02-1 (use --database-upgrade=true to override)
```
and btcpay-server_clightning_bitcoin_rest is crash 
```
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
Reading config file
warn: --- Starting the cl-rest server ---
warn: --- cl-rest api server is ready and listening on port: 3001 ---
warn: --- cl-rest doc server is ready and listening on port: 4001 ---
error: Lightning client connection error
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED /root/.lightning/lightning-rpc
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:82:23)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning/lightning-rpc'
}
```

**Comment by hemangjoshi37a** [comment] 2023-04-26 12:35
Hi @selukov,

Regarding the issue with btcpay-server_clightning_bitcoin and btcpay-server_clightning_bitcoin_rest crashing, you can try the following steps to resolve it:

1. First, stop your BTCPay Server and C-Lightning containers with the following command:
```
docker-compose down
```

2. To perform the database upgrade for C-Lightning, edit your `docker-compose.yml` file and add the `--database-upgrade=true` argument to the C-Lightning container's command section. It should look something like this:

```yaml
clightning_bitcoin:
  command: lightningd --network=bitcoin --database-upgrade=true
```

3. Now, start your BTCPay Server and C-Lightning containers again using the following command:
```
docker-compose up -d
```

The C-Lightning container should now upgrade the database and start without issues. Once it's running, the btcpay-server_clightning_bitcoin_rest container should also work without any problems.

Please try these steps and let me know if the issue is resolved or if you need any further assistance.

**Comment by selukov** [comment] 2023-04-26 14:48
great clightning_bitcoin started working
```
network=bitcoin added in /root/.lightning/config
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
Waiting /var/lib/tor/hidden_services/c-lightning/hostname to be created by tor...
announce-addr=jobbxgauvxskpa2fp55bzltww3pif7orzqkynyvggumybnzmv7acvkad.onion:9735 added to /root/.lightning/config
rpc-file=/root/.lightning/lightning-rpc added to /root/.lightning/config
Installing bundled plugins
C-Lightning starting, listening on port 9735
2023-04-26T14:23:23.953Z INFO    lightningd: Updating database from version 190 to 216
2023-04-26T14:23:30.918Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
2023-04-26T14:23:31.083Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:32.087Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:33.091Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:34.094Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:35.099Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:36.103Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
2023-04-26T14:23:37.107Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000000355339058b1dd004cda24e2b6a823d564153576180888 0 exited with status 1
```

but clightning_bitcoin_charge still broken, constantly rebooting
```
Using lightningd directory mounted in /etc/lightning... 
Starting Lightning Charge
Lightning client connection error Error: connect ECONNREFUSED /etc/lightning/lightning-rpc
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/etc/lightning/lightning-rpc'
}
events.js:287
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED /etc/lightning/lightning-rpc
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/opt/charged/node_modules/clightning-client/index.js:65:23)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/etc/lightning/lightning-rpc'
}
```
the same thing happens with clightning_bitcoin_rest 
```
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
Reading config file
warn: --- Starting the cl-rest server ---
warn: --- cl-rest api server is ready and listening on port: 3001 ---
warn: --- cl-rest doc server is ready and listening on port: 4001 ---
error: Lightning client connection error
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED /root/.lightning/lightning-rpc
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:82:23)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning/lightning-rpc'
}
```

**Comment by selukov** [comment] 2023-04-29 17:11
I deleted and created docker volume
rm -rf clightning_bitcoin_datadir
rm -rf clightning_bitcoin_charge

mkdir clightning_bitcoin_datadir
mkdir clightning_bitcoin_charge

all containers and services are running :-)
But I can't get in  Core Lightning (Spark) and Ride The Lightning
[![Screenshot-from-2023-04-29-23-59-32.png](https://i.postimg.cc/bJkDnbD9/Screenshot-from-2023-04-29-23-59-32.png)](https://postimg.cc/zbDGZyky)
link https://XXXXXXX//spark/btc/?access-key=76Zqz8ghrmacLchu7O2LFuxgTZvsKJhtZ1uNnZLRPA
[![Screenshot-from-2023-04-30-00-00-08.png](https://i.postimg.cc/rssBbG1S/Screenshot-from-2023-04-30-00-00-08.png)](https://postimg.cc/gL9tLZBJ)

link https://XXXXXXX/rtl/api/authenticate/cookie?access-key=29b507658ef3f5dedcd8f3df4874d24a95f29cf8bc76f5801cb5d6c3a6986412092eb1050eba1964fafbdc0f1e7fa520858bd9890ac478b56f7665fa6eb9df33
[![Screenshot-from-2023-04-30-00-00-23.png](https://i.postimg.cc/9QxwGCxz/Screenshot-from-2023-04-30-00-00-23.png)](https://postimg.cc/ZWdqmtzh)

**Comment by NicolasDorier** [comment] 2023-05-01 09:44
are you using docker delpoyment and no fancy things on the middle such as cloudflare or another reverse proxy?

**Comment by selukov** [comment] 2023-05-03 20:16
Yes, I use nginx-proxy
I seem to have figured out what the problem is I don't have your nginx settings
```code	
       location /spark/btc/ {
		proxy_pass http://clightning_bitcoin_spark:9737/;
	}
	location /lightning-charge/btc/ {
		proxy_pass http://clightning_bitcoin_charge:9112/;
	}
	location /clightning-rest/btc/ {
	    rewrite ^/clightning-rest/btc/(.*) /$1 break;
		proxy_pass http://clightning_bitcoin_rest:3001/;
	}
	location /rtl/ {
		proxy_pass http://bitcoin_rtl:3000/rtl/;
```

**Comment by NicolasDorier** [comment] 2023-08-28 01:03
Closing this one. Discussion side tracked on a different issue and original issue fixed.

This isn't clear what caused nbx to hang. We should monitor if that happen again to people and let me know.

**Closed by NicolasDorier** 2023-08-28 01:03 UTC
