### ISSUE TITLE
Send a message for seller

### ISSUE THREAD

**Issue by Luca399** [btcpayserver/btcpayserver#1317] opened 2020-02-03 16:56 UTC
Is it possible, when paying, above the "Contact & Refund Email", to have an optional thing like "Do you have a message for seller?", something like there is in Paypal?

<img width="290" alt="SendMessage4Seller" src="https://user-images.githubusercontent.com/59049675/73672837-e5fbea80-46ad-11ea-8b0e-5bf349790966.png">

This can be made the same like "Contact & Refund Email", so to have the option to enable/disable it. Also, would be useful to add it in the transmuter, so for example to be able to email this message  to different recipients.

Or how much would cost me if anybody wants to develope it for me? :)

**Comment by NicolasDorier** [comment] 2020-02-04 07:44
Issue transferred to BTCPayServer repo. I think @Kukks and @rockstardev wanted to add some options in the checkout page long ago.

**Comment by Kukks** [comment] 2020-02-04 07:48
Duplicate of #863

**Comment by pavlenex** [comment] 2020-02-05 09:12
Closing since it's a duplicate, @Luca399 feel free to comment on issue #863

**Closed by pavlenex** 2020-02-05 09:12 UTC
