### ISSUE TITLE
Expired invoice remains as new

### ISSUE THREAD

**Issue by mondoir** [btcpayserver/btcpayserver#1302] opened 2020-01-23 21:46 UTC
Sometimes when an invoice expires, its status wont get updated as Expired.
This happens when there are more than 20 invoices generated despite their status.
According to the attached image, it shows the timer reaches zero but the address still showing.
This particular invoice expired 40 minutes prior to the time of this report.
There were no IPN call after the invoice was created according to the picture bellow.

<img width="363" alt="Screenshot 2020-01-23 at 21 40 35" src="https://user-images.githubusercontent.com/56967158/73026594-9d307000-3e29-11ea-8a4c-7bf8699dc507.png">
<img width="877" alt="Screenshot 2020-01-23 at 21 45 45" src="https://user-images.githubusercontent.com/56967158/73026683-c5b86a00-3e29-11ea-8502-4dbe0b147bb9.png">
<img width="384" alt="Screenshot 2020-01-23 at 21 45 56" src="https://user-images.githubusercontent.com/56967158/73026689-c8b35a80-3e29-11ea-9506-a3f37fd634d7.png">

**Comment by pavlenex** [comment] 2020-01-25 10:33
@mondoir Can you please follow the template next time when you're opening an issue, it helps us troubleshoot faster.

So to replicate this: 
Create 20 invoices in BTCPay one after another?
Which version of BTCPay are you running?
What's your deployment method?

**Comment by mondoir** [comment] 2020-01-25 10:40
@pavlenex sorry mate. My bad.

version: BTCPayServer v1.0.3.153
Deployment: LunaNode

This is for today.
I am not certain that generating 20 invoices one after another would certainly recreate this, but when there are many open invoices, at least one is not getting expired properly as others.

<img width="1113" alt="Screenshot 2020-01-25 at 10 37 32" src="https://user-images.githubusercontent.com/56967158/73119789-d3bbd700-3f5e-11ea-98bb-95910a0ad637.png">

**Comment by pavlenex** [comment] 2020-01-25 10:42
No worries, thanks for providing the info. Someone already reported this a while ago but we were never able to replicate it. Knowing that it probably happens when there are a lot of invoices may be a progress.

**Comment by pavlenex** [comment] 2020-01-27 12:12
I've tried this on v1.0.3.155 and can confirm it's a bug.

Link to expired invoice https://pay.pavlenex.com/i/UrRjBb9JcV5jJMMfrFfmig

```

Date | Message
-- | --
1/27/2020 12:56:05 PM | Creation of invoice starting
1/27/2020 12:56:05 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)
1/27/2020 12:56:05 PM | BTC_USD: The evaluated rating rule is 8668.917
1/27/2020 12:56:05 PM | BTC (Off-Chain): Payment method details creation took 18 milliseconds
1/27/2020 12:56:05 PM | BTC (On-Chain): Payment method details creation took 25 milliseconds
1/27/2020 12:56:05 PM | Saving invoice took 16 milliseconds
1/27/2020 12:56:05 PM | Invoice UrRjBb9JcV5jJMMfrFfmig new event: invoice_created (1001)
```

```
info: Events:         Invoice UrRjBb9JcV5jJMMfrFfmig new event: invoice_created (1001)
info: Events:         Invoice MA8QLfDpEzCdJdU2W9oWAE new event: invoice_created (1001)
info: Events:         Invoice SxtFCo23BuPtMBM6iiiHE6 new event: invoice_created (1001)
info: Events:         BTC: New block
info: Events:         Invoice status is expired
info: Events:         Invoice M4ztx3mDu6fGTk7TXL7wYV new event: invoice_expired (1004)
info: Events:         Invoice status is expired
info: Events:         Invoice 5sn5LqUMb1UaCa9PGgxwMG new event: invoice_expired (1004)
info: Events:         Invoice status is expired
info: Events:         Invoice BXuSfZ2TRNPNFacyEaUqmG new event: invoice_expired (1004)
info: Events:         Invoice status is expired
info: Events:         Invoice MA8QLfDpEzCdJdU2W9oWAE new event: invoice_expired (1004)
info: Events:         Invoice status is expired
info: Events:         Invoice SxtFCo23BuPtMBM6iiiHE6 new event: invoice_expired (1004)
```

**UrRjBb9JcV5jJMMfrFfmig** never expired.

NBX

My logs are spammed with this message for months now, so I am quite certain this is not the issue, still leaving it here.

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLSV3UTPANK8", Request id "0HLSV3UTPANK8:00001503": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.RPCClientExtensions.GetBlockchainInfoAsyncEx(RPCClient client) in /source/NBXplorer/RPCClientExtensions.cs:line 80
   at NBXplorer.Controllers.MainController.GetStatus(String cryptoCode) in /source/NBXplorer/Controllers/MainController.cs:line 254
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

To replicate this, just create a bunch of invoices as @mondoir mentioned, there's no magical number for me, it took around 40 invoices to get the invoice that's stuck in `new` status.

**Comment by pavlenex** [comment] 2020-01-27 20:38
So on my end, it seems that after a while something triggers these invoices to expire, but it took ~4 hours (even though the timer was set to 5 min).

```

Date | Message
-- | --
1/27/2020 12:56:05 PM | Creation of invoice starting
1/27/2020 12:56:05 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)
1/27/2020 12:56:05 PM | BTC_USD: The evaluated rating rule is 8668.917
1/27/2020 12:56:05 PM | BTC (Off-Chain): Payment method details creation took 18 milliseconds
1/27/2020 12:56:05 PM | BTC (On-Chain): Payment method details creation took 25 milliseconds
1/27/2020 12:56:05 PM | Saving invoice took 16 milliseconds
1/27/2020 12:56:05 PM | Invoice UrRjBb9JcV5jJMMfrFfmig new event: invoice_created (1001)
1/27/2020 8:31:05 PM | Invoice status is expired
1/27/2020 8:31:05 PM | Invoice UrRjBb9JcV5jJMMfrFfmig new event: invoice_expired (1004)
1/27/2020 8:31:05 PM | Invoice UrRjBb9JcV5jJMMfrFfmig is not monitored anymore.
```

Take a look at the time stamps, there's a 4-hour disproportion on this particular invoice, all others expired normally.

**Comment by petzsch** [comment] 2020-02-06 14:47
same problem here:

Date | Message
-- | --
6.2.2020 15:12:20 | Creation of invoice starting
6.2.2020 15:12:20 | BTC_EUR: The rating rule is coingecko(BTC_EUR)
6.2.2020 15:12:20 | BTC_EUR: The evaluated rating rule is 8812.316
6.2.2020 15:12:20 | BTC (Off-Chain): Payment method details creation took 11 milliseconds
6.2.2020 15:12:20 | BTC (On-Chain): Payment method details creation took 31 milliseconds
6.2.2020 15:12:20 | Saving invoice took 15 milliseconds
6.2.2020 15:12:20 | Invoice HyjcteR3ujTjVXoPhjyjR9 new event: invoice_created (1001)

by the time of writing this the expiry is roughly 15 minutes overdue.

nothing unusual in the server logs.

can't post the invoice url as there is a customer's email attached to it.

**Comment by rockstardev** [comment] 2020-02-21 08:19
@pavlenex I've created 230 invoices on my machine and couldn't get this reproduced. Will need you to retest once @NicolasDorier merges PR #1345

![image](https://user-images.githubusercontent.com/5191402/75016398-85600200-5450-11ea-95d8-754e9c70e290.png)

**Comment by pavlenex** [comment] 2020-02-21 08:20
@rockstardev Aye Aye Captain. I'll test the PR and try to repro in dev env, but if remember correctly, I repro this on a live server twice.

**Comment by rockstardev** [comment] 2020-02-21 08:29
@pavlenex yeah, I'm curious if you'll be able to repro after @NicolasDorier merges changes... I think I got it with this last commit.

**Comment by rockstardev** [comment] 2020-02-21 23:10
@pavlenex + @rockstardev team delivers again, we can close this when new version is published... details here: https://github.com/btcpayserver/btcpayserver/pull/1345#issuecomment-589874869

**Comment by pavlenex** [comment] 2020-02-22 14:19
@mondoir @petzsch closing this since the fix has been merged, once you give it a try do let us know if it works for you guys, if for some reason it does not, let me know and I'll re-open.

**Closed by pavlenex** 2020-02-22 14:19 UTC
Labels: Bug, Invoice
