### ISSUE TITLE
NBXplorer headers height

### ISSUE THREAD

**Issue by Pavlos584** [btcpayserver/btcpayserver#4119] opened 2022-09-14 15:41 UTC
### What is your BTCPay version?

v 1.6.10

### How did you deploy BTCPay Server?

Ubuntu linux

### What happened?

Dash cryptocurrency is not syncing

### How did you encounter this bug?

3

### Additional information

Hello, everything was working fine the whole time, but today there was a power outage of several hours and after turning it on, I have a problem with Dash synchronization. Other cryptocurrencies sync seamlessly. I am sending a screenshot of the problem. 
![Screenshot_20220914-173256_Chrome](https://user-images.githubusercontent.com/108590410/190200182-de8316c8-780c-4094-ad50-c1ad365bb252.jpg)

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by Pavlos584** [comment] 2022-09-14 17:43
I tried restarting the server and then updating but to no avail.

**Comment by Pavlos584** [comment] 2022-09-15 17:56
Today after another reboot litecoin also stopped working, what should I do?

**Comment by Pavlos584** [comment] 2022-09-15 17:57
![Uploading Screenshot_20220915-195711_Chrome.jpg…]()

**Comment by Pavlos584** [comment] 2022-09-15 17:58
![Screenshot_20220915-195711_Chrome](https://user-images.githubusercontent.com/108590410/190476464-46f6c2dd-c20c-4483-aa7b-1fa521daed1f.jpg)

**Comment by pavlenex** [comment] 2022-09-16 16:52
This is duplicate of #904, unfortunately we can't really help with shitcoins, as we're not maintaing them. At first look restarting your server may help, but you have so many coins, so perhaps you need a better VPS. Anyway, see some solutions in #904 and I'll close this one.

**Closed by pavlenex** 2022-09-16 16:52 UTC
