### ISSUE TITLE
full explanation of settings.config

### ISSUE THREAD

**Issue by P0u1us** [btcpayserver/btcpayserver#748] opened 2019-04-09 21:01 UTC
**Describe the problem/bug**
Missing full explanation of settings.config; have build a full LND&BTCpayServer instance from base (not docker) on Ubuntu; end result is 2 issues on the service tab under server settings which dont seem to work (in my perception due to not properly reading config file):
clicking "see info" LND REST server... gives: Error: Macaroon not found
using "see info" LND gRPC server... provides nearly blank (unusefull) connection code

**Your environment**
* Version of BTCPay Server:
Have build a full LND&BTCpayServer instance from base (not docker) on Ubuntu;
* Deployment method: 
Manually build
* Other relevant environment details:
Noticed that all questions related to non-docker implementations are answered with: use docker build; keen to understand all basics by using this implementation; if this is not supported then please remove the ability for any non-docker installs, much appreciate your effort.

All other functions are running properly:
NBXplorer, LND, BitcoinQT & PostgresDB and communicate with BTCpayServer

**Logs (if applicable)**
The basic logs show a proper start of the BTCpayServer
2019-04-09 20:50:02.606 +02:00 [INF] Network: Mainnet
2019-04-09 20:50:02.644 +02:00 [INF] Supported chains: BTC
2019-04-09 20:50:02.645 +02:00 [INF] LogFile: /root/.btcpayserver/Main/btcdebug.log
2019-04-09 20:50:02.645 +02:00 [INF] Log Level: Debug
2019-04-09 20:50:02.646 +02:00 [INF] Root Path: /
2019-04-09 20:50:02.735 +02:00 [INF] Postgres DB used (User ID=cxxxxxxxt;Password=cxxxxxxxB;Host=localhost;Port=5432;Database=btcpayserver;)
2019-04-09 20:50:04.932 +02:00 [INF] BTC: Explorer url is http://127.0.0.1:24445/
2019-04-09 20:50:04.932 +02:00 [INF] BTC: Cookie file is /root/.nbxplorer/Main/.cookie
2019-04-09 20:50:05.724 +02:00 [INF] Starting listening NBXplorer (BTC)
2019-04-09 20:50:05.879 +02:00 [INF] Start watching invoices
2019-04-09 20:50:06.157 +02:00 [INF] Starting payment request expiration watcher
2019-04-09 20:50:06.556 +02:00 [INF] NBXplorer BTC: NotConnected => Ready
2019-04-09 20:50:06.569 +02:00 [INF] 0 pending payment requests being checked since last run
2019-04-09 20:50:06.674 +02:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2019-04-09 20:50:06.682 +02:00 [INF] BTC: 0 payments happened while offline
2019-04-09 20:50:06.682 +02:00 [INF] Connected to WebSocket of NBXplorer (BTC)

THIS indicates that at least some portion of the config settings are correct

**Expected behavior**
Please point to a location where I can find the details of settings.config
so that I can assure that my used information is correct.
Currently I can not be sure of the used parms
(not even sure if a comment line starts with # or ; !!!)

**Comment by NicolasDorier** [comment] 2019-04-16 02:40
Check `--help` there is a setting that look like `btclightning` or something like this.

Then follow the format of connection string documented here https://github.com/btcpayserver/BTCPayServer.Lightning/

**Comment by NicolasDorier** [comment] 2019-04-16 02:40
I think you should use docker though.

**Comment by P0u1us** [comment] 2019-04-16 06:50
HI, thanks for the feedback;
I have been fiddling a lot with the connection strings and peculiar enough got it working under the stores lightning settings with: type=lnd-rest;server=https://127.0.0.1:8080/;macaroonfilepath=/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;allowinsecure=true
Thus: using a combination of https and allowinsecure; any other combination doesnt work!? while I am sure about the fingerprint ;-)
Under store settings the gPRC string gives:
{"configurations":[{"host":"127.0.0.1","port":53280,"ssl":true,"chainType":"Mainnet","type":"grpc","cryptoCode":"BTC","certificateThumbprint":null,"macaroon":null,"adminMacaroon":null,"readonlyMacaroon":null,"invoiceMacaroon":null}]}
which to me looks incomplete?
so not really sure in what the underlying issue could be; btw I am on v1.0.3.91 and planning to upgrade today to latest.
further just puddling along and was expecting the docker comment ;-)

**Comment by NicolasDorier** [comment] 2019-04-22 08:54
well, if you don't see the macaroonfilepath, it means it does not find your macaroon.
Try to set `macaroondirectorypath=/root/.lnd/data/chain/bitcoin/mainnet` check the path is correct.

**Comment by P0u1us** [comment] 2019-04-22 14:15
Hi Nicolas, the peculiar thing is that under the store setting: the places where the LND wallets are setup... that does properly work ! In my humble opinion... that means the settings are correct ;-) Thus I am looking for if the settings are not uniformly passed with the config settings, but maybe also with envvars or something else? which could explain that they work on one settings page and not the other? I do need to note: that I am note using the default IP-ports.

**Comment by NicolasDorier** [comment] 2019-04-23 05:51
can you try the store setting with `macaroondirectorypath=` to see if it work as well?

**Comment by P0u1us** [comment] 2019-04-23 09:18
Nop: fiddled with keeping and removing the admin.macaroon filename as well, but on all:Error: Error while connecting to the API (The HTTP status code of the response was not expected (500).)
What works for BTC: type=lnd-rest;server=https://127.0.0.1:8080/;macaroonfilepath=/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;allowinsecure=true
And for LTC: type=lnd-rest;server=https://xx.yy.zz.aa:port/;macaroonfilepath=/root/.lnd/data/chain/litecoin/mainnet/admin.macaroon;certthumbprint=LotsOfScramlbledHEXnumbers;-)

**Comment by P0u1us** [comment] 2019-04-29 15:59
UPDATE: found what blocked the page to properly load and prompt with the error: macaroon not found!
file: /(user)/btcpayserver/BTCPayServer/Properties/launchSettings.json
has: ;macaroonfilepath=D:\\admin.macaroon . . . . .(windows test line ???)
appended to: BTCPAY_BTCEXTERNALLNDREST
when that is removed: the REST page on Services Settings properly loads/works!

Leaves me with my original question: I noticed in the launchSettings,json file numerous EnvVars which I can not find in the documentation; 
Is there anywhere where I can find that info? it would help tremendously ;-)

**Comment by NicolasDorier** [comment] 2019-05-02 08:24
@P0u1us yes, just run BTCPay with `--help` and you get a documentation.

**Comment by NicolasDorier** [comment] 2019-05-02 08:25
@P0u1us ok I know your problem... you need to run with `./run.sh` as documented in the README because else the test launchSettings have been applied!

**Comment by P0u1us** [comment] 2019-05-02 11:33
Hi Nicolas, thanks for the hint: I am going to pursue that, see if that gets thee job done ;-)

**Comment by P0u1us** [comment] 2019-05-03 12:44
Got it tested: and what I see is that on the services pages, there are no more services exposed!?
Could be that is correct as result of it now properly running as a dedicated BTCpay server, where the BTC-LND and LTC-LND nodes are running each on their own server... could you confirm?

**Comment by NicolasDorier** [comment] 2019-05-03 13:20
@P0u1us if you install btcpay by hand, you need to do `--help` and see all the settings to be set.

Installing btcpay manually will not install all the other component like LND nor connect them to BTCPay for you. This is why we use docker.

**Comment by P0u1us** [comment] 2019-05-03 13:49
Thnx, i do appreciate your patience!

**Comment by pavlenex** [comment] 2019-05-07 15:34
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue or comment on it at any time.

**Closed** 2019-05-08 11:19 UTC
Labels: Closing
