### ISSUE TITLE
Dash/Doge Won't Sync

### ISSUE THREAD

**Issue by MathijsCraft** [btcpayserver/btcpayserver#3156] opened 2021-11-24 21:15 UTC
So, I keep getting the issue where my data gets corrupted.
Its for the coins Dash and Dogecoin.
https://docs.btcpayserver.org/FAQ/Synchronization/#cause-4-your-bitcoin-data-directory-is-corrupted 
I followed this guide like 20x (Yes I edited the commands to the coin) I also tried to manually delete the folders.
I asked on the chat platform but they didnt have an idea either.

**Comment by pavlenex** [comment] 2021-11-26 11:33
Hey! This issue is a duplicate of #2824

Unfortunately altcoins are maintained by their communities so you'd have to reach out to them somehow. This issue has been happening for months now, but there's no effort on communities end to address this. So there's no solution but to wait, bug someone from dash/doge team or remove the coin from your deployment.

**Closed by pavlenex** 2021-11-26 11:33 UTC
