### ISSUE TITLE
Pay Button - buyer information And custom input on the checkout page

### ISSUE THREAD

**Issue by lvtz** [btcpayserver/btcpayserver#1083] opened 2019-10-10 22:17 UTC
It is already a released option to pass buyer information via the pay button?

I want to pass data using example input, but it seems it still doesn't work.

`<input type='hidden' name='buyerAddress1' value='TestAddr'>`

And the second question, is there any option to ask the buyer on Checkout Page for something? Something like second input like a buyer input with refund email.

**Comment by pavlenex** [comment] 2019-10-10 23:15
Related #863

**Comment by bolatovumar** [comment] 2019-10-23 23:54
@lvtz you can ask the user for a refund e-mail already. It's under Stores -> Settings -> Checkout experience -> Requires a refund email

![Capture](https://user-images.githubusercontent.com/1934678/67442434-ab19ef00-f5b5-11e9-91bc-f1c879c31291.PNG)

**Comment by pavlenex** [comment] 2019-11-01 15:19
Closing this one since it seems like a duplicate of the  #863

**Closed by pavlenex** 2019-11-01 15:19 UTC
Labels: need-info
