### ISSUE TITLE
How to change Contact & Refund Email invoice page

### ISSUE THREAD

**Issue by lrgeoemtry** [btcpayserver/btcpayserver#862] opened 2019-05-25 23:25 UTC
<img width="286" alt="Screenshot 2019-05-25 at 6 23 02 PM" src="https://user-images.githubusercontent.com/25958096/58375512-3b2a0e80-7f1a-11e9-8352-1065fd2e0558.png">

I'm in need of changing this copy to say somehting like 

"Insert your Ethereum Address for Delivery of tokens" 

but i can't find it 

All i can find is 
"Require a Refund Email" 

Also, how to keep the cart up for the user longer after payment? It just goes away with no confirmation of payment. 

Any help is awesome. 

Thanks

**Comment by pavlenex** [comment] 2019-05-26 00:53
You would have to fork BTCPay Server and apply changes, [maintain your own fork](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-customize-my-btcpay-theme-style) with the change, it's currently not possible to do it in an easy, non-technical and out of the box way.

**Comment by lrgeoemtry** [comment] 2019-05-26 01:00
=/
Well thanks for the answer.

Maybe make this a feature request :
Instead of
*Require Refund Email*
Which doesnt seem trustless
Make it a free form text field ?

If i could ask for the user's wallet address by Friday that would be
great...

https://images.app.goo.gl/EUCcbLEUyjL3RgJT9

Lmk if possible.

Cheers

**Comment by Kukks** [comment] 2019-05-26 05:43
If you did change the text to say that, the system is hard-coded to validate it against an email format. We have an idea on how to extend the system further to be able to add your own forms but it's still a rough idea needing to be properly specced out and developed.

No ETA.

**Comment by pavlenex** [comment] 2019-05-26 08:53
In that case, this request is a sort of a duplicate of #671 so I'll proceed with closing it.

We do have an idea to make this more configurable in the future as @Kukks.

**Closed by pavlenex** 2019-05-26 08:53 UTC
Labels: Invoice, Question
