### ISSUE TITLE
Improve off-chain/LNURL defaults for payment method on checkout

### ISSUE THREAD

**Issue by dergigi** [btcpayserver/btcpayserver#3359] opened 2022-01-26 10:06 UTC
**Describe the improvement**
Currently, you can set the default to on-chain, off-chain, and LNURL-pay. However, LNURL-pay introduces additional steps for the customer, namely setting the amount and entering an optional message/comment.

To understand this issue we have to differentiate between two types of payments/invoices:

1. **Exact**: invoice has an exact amount to be paid, e.g. `price=1337&currency=SAT`
2. **Unlimited**: no exact amount defined, e.g. a donation that can be as high as the user wants, i.e. no `price` is set

For exact payments, the simple Lightning experience ("off-chain" setting) is superior, since it is just "Scan > Approve > Done". If the checkout is set to LNURL and it is an exact payment, the experience changes to "Scan > Option to change amount > Write optional message > Approve > Done".

Granted, the amount can't be changed since the LNURL-pay `min` and `max` will be set to the `price`, i.e. the Lightning wallet UI will force the user to set the amount between 1337 and 1337 sats, to stay with the above example.

**Suggested behavior**

Use LNURL if `amount=0`, use Lightning ("off-chain") otherwise.

We could use the "Enable payment methods only when amount is" element to implement this logic. Add an "equal" in addition to the greater than / less than dropdown and add the LNURL option in addition to on-chain and off-chain.

The result would be that LNURL would be used for _unlimited_ payments, which is good, because the user has to set the amount himself anyway. If an exact amount is to be paid, it's a regular lightning invoice without any extra steps.

**Screenshots**

<img width="308" alt="Screenshot 2022-01-26 at 10 43 53" src="https://user-images.githubusercontent.com/109058/151142400-001bdaea-ea30-4bb9-97f6-9e34f68d5578.png">

<img width="531" alt="Screenshot 2022-01-26 at 10 58 10" src="https://user-images.githubusercontent.com/109058/151142417-7acba478-ae40-47e3-967a-dfaa3c4d6031.png">

I hope this makes sense.

**Comment by dergigi** [comment] 2022-01-26 10:08
Oh, and before I forget, I would also be in favor of updating the terminology. I think most people would call this "Onchain," "Lightning," and "LNURL" - not a big deal, but I thought I'd mention it while we're at it 😅

**Comment by pavlenex** [comment] 2022-01-26 13:36
Related or even a duplicate of #3324

**Comment by dergigi** [comment] 2022-01-26 20:57
Yes, looks like a duplicate - apologies for that. And it seems like Kukks already implemented it. Awesome!

**Closed** 2022-01-27 09:01 UTC
