### ISSUE TITLE
Webhook Disappeared automatically on every morning 

### ISSUE THREAD

**Issue by bhambrij-upwork** [btcpayserver/btcpayserver#2173] opened 2020-12-29 05:54 UTC
Webhook Disappeared automatically on every morning 

I have setup the webhooks under https://btc.exitpay.org/stores/<storeId>/webhooks, it's working fine for 1-2 days.

But not getting disappeared automatically on every morning, not receiving any event.

**Comment by NicolasDorier** [comment] 2021-01-01 04:00
mmh thanks a lot.
"Disappearing" do you mean that you don't receive event and you need to restart, or that the webhooks are not set anymore?

**Comment by oiiahchai** [comment] 2021-01-02 16:33
Hello, I have the same problem, webhooks for some store will disappeared if create multiple store with webhooks, and one of the newly create id and store, webhooks work fine but another new create id and store not deliver confirmed invoice.
Version: 1.0.6.4
Error found in log: 
2021-01-02 15:20:53.477 +00:00 [INF] Invoice status is paid
2021-01-02 15:20:53.477 +00:00 [INF] Invoice AxChXxEEQwGrA32UrYtf3Q new event: invoice_paidInFull (1003)
2021-01-02 15:24:26.453 +00:00 [ERR] Unexpected error when processing a webhook
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.HostedServices.WebhookNotificationManager.Process(String id, Channel`1 channel) in /source/BTCPayServer/HostedServices/WebhookNotificationManager.cs:line 235
2021-01-02 15:24:26.458 +00:00 [ERR] Unexpected error when processing a webhook
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Data.WebhookDataExtensions.GetBlob(WebhookData webhook) in /source/BTCPayServer/Data/WebhookDataExtensions.cs:line 51
   at BTCPayServer.HostedServices.WebhookNotificationManager.Process(String id, Channel`1 channel) in /source/BTCPayServer/HostedServices/WebhookNotificationManager.cs:line 211

TQ

**Comment by NicolasDorier** [comment] 2021-01-03 05:12
@oiiahchai thanks a lot this error log should help me understand the issue.

**Comment by NicolasDorier** [comment] 2021-01-03 05:34
@oiiahchai I tried to create 2 stores, with webhook to replicate the bug. But I can't replicate, anything else you did in the steps?

**Comment by oiiahchai** [comment] 2021-01-03 14:14
@NicolasDorier I also cant replicate it, not sure how it happen. one thing notice that when webhooks failed to get respond and try re-delivery it will ignore new events, maybe at the time when q for re-delivery I delete the webhooks setting and create a new webhooks will destroy all existing webhooks.

**Comment by NicolasDorier** [comment] 2021-01-04 02:55
@oiiahchai it does not ignore new events, it queue them.
If you select "automatic redelivery", BTCPaySErver try to keep the order of event, so if you manually redeliver it just put it at the end of the queue, but the last delivery that did not deliver is still in front. BTCpay will retry it after a while.

**Comment by bhambrij-upwork** [comment] 2021-01-04 09:41
Disappearing means - I need to set the webhook URL again, as it was removed
from the webhook interface automatically. As the webhook URL was removed,
therefore not receiving the events too.

**Comment by NicolasDorier** [comment] 2021-01-04 11:39
@bhambrij-upwork this seem to match error of @oiiahchai , did you find a way to reproduce this?

**Comment by bhambrij-upwork** [comment] 2021-01-04 17:48
There is no such scenario to reproduce it.

I have only one store at btc.exitpay.org, and only one webhook to receive
all the events, which is getting removed after some interval.

**Comment by NicolasDorier** [comment] 2021-01-05 03:37
@bhambrij-upwork I will try to make a new release this week that will hopefully fix it. Though I don't understand the root cause yet.

**Comment by NicolasDorier** [comment] 2021-01-12 02:51
@bhambrij-upwork @oiiahchai this should be fixed by this new release. Can you give a try? I am not sure about the root cause, so if it happens again I need to know.

**Comment by bhambrij-upwork** [comment] 2021-01-14 08:34
Today morning my webhook was again disappeared both from btc.exitpay.org
and testnet.demo.btcpayserver.org
Store Id on  btc.exitpay.org : 4zWsMAw5hwXCETzbZyUKcpqeNvM6jPwtq6USqdVGGnNQ

**Comment by NicolasDorier** [comment] 2021-01-14 09:10
@bhambrij-upwork do you own exitpay? what version are server is using? You can see that in the footer of the webpage.

**Comment by pavlenex** [comment] 2021-01-17 11:33
@bhambrij-upwork Please use a third-party host that's updated BTCPay to v1.0.6.5 or later. If your issue is not solved, please let us know, if no reply in the next few days, I'll consider it fixed and close it to clear the backlog. Thanks.

**Comment by NicolasDorier** [comment] 2021-01-17 12:09
I prefer we don't close this before we are sure the error is indeed fixed.
I did not identified the root cause, I changed code that was suspicious, but still unsure.

**Comment by NicolasDorier** [comment] 2021-01-17 12:12
I did not updated `testnet.demo.btcpayserver.org` just did now.

**Comment by pavlenex** [comment] 2021-02-27 08:07
Closing due to inactivity and the fact nobody complained about this after it's been addressed in #2178

**Closed by pavlenex** 2021-02-27 08:07 UTC
Labels: Closing, need-info

**Comment by Eskyee** [comment] 2021-03-10 13:38
I can update the BTCPayJungle 1.0.6.5 to the next Update Release.
as 1.0.6.8 was a minor release, in which I tend to wait for major releases, to limit bugs found, and to keep the server smooth for our users. since I have a lot of users getting use to their BTCPay playground.  

I hope this sorts out your Webhooks problems IvanMurzak soon!

**Comment by IvanMurzak** [comment] 2021-03-28 20:43
@Eskyee here we go :)
https://github.com/btcpayserver/btcpayserver/releases/tag/v1.0.7.0
Please update BTCPayJungle to the version. Maybe it will help

**Comment by Eskyee** [comment] 2021-03-28 21:04
Yes I see, will update next week. After checking for any problems..

**Comment by Eskyee** [comment] 2021-03-29 10:48
> @Eskyee here we go :)
> https://github.com/btcpayserver/btcpayserver/releases/tag/v1.0.7.0
> Please update BTCPayJungle to the version. Maybe it will help

now!! updated  to the latest version @IvanMurzak BTCPayJungle v1.0.7.0
