### ISSUE TITLE
POS iOS Safari zoom bug

### ISSUE THREAD

**Issue by songproducer** [btcpayserver/btcpayserver#679] opened 2019-03-14 14:42 UTC
**Describe the problem/bug**
When entering the amount Safari zooms into the text field slightly, but after clicking "Done" the zoom level stays zoomed in.

**Your environment** iOS iPhone 7s+
* Version of BTCPay Server:Latest
* Deployment method: Lunanode

**Screenshots/Links**
https://imgur.com/a/wtwhJdP

**Comment by pavlenex** [comment] 2019-03-14 15:03
Replicated on iOS, that said, I don't think it's a big issue, since you can zoom out manually, but I see this can be a minor UX annoyance. We'll re-write that PoS at certain point, so this is good to know.

There are no console errors, it's just that input fields require either a hacky way to to do that or to simply [stop Safari from zooming in.](https://www.reddit.com/r/bootstrap/comments/37isod/how_to_fix_the_zooming_when_you_focus_an_input/)

**Comment by songproducer** [comment] 2019-03-14 16:02
Would look smooth without the zoom! Look forward to a fix in a future update.

**Comment by Eskyee** [comment] 2019-05-15 14:26
iPhone SE iOS 12.2 POS working fine on my iPhone, no problems found here, Pav
I Would suggest others updating there iPhone 📱

**Comment by Eskyee** [comment] 2019-05-15 14:30
My mistake I can reproduce error Pav, iPhone SE iOS 12.2

**Comment by bolatovumar** [comment] 2019-08-21 13:00
@pavlenex this is a well-known iOS issue and I had to apply the 16px fix on all projects that I worked on.

**Comment by mariodian** [comment] 2019-09-10 05:30
@bolatovumar do you think disabling zooming would fix the issue too?

`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />`

The UI is mobile friendly so there's no need for zooming anyway.

**Comment by bolatovumar** [comment] 2019-09-11 02:47
@mariodian disabling the zoom doesn't fix it as far as I'm aware but I'm not 100% confident. I can test it on an iOS device later to know for sure.

https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by bolatovumar** [comment] 2019-09-11 02:48
@mariodian also I wouldn't disable zooming since you never know when or why people might wanna zoom in on something. Also disabling zooming because of this one issue seems like an overkill.

**Comment by bolatovumar** [comment] 2019-09-11 17:17
As suspected this is easily fixable by increasing the input font size to 16px. See the difference between two inputs in the GIF below. Tapping into the first one doesn't trigger zooming because it's a 16px input. Tapping into the second one triggers zooming.

![btcpay](https://user-images.githubusercontent.com/1934678/64719404-087e3480-d47d-11e9-8070-d3d5107bdd62.gif)

**Comment by pavlenex** [comment] 2020-05-07 23:32
I've just tried and this no longer seems to be the issue. Probably fixed by #1544 If it's still the issue let me know and will re-open.

**Closed by pavlenex** 2020-05-07 23:32 UTC
Labels: App, PoS, UI / UX, good first issue
